/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cheese',
   styleUrl: './crai-icon-cheese.css',
   shadow: true,
   })
export class CraiIconCheese {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19 15a2 2 0 1 1-4 0 2 2 0 0 1 4 0M8 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m16-.993V18.5a5.506 5.506 0 0 1-5.5 5.5H6.025a5.51 5.51 0 0 1-5.21-3.732A14.37 14.37 0 0 1 .8 10.78a19.45 19.45 0 0 1 6.944-9.72A5.46 5.46 0 0 1 14.03.933l7.29 4.816A6.56 6.56 0 0 1 24 11.007M6.051 7h11.721l-5.4-3.567a2.455 2.455 0 0 0-2.83.03A16.7 16.7 0 0 0 6.052 7m14.95 4.007a3.5 3.5 0 0 0-.15-1.007H6.026a2.51 2.51 0 0 0-2.37 1.7 11.37 11.37 0 0 0 0 7.6 2.5 2.5 0 0 0 2.37 1.7H9a3 3 0 0 1 6 0h3.5a2.5 2.5 0 0 0 2.5-2.5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
