/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-truck-side',
   styleUrl: './crai-icon-truck-side.css',
   shadow: true,
   })
export class CraiIconTruckSide {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M18.682 5h-1.867a5.314 5.314 0 0 0-5.133-4H5.318A5.324 5.324 0 0 0 0 6.316v9.32a4.35 4.35 0 0 0 3.02 4.128c-.006.078-.02.154-.02.234a3 3 0 0 0 6 0h6a3 3 0 0 0 6 0c0-.08-.014-.155-.02-.233a4.355 4.355 0 0 0 3.02-4.13V10.27A5.3 5.3 0 0 0 18.682 5M21 10.27V11h-4V8h1.682A2.27 2.27 0 0 1 21 10.271M4.364 17A1.365 1.365 0 0 1 3 15.636V6.317A2.32 2.32 0 0 1 5.318 4h6.364A2.32 2.32 0 0 1 14 6.317V17zm15.273 0H17v-3h4v1.637A1.364 1.364 0 0 1 19.637 17"/></svg>
        </Host>
    );
  }
}
