/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-time-twenty-four',
   styleUrl: './crai-icon-time-twenty-four.css',
   shadow: true,
   })
export class CraiIconTimeTwentyFour {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M15 15.626a4.25 4.25 0 0 0-8.5 0 1.5 1.5 0 0 0 3 0 1.25 1.25 0 1 1 2.5 0c0 .625-1.192 1.519-2.15 2.237C8.28 19.04 6.5 20.376 6.5 22.5A1.5 1.5 0 0 0 8 24h5.5a1.5 1.5 0 1 0 0-3h-2.8c.31-.254.645-.5.955-.737C13.22 19.086 15 17.75 15 15.626M22.5 11a1.5 1.5 0 0 0-1.5 1.5V17h-.75A1.25 1.25 0 0 1 19 15.75V12.5a1.5 1.5 0 0 0-3 0v3.25A4.255 4.255 0 0 0 20.25 20H21v2.5a1.5 1.5 0 1 0 3 0v-10a1.5 1.5 0 0 0-1.5-1.5"/><path d="M22.293 2.707 20.97 4.03A12 12 0 0 0 1.5 17.811a1.5 1.5 0 1 0 2.624-1.455 8.992 8.992 0 0 1 14.71-10.19l-1.127 1.127A1 1 0 0 0 18.414 9H23a1 1 0 0 0 1-1V3.414a1 1 0 0 0-1.707-.707"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
