/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-comment-alt',
   styleUrl: './crai-icon-comment-alt.css',
   shadow: true,
   })
export class CraiIconCommentAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 0h-13A5.507 5.507 0 0 0 0 5.5v9A5.507 5.507 0 0 0 5.5 20h1.438l4.1 3.428a1.5 1.5 0 0 0 1.924 0l4.1-3.428H18.5a5.507 5.507 0 0 0 5.5-5.5v-9A5.507 5.507 0 0 0 18.5 0M21 14.5a2.5 2.5 0 0 1-2.5 2.5h-1.983a1.5 1.5 0 0 0-.962.35L12 20.322 8.445 17.35a1.5 1.5 0 0 0-.962-.35H5.5A2.5 2.5 0 0 1 3 14.5v-9A2.5 2.5 0 0 1 5.5 3h13A2.5 2.5 0 0 1 21 5.5z"/><path d="M7.5 9h3a1.5 1.5 0 0 0 0-3h-3a1.5 1.5 0 0 0 0 3m9 2h-9a1.5 1.5 0 0 0 0 3h9a1.5 1.5 0 1 0 0-3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
