/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-grid-alt',
   styleUrl: './crai-icon-grid-alt.css',
   shadow: true,
   })
export class CraiIconGridAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 0h-13A5.506 5.506 0 0 0 0 5.5v13A5.506 5.506 0 0 0 5.5 24h13a5.506 5.506 0 0 0 5.5-5.5v-13A5.506 5.506 0 0 0 18.5 0M10 14v-4h4v4zm4 3v4h-4v-4zM3 10h4v4H3zm7-3V3h4v4zm7 3h4v4h-4zm4-4.5V7h-4V3h1.5A2.5 2.5 0 0 1 21 5.5M5.5 3H7v4H3V5.5A2.5 2.5 0 0 1 5.5 3M3 18.5V17h4v4H5.5A2.5 2.5 0 0 1 3 18.5M18.5 21H17v-4h4v1.5a2.5 2.5 0 0 1-2.5 2.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
