/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-terrace',
   styleUrl: './crai-icon-terrace.css',
   shadow: true,
   })
export class CraiIconTerrace {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m21.765 5.818-6.573-4.78A5.4 5.4 0 0 0 12.176.01h-.35a5.4 5.4 0 0 0-3.019 1.028l-6.572 4.78A5.45 5.45 0 0 0 0 10.208 2.8 2.8 0 0 0 2.792 13H10.5v9.5a1.5 1.5 0 1 0 3 0V13h7.708A2.8 2.8 0 0 0 24 10.208a5.45 5.45 0 0 0-2.235-4.39M14.638 10H9.362v-.162c0-.456.134-.902.387-1.283l.059-.095L12 4.561l2.192 3.9.059.095c.253.38.387.827.387 1.283zM4 8.244l4.206-3.06-.989 1.76a5.3 5.3 0 0 0-.856 2.894V10H3.009A2.44 2.44 0 0 1 4 8.244M17.638 10v-.162a5.3 5.3 0 0 0-.856-2.894l-.99-1.76L20 8.244A2.44 2.44 0 0 1 20.991 10z"/><path d="M4.591 18H3v-2.5a1.5 1.5 0 0 0-3 0v7a1.5 1.5 0 0 0 3 0V21h1.591a.41.41 0 0 1 .409.41v1.09a1.5 1.5 0 0 0 3 0v-1.09A3.413 3.413 0 0 0 4.591 18M22.5 14a1.5 1.5 0 0 0-1.5 1.5V18h-1.59A3.413 3.413 0 0 0 16 21.41v1.09a1.5 1.5 0 1 0 3 0v-1.09a.41.41 0 0 1 .41-.41H21v1.5a1.5 1.5 0 1 0 3 0v-7a1.5 1.5 0 0 0-1.5-1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
