/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-play',
   styleUrl: './crai-icon-play.css',
   shadow: true,
   })
export class CraiIconPlay {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="m20.463 7.713-9.1-6.677A5.317 5.317 0 0 0 2.9 5.323v13.354a5.311 5.311 0 0 0 8.46 4.287l9.105-6.677a5.315 5.315 0 0 0 0-8.574zm-1.774 6.155-9.1 6.677A2.317 2.317 0 0 1 5.9 18.677V5.323a2.28 2.28 0 0 1 1.27-2.066A2.3 2.3 0 0 1 8.223 3a2.3 2.3 0 0 1 1.362.455l9.1 6.677a2.316 2.316 0 0 1 0 3.736z"/></svg>
        </Host>
    );
  }
}
