/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-hastag',
   styleUrl: './crai-icon-hastag.css',
   shadow: true,
   })
export class CraiIconHastag {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 8.999a1.5 1.5 0 0 0 0-3h-3.628l.613-4.288a1.501 1.501 0 0 0-2.97-.424l-.673 4.712h-5.97l.613-4.288a1.501 1.501 0 0 0-2.97-.424l-.673 4.712H2.5a1.5 1.5 0 1 0 0 3h3.913l-.857 6H1.5a1.5 1.5 0 0 0 0 3h3.628l-.613 4.288a1.5 1.5 0 0 0 2.97.424l.673-4.712h5.97l-.613 4.288a1.5 1.5 0 0 0 2.97.424l.673-4.712H21.5a1.5 1.5 0 1 0 0-3h-3.913l.857-6zm-7.944 6H8.587l.857-6h5.969z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
