/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-arrow-small-up',
   styleUrl: './crai-icon-arrow-small-up.css',
   shadow: true,
   })
export class CraiIconArrowSmallUp {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="m18.061 9.525-3.586-3.586a3.585 3.585 0 0 0-4.95 0L5.94 9.525a1.5 1.5 0 1 0 2.122 2.12l2.44-2.438V19a1.5 1.5 0 1 0 3 0V9.207l2.438 2.439a1.5 1.5 0 0 0 2.122 0 1.5 1.5 0 0 0 0-2.121"/></svg>
        </Host>
    );
  }
}
