/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-venus-mars',
   styleUrl: './crai-icon-venus-mars.css',
   shadow: true,
   })
export class CraiIconVenusMars {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.99 1a1 1 0 0 0-1-1h-4.57a1 1 0 0 0-.706 1.707l1.229 1.229-2.038 2.038a6.45 6.45 0 0 0-6.9.057A6.496 6.496 0 1 0 5 16.818V18H4a1.5 1.5 0 1 0 0 3h1v1.5a1.5 1.5 0 0 0 3 0V21h1a1.5 1.5 0 1 0 0-3H8v-1.191a6.5 6.5 0 0 0 2-.84A6.488 6.488 0 0 0 19.026 7.1l2.038-2.038 1.229 1.229A1 1 0 0 0 24 5.577zM3 10.5a3.486 3.486 0 0 1 4.86-3.218 6.45 6.45 0 0 0 0 6.436A3.487 3.487 0 0 1 3 10.5M13.5 14a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
