/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-chart-network',
   styleUrl: './crai-icon-chart-network.css',
   shadow: true,
   })
export class CraiIconChartNetwork {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21 13.5a3 3 0 0 0-1.653.5l-1.02-.509a6.5 6.5 0 0 0-7.893-7.8l-.6-1.081A3 3 0 1 0 7.17 6l.6 1.074a6.49 6.49 0 0 0-1.322 8.3l-2.81 2.695A3 3 0 1 0 5.862 20.1l2.693-2.586a6.49 6.49 0 0 0 8.429-1.34l1.023.511A3 3 0 1 0 21 13.5m-9 2a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
