/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-apple',
   styleUrl: './crai-icon-apple.css',
   shadow: true,
   })
export class CraiIconApple {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M15.341 6h-.349a6.9 6.9 0 0 0 2.547-1.516 5.77 5.77 0 0 0 1.453-3.356 1 1 0 0 0-1.12-1.12 5.77 5.77 0 0 0-3.356 1.453A5.47 5.47 0 0 0 13.2 4.248a10.8 10.8 0 0 0-1.451-3.58 1.502 1.502 0 0 0-2.5 1.664A8.2 8.2 0 0 1 10.449 6h-1.79A8.845 8.845 0 0 0 0 15c-.194 5.655 5.933 10.877 11.074 8.32a1.6 1.6 0 0 1 1.948.017C18.138 25.882 24.181 20.578 24 15a8.845 8.845 0 0 0-8.659-9m0 15a1.8 1.8 0 0 1-.916-.315A4.83 4.83 0 0 0 12 20a4.74 4.74 0 0 0-2.308.657A2.07 2.07 0 0 1 8.659 21c-7.477-.246-7.474-11.756 0-12h6.682c7.479.247 7.473 11.756 0 12"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
