/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-beer',
   styleUrl: './crai-icon-beer.css',
   shadow: true,
   })
export class CraiIconBeer {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20 9h-1V5.5A1.5 1.5 0 0 0 17.5 4h-1.21a2.78 2.78 0 0 0-1.3-1.6 3.14 3.14 0 0 0-1.79-.387 1.59 1.59 0 0 1-1.44-.613 3.51 3.51 0 0 0-5.947.622A2.955 2.955 0 0 0 2.685 4H1.5A1.5 1.5 0 0 0 0 5.5v13A5.506 5.506 0 0 0 5.5 24h8a5.506 5.506 0 0 0 5.287-4H20a4 4 0 0 0 4-4v-3a4 4 0 0 0-4-4m-4 9.5a2.5 2.5 0 0 1-2.5 2.5h-8A2.5 2.5 0 0 1 3 18.5V7h.5A1.5 1.5 0 0 1 5 8.5V13a2 2 0 0 0 4 0V8.5A1.5 1.5 0 0 1 10.5 7H16zm5-2.5a1 1 0 0 1-1 1h-1v-5h1a1 1 0 0 1 1 1z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
