/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-trophy',
   styleUrl: './crai-icon-trophy.css',
   shadow: true,
   })
export class CraiIconTrophy {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 10a4 4 0 0 0-2.393-3.657c.072-.21.151-.421.213-.63a4.39 4.39 0 0 0-.705-3.9A4.47 4.47 0 0 0 17.5 0h-11a4.47 4.47 0 0 0-3.615 1.813 4.38 4.38 0 0 0-.7 3.9c.062.209.141.42.213.63A4 4 0 0 0 0 10c0 3.15 2.379 6.8 9 6.983V19.5A1.373 1.373 0 0 1 7.5 21h-1a1.5 1.5 0 1 0 0 3h11a1.5 1.5 0 1 0 0-3h-.982A1.378 1.378 0 0 1 15 19.5v-2.517c6.621-.183 9-3.833 9-6.983m-3 0c0 1.587-1.154 3.26-4.214 3.811a17.7 17.7 0 0 0 3.62-4.721A1 1 0 0 1 21 10M5.288 3.609A1.5 1.5 0 0 1 6.5 3h11a1.5 1.5 0 0 1 1.212.609 1.4 1.4 0 0 1 .231 1.253 15.6 15.6 0 0 1-4.337 6.883A6.49 6.49 0 0 0 12 16.92a6.5 6.5 0 0 0-2.606-5.177 15.6 15.6 0 0 1-4.337-6.882 1.4 1.4 0 0 1 .231-1.252M3 10a1 1 0 0 1 .594-.91 17.7 17.7 0 0 0 3.621 4.721C4.154 13.261 3 11.587 3 10"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
