/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-text-check',
   styleUrl: './crai-icon-text-check.css',
   shadow: true,
   })
export class CraiIconTextCheck {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M8.094 1.328a1.5 1.5 0 0 0-2.684 0l-5.25 10.5a1.5 1.5 0 0 0 2.682 1.342L3.429 12h6.646l.585 1.17a1.5 1.5 0 1 0 2.682-1.342zM4.929 9l1.823-3.646L8.575 9z"/><path d="M13 23.5a1.5 1.5 0 0 1-1.06-.439l-5-5a1.5 1.5 0 0 1 2.12-2.121L13 19.88l8.438-8.44a1.5 1.5 0 0 1 2.122 2.122l-9.5 9.5a1.5 1.5 0 0 1-1.06.44"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
