/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-box-alt',
   styleUrl: './crai-icon-box-alt.css',
   shadow: true,
   })
export class CraiIconBoxAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 0h-13A5.507 5.507 0 0 0 0 5.5v13A5.507 5.507 0 0 0 5.5 24h13a5.507 5.507 0 0 0 5.5-5.5v-13A5.507 5.507 0 0 0 18.5 0m2.449 5H16V3h2.5a2.5 2.5 0 0 1 2.449 2M11 3h2v4a1 1 0 0 1-2 0zM5.5 3H8v2H3.051A2.5 2.5 0 0 1 5.5 3m13 18h-13A2.5 2.5 0 0 1 3 18.5V8h5.142a3.98 3.98 0 0 0 7.716 0H21v10.5a2.5 2.5 0 0 1-2.5 2.5m.5-3.5a1.5 1.5 0 0 1-1.5 1.5h-3a1.5 1.5 0 1 1 0-3h3a1.5 1.5 0 0 1 1.5 1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
