/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-folder-add',
   styleUrl: './crai-icon-folder-add.css',
   shadow: true,
   })
export class CraiIconFolderAdd {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M16.5 14a1.5 1.5 0 0 1-1.5 1.5h-1.5V17a1.5 1.5 0 1 1-3 0v-1.5H9a1.5 1.5 0 1 1 0-3h1.5V11a1.5 1.5 0 1 1 3 0v1.5H15a1.5 1.5 0 0 1 1.5 1.5M24 8.5v9a5.506 5.506 0 0 1-5.5 5.5h-13A5.506 5.506 0 0 1 0 17.5v-11A5.506 5.506 0 0 1 5.5 1H8a1.5 1.5 0 0 1 .671.158L12.354 3H18.5A5.506 5.506 0 0 1 24 8.5m-3 0a2.5 2.5 0 0 0-.051-.5H3v9.5A2.5 2.5 0 0 0 5.5 20h13a2.5 2.5 0 0 0 2.5-2.5z"/></svg>
        </Host>
    );
  }
}
