/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-compress',
   styleUrl: './crai-icon-compress.css',
   shadow: true,
   })
export class CraiIconCompress {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M9 2.5A6.5 6.5 0 0 1 2.5 9h-1a1.5 1.5 0 0 1 0-3h1A3.5 3.5 0 0 0 6 2.5v-1a1.5 1.5 0 0 1 3 0zM16.5 24a1.5 1.5 0 0 1-1.5-1.5v-1a6.5 6.5 0 0 1 6.5-6.5h1a1.5 1.5 0 1 1 0 3h-1a3.5 3.5 0 0 0-3.5 3.5v1a1.5 1.5 0 0 1-1.5 1.5m6-15h-1A6.5 6.5 0 0 1 15 2.5v-1a1.5 1.5 0 1 1 3 0v1A3.5 3.5 0 0 0 21.5 6h1a1.5 1.5 0 0 1 0 3m-15 15A1.5 1.5 0 0 1 6 22.5v-1A3.5 3.5 0 0 0 2.5 18h-1a1.5 1.5 0 1 1 0-3h1A6.5 6.5 0 0 1 9 21.5v1A1.5 1.5 0 0 1 7.5 24"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
