/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-sword',
   styleUrl: './crai-icon-sword.css',
   shadow: true,
   })
export class CraiIconSword {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.268.734A2.49 2.49 0 0 0 20.961.06 15.96 15.96 0 0 0 14.14 4.2l-8.218 8.222a15 15 0 0 0-4.21-1.407 1.5 1.5 0 0 0-.429 2.969c1.674.317 3.263.98 4.667 1.944L3 18.879l-.439-.44a1.5 1.5 0 0 0-2.122 2.123l3 3a1.5 1.5 0 1 0 2.122-2.122l-.44-.44 2.95-2.95a12.3 12.3 0 0 1 1.945 4.667 1.5 1.5 0 0 0 2.971-.431 15 15 0 0 0-1.407-4.21L19.8 9.86a17.75 17.75 0 0 0 4.144-6.82 2.49 2.49 0 0 0-.676-2.306m-5.592 7.005L9.9 15.515c-.212-.252-.432-.5-.673-.742a11 11 0 0 0-.741-.672l7.775-7.776a13.9 13.9 0 0 1 4.364-2.95 14 14 0 0 1-2.949 4.364"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
