/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-file-eps',
   styleUrl: './crai-icon-file-eps.css',
   shadow: true,
   })
export class CraiIconFileEps {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M11.608 3.529h-.838l.006 1.723h.832c.48.002.874-.38.889-.86a.887.887 0 0 0-.889-.863"/><path d="M19.5 0h-15A4.505 4.505 0 0 0 0 4.5v15A4.505 4.505 0 0 0 4.5 24h11.984a4.47 4.47 0 0 0 3.182-1.318l3.016-3.015A4.47 4.47 0 0 0 24 16.485V4.5A4.505 4.505 0 0 0 19.5 0m-4.9 6.922a.6.6 0 0 1 .761-.052l.127.1c.249.218.536.388.847.5.32.094.662.081.975-.035a.73.73 0 0 0 .456-.409.56.56 0 0 0-.149-.578 1.3 1.3 0 0 0-.482-.276 33 33 0 0 1-1.233-.484 1.93 1.93 0 0 1-.96-.735 1.6 1.6 0 0 1-.235-1.1c.031-.211.101-.415.207-.6a1.82 1.82 0 0 1 1.026-.826c.82-.219 1.695-.1 2.427.331.163.081.303.203.406.354a.61.61 0 0 1-.032.737c-.237.281-.583.2-.878.074a8 8 0 0 0-.82-.309 1.5 1.5 0 0 0-.607-.088.6.6 0 0 0-.49.328.59.59 0 0 0 .15.618c.169.151.374.255.595.3.279.072.562.124.836.217.333.112.64.29.905.521.47.4.697 1.015.6 1.624a2.14 2.14 0 0 1-2.181 1.655 3.14 3.14 0 0 1-2.3-.984.625.625 0 0 1 .049-.883M10.141 2.28h1.465a2.11 2.11 0 1 1 0 4.219h-.84v1.666a.625.625 0 0 1-1.25 0L9.518 2.9a.6.6 0 0 1 .157-.429.62.62 0 0 1 .466-.191m-5.332.644c0-.345.28-.624.625-.624h2.2a.625.625 0 0 1 0 1.25H6.059v1.36h1.409a.625.625 0 0 1 0 1.25H6.059v1.356H7.63a.625.625 0 0 1 0 1.25h-2.2a.625.625 0 0 1-.625-.625zM21 15h-4a2 2 0 0 0-2 2v4H4.5A1.5 1.5 0 0 1 3 19.5V11h18z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
