/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-thumbtack',
   styleUrl: './crai-icon-thumbtack.css',
   shadow: true,
   })
export class CraiIconThumbtack {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M1.5 24.008a1.5 1.5 0 0 0 1.06-.44l5.95-5.954.729.753a5.3 5.3 0 0 0 3.7 1.64c.482.001.962-.08 1.417-.24a3.93 3.93 0 0 0 2.606-3.335 8.3 8.3 0 0 0-.213-2.94l-.042-.2 3.388-3.387.452.453a2.05 2.05 0 0 0 2.62.292 1.992 1.992 0 0 0 .255-3.026L16.455.641A2.05 2.05 0 0 0 13.834.35a1.993 1.993 0 0 0-.254 3.026l.52.525-3.38 3.381c-.981-.257-2-.334-3.01-.227A4.1 4.1 0 0 0 4.254 9.8a4.22 4.22 0 0 0 .977 4.423l1.2 1.236-5.991 5.99a1.5 1.5 0 0 0 1.06 2.56M7.08 10.8a1.11 1.11 0 0 1 .943-.762 5.5 5.5 0 0 1 1.955.15l.829.211a1.5 1.5 0 0 0 1.43-.393l3.983-3.984 1.754 1.76-3.964 3.965a1.5 1.5 0 0 0-.407 1.37l.225 1.062c.166.633.216 1.291.148 1.942a.91.91 0 0 1-.625.817 1.96 1.96 0 0 1-1.973-.675L7.37 12.118a1.25 1.25 0 0 1-.29-1.318"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
