/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-film',
   styleUrl: './crai-icon-film.css',
   shadow: true,
   })
export class CraiIconFilm {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 0h-13A5.506 5.506 0 0 0 0 5.5v13A5.506 5.506 0 0 0 5.5 24h13a5.506 5.506 0 0 0 5.5-5.5v-13A5.506 5.506 0 0 0 18.5 0M3 10h2v4H3zm13 .5H8V3h8zm-8 3h8V21H8zM19 10h2v4h-2zm2-4.5V7h-2V3.051A2.5 2.5 0 0 1 21 5.5M5 3.051V7H3V5.5a2.5 2.5 0 0 1 2-2.449M3 18.5V17h2v3.949A2.5 2.5 0 0 1 3 18.5m16 2.449V17h2v1.5a2.5 2.5 0 0 1-2 2.449"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
