/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-archive',
   styleUrl: './crai-icon-archive.css',
   shadow: true,
   })
export class CraiIconArchive {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M16.5 0h-9A5.506 5.506 0 0 0 2 5.5v13A5.506 5.506 0 0 0 7.5 24h9a5.506 5.506 0 0 0 5.5-5.5v-13A5.506 5.506 0 0 0 16.5 0m-9 3h9A2.5 2.5 0 0 1 19 5.5V11H5V5.5A2.5 2.5 0 0 1 7.5 3m9 18h-9A2.5 2.5 0 0 1 5 18.5V14h14v4.5a2.5 2.5 0 0 1-2.5 2.5"/><path d="M11.5 6h1a1.5 1.5 0 0 1 0 3h-1a1.5 1.5 0 0 1 0-3m0 10h1a1.5 1.5 0 0 1 0 3h-1a1.5 1.5 0 0 1 0-3"/></svg>
        </Host>
    );
  }
}
