/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-time-forward',
   styleUrl: './crai-icon-time-forward.css',
   shadow: true,
   })
export class CraiIconTimeForward {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.56 11a1.486 1.486 0 0 0-1.57 1.43 9.028 9.028 0 1 1-3.154-7.266l-1.129 1.13A.999.999 0 0 0 17.414 8H22a1 1 0 0 0 1-1V2.414a1.001 1.001 0 0 0-1.707-.707l-1.335 1.335a11.984 11.984 0 1 0 4.028 9.528A1.5 1.5 0 0 0 22.56 11"/><path d="M11.5 7A1.5 1.5 0 0 0 10 8.5v4.292a2 2 0 0 0 .586 1.414L12.379 16a1.5 1.5 0 0 0 2.12-2.12l-1.5-1.5V8.5A1.5 1.5 0 0 0 11.5 7"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
