/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-comments',
   styleUrl: './crai-icon-comments.css',
   shadow: true,
   })
export class CraiIconComments {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M8.262 18H3.5A3.5 3.5 0 0 1 0 14.5V9.232a9.31 9.31 0 0 1 3.4-7.224 8.74 8.74 0 0 1 7.368-1.83 9.01 9.01 0 0 1 7.095 7.266 8.64 8.64 0 0 1-1.894 7.156A9.98 9.98 0 0 1 8.262 18m.717-15a5.73 5.73 0 0 0-3.68 1.326A6.4 6.4 0 0 0 3 9.232V14.5a.5.5 0 0 0 .5.5h4.763a7 7 0 0 0 5.412-2.336 5.68 5.68 0 0 0 1.233-4.711 6.07 6.07 0 0 0-4.72-4.832A6.3 6.3 0 0 0 8.979 3m12 6.782a8 8 0 0 0-1-.687 10.6 10.6 0 0 1-.553 3.335A5.36 5.36 0 0 1 21 16.2v4.3a.5.5 0 0 1-.5.5h-3.86a5.95 5.95 0 0 1-4.27-1.671c-1.06.352-2.162.564-3.278.629q.316.54.716 1.02A8.85 8.85 0 0 0 16.64 24h3.86a3.5 3.5 0 0 0 3.5-3.5v-4.3a8.27 8.27 0 0 0-3.017-6.416z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
