/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-feather',
   styleUrl: './crai-icon-feather.css',
   shadow: true,
   })
export class CraiIconFeather {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.727 1.273A4.31 4.31 0 0 0 18.615.129 30.23 30.23 0 0 0 5.3 7.616a7.86 7.86 0 0 0-.969 9.933l-3.892 3.89a1.5 1.5 0 1 0 2.122 2.122l3.893-3.894A7.63 7.63 0 0 0 10.742 21a8.3 8.3 0 0 0 5.989-2.58 30.6 30.6 0 0 0 7.143-13.07 4.28 4.28 0 0 0-1.147-4.077m-3.388 1.768a1.32 1.32 0 0 1 1.269.355 1.29 1.29 0 0 1 .352 1.237A27 27 0 0 1 18.923 10h-2.8l1.44-1.439a1.5 1.5 0 0 0-2.122-2.122L11 10.879V6.844c2.553-1.715 5.37-3 8.339-3.803M6.006 13.418a4.9 4.9 0 0 1 1.417-3.683c.184-.185.386-.35.577-.527v4.671l-1.488 1.488a4.9 4.9 0 0 1-.506-1.949m8.559 2.922a5.12 5.12 0 0 1-5.941 1.16l1.936-1.936L13.121 13h4.072a23.6 23.6 0 0 1-2.628 3.34"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
