/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-ferris-wheel',
   styleUrl: './crai-icon-ferris-wheel.css',
   shadow: true,
   })
export class CraiIconFerrisWheel {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.813 7.084v-.008a10.17 10.17 0 0 0-4.487-4.188A3.99 3.99 0 0 0 12.5 0h-1a3.99 3.99 0 0 0-3.823 2.888A10.1 10.1 0 0 0 3.2 7.081a3.989 3.989 0 0 0-.947 7.5A9.9 9.9 0 0 0 7.4 20.907l-.337 1.181a1.5 1.5 0 1 0 2.884.824l.3-1.061Q11.117 22 12 22t1.753-.151l.3 1.063a1.5 1.5 0 1 0 2.884-.824L16.6 20.9a9.94 9.94 0 0 0 5.152-6.324 3.988 3.988 0 0 0-.942-7.493zM20 12h-1a1 1 0 0 1 0-2h1a1 1 0 0 1 0 2m-8.5-9h1a1 1 0 1 1 0 2h-1a1 1 0 1 1 0-2M5 12H4a1 1 0 0 1 0-2h1a1 1 0 0 1 0 2m7 7a7 7 0 0 1-.917-.076L12 15.717l.92 3.218A7 7 0 0 1 12 19m3.757-1.057-1.121-3.919A2.727 2.727 0 0 0 9.37 14l-1.125 3.933a6.9 6.9 0 0 1-2.683-2.99 3.982 3.982 0 0 0 1.1-7.573c.42-.49.906-.92 1.443-1.279A3.99 3.99 0 0 0 11.5 8h1a3.99 3.99 0 0 0 3.4-1.92 7.2 7.2 0 0 1 1.445 1.289 3.982 3.982 0 0 0 1.1 7.575 6.97 6.97 0 0 1-2.688 2.999"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
