/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-paint-brush',
   styleUrl: './crai-icon-paint-brush.css',
   shadow: true,
   })
export class CraiIconPaintBrush {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 3.94a3.9 3.9 0 0 0-1.149-2.8 3.94 3.94 0 0 0-5.516-.033L7.164 11.033a5.97 5.97 0 0 0-4.4 1.737C1.147 14.389.246 18.542.035 20.007a3.507 3.507 0 0 0 3.978 3.97c1.463-.21 5.615-1.11 7.235-2.73a5.96 5.96 0 0 0 1.691-4.88l9.88-9.641A3.9 3.9 0 0 0 24 3.94M9.123 19.128c-.652.65-3.346 1.566-5.541 1.882a.506.506 0 0 1-.577-.576c.316-2.2 1.231-4.89 1.882-5.542a3 3 0 0 1 4.236 0c.34.345.59.769.728 1.234q.027.184.1.356a3 3 0 0 1-.828 2.646m11.6-14.55-9 8.78a6 6 0 0 0-.479-.587 6 6 0 0 0-.851-.7l9.037-8.814a.928.928 0 0 1 1.502.31.92.92 0 0 1-.21 1.012z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
