/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-makeup-brush',
   styleUrl: './crai-icon-makeup-brush.css',
   shadow: true,
   })
export class CraiIconMakeupBrush {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.984 1.018a3.49 3.49 0 0 0-4.71-.184L5.648 11.754C3.573 12.227 0 13.52 0 16.8A7.21 7.21 0 0 0 7.2 24c3.282 0 4.573-3.573 5.046-5.648L23.18 5.71a3.49 3.49 0 0 0-.196-4.692M7.2 21A4.2 4.2 0 0 1 3 16.8c0-1.094 2.121-1.886 3.681-2.2L9.4 17.32C9.086 18.88 8.294 21 7.2 21M20.9 3.76l-6.247 7.223-1.637-1.635 7.211-6.236a.469.469 0 0 1 .672.648z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
