/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-key',
   styleUrl: './crai-icon-key.css',
   shadow: true,
   })
export class CraiIconKey {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M6.5 16a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3m3 7.86a7.94 7.94 0 0 0 6.065-5.26 7.8 7.8 0 0 0 .32-3.85l.681-.69A1.5 1.5 0 0 0 17 13v-2h.5A2.5 2.5 0 0 0 20 8.5V8h1.251a2.51 2.51 0 0 0 2.307-1.52 5.3 5.3 0 0 0 .416-2.635A4.317 4.317 0 0 0 19.63 0a5.47 5.47 0 0 0-3.89 1.612l-6.5 6.5a7.8 7.8 0 0 0-3.84.326A8 8 0 0 0 9.5 23.86M9.315 11.2a1.5 1.5 0 0 0 1.463-.385l7.081-7.08A2.5 2.5 0 0 1 19.63 3a1.34 1.34 0 0 1 1.36 1.149c.03.286.002.575-.08.85H19.5A2.5 2.5 0 0 0 17 7.5V8h-.5a2.5 2.5 0 0 0-2.5 2.5v1.885l-.822.83a1.5 1.5 0 0 0-.378 1.46c.279.97.253 2-.074 2.955a5 5 0 1 1-6.36-6.352 4.9 4.9 0 0 1 2.95-.077"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
