/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-document',
   styleUrl: './crai-icon-document.css',
   shadow: true,
   })
export class CraiIconDocument {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M17 12.5a1.5 1.5 0 0 1-1.5 1.5h-7a1.5 1.5 0 1 1 0-3h7a1.5 1.5 0 0 1 1.5 1.5M12.5 16h-4a1.5 1.5 0 0 0 0 3h4a1.5 1.5 0 1 0 0-3M22 8.157V18.5a5.506 5.506 0 0 1-5.5 5.5h-9A5.506 5.506 0 0 1 2 18.5v-13A5.506 5.506 0 0 1 7.5 0h6.343a5.46 5.46 0 0 1 3.89 1.611l2.656 2.657A5.46 5.46 0 0 1 22 8.157M19 18.5V9h-4a2 2 0 0 1-2-2V3H7.5A2.5 2.5 0 0 0 5 5.5v13A2.5 2.5 0 0 0 7.5 21h9a2.5 2.5 0 0 0 2.5-2.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
