/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-home-location',
   styleUrl: './crai-icon-home-location.css',
   shadow: true,
   })
export class CraiIconHomeLocation {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21.656 5.419 14.975.91a5.29 5.29 0 0 0-5.95 0L2.344 5.418A5.31 5.31 0 0 0 0 9.827v8.855A5.324 5.324 0 0 0 5.318 24h13.364A5.324 5.324 0 0 0 24 18.682V9.827a5.3 5.3 0 0 0-2.344-4.408M21 18.682A2.32 2.32 0 0 1 18.682 21H5.318A2.32 2.32 0 0 1 3 18.682V9.827a2.32 2.32 0 0 1 1.02-1.922L10.7 3.4a2.31 2.31 0 0 1 2.593 0l6.682 4.51A2.32 2.32 0 0 1 21 9.827zM12 8a5 5 0 0 0-3.536 8.535l2.649 2.591a1.27 1.27 0 0 0 1.774 0l2.648-2.591A5 5 0 0 0 12 8m0 6.554a1.5 1.5 0 1 1 0-2.999 1.5 1.5 0 0 1 0 2.999"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
