/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-hand-holding-heart',
   styleUrl: './crai-icon-hand-holding-heart.css',
   shadow: true,
   })
export class CraiIconHandHoldingHeart {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M16 2.75c0 2.163-2.82 4.851-4.225 5.978a1.24 1.24 0 0 1-1.55 0C8.82 7.6 6 4.913 6 2.75A2.634 2.634 0 0 1 8.5 0 2.634 2.634 0 0 1 11 2.75 2.634 2.634 0 0 1 13.5 0 2.634 2.634 0 0 1 16 2.75m1.818 17.661 5.2-5.943a3.884 3.884 0 1 0-5.77-5.2l-2.438 2.679A3.63 3.63 0 0 0 12.357 11H4.5A4.505 4.505 0 0 0 0 15.5v4A4.505 4.505 0 0 0 4.5 24h5.414a10.5 10.5 0 0 0 7.904-3.589M12.357 14a.641.641 0 0 1 .092 1.278l-5.161.737a1.5 1.5 0 1 0 .424 2.97l5.162-.737a3.66 3.66 0 0 0 3.093-3.116l3.5-3.843a.883.883 0 1 1 1.303 1.193l-5.206 5.955A7.5 7.5 0 0 1 9.914 21H4.5A1.5 1.5 0 0 1 3 19.5v-4A1.5 1.5 0 0 1 4.5 14z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
