/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-sun',
   styleUrl: './crai-icon-sun.css',
   shadow: true,
   })
export class CraiIconSun {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 10.5h-3.151a7.5 7.5 0 0 0-1.1-2.632l2.232-2.232a1.5 1.5 0 0 0-2.121-2.121l-2.228 2.232a7.5 7.5 0 0 0-2.632-1.1V1.5a1.5 1.5 0 1 0-3 0v3.151a7.5 7.5 0 0 0-2.632 1.1L5.636 3.515a1.5 1.5 0 0 0-2.121 2.121l2.232 2.232a7.5 7.5 0 0 0-1.1 2.632H1.5a1.5 1.5 0 1 0 0 3h3.151c.194.94.567 1.834 1.1 2.632l-2.236 2.232a1.5 1.5 0 0 0 2.121 2.121l2.232-2.232a7.5 7.5 0 0 0 2.632 1.1V22.5a1.5 1.5 0 1 0 3 0v-3.151a7.5 7.5 0 0 0 2.632-1.1l2.232 2.232a1.5 1.5 0 0 0 2.121-2.121l-2.232-2.232a7.5 7.5 0 0 0 1.1-2.632H22.5a1.5 1.5 0 0 0 0-2.996m-10.5 6a4.5 4.5 0 1 1 0-9 4.5 4.5 0 0 1 0 9"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
