/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-barber-shop',
   styleUrl: './crai-icon-barber-shop.css',
   shadow: true,
   })
export class CraiIconBarberShop {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20 8v2h2.5a1.5 1.5 0 1 1 0 3H20v2h2.5a1.5 1.5 0 1 1 0 3H20v4.5a1.5 1.5 0 1 1-3 0v-18A4.505 4.505 0 0 1 21.5 0h1a1.5 1.5 0 1 1 0 3h-1A1.5 1.5 0 0 0 20 4.5V5h2.5a1.5 1.5 0 1 1 0 3zm-4 11.25a4.735 4.735 0 0 1-8 3.45 4.739 4.739 0 1 1-5.8-7.442c1.154-1.4 2.712-3.5 4.013-5.474C4.49 6.946 3 3.829 3 1.5a1.5 1.5 0 1 1 3 0c0 1.308.827 3.268 2 5.365 1.173-2.1 2-4.058 2-5.365a1.5 1.5 0 0 1 3 0c0 2.329-1.491 5.447-3.217 8.281 1.3 1.975 2.858 4.077 4.013 5.473A4.74 4.74 0 0 1 16 19.25m-9.5 0a1.75 1.75 0 1 0-3.5 0 1.75 1.75 0 0 0 3.5 0M8 15.8a4.8 4.8 0 0 1 1.649-1A65 65 0 0 1 8 12.516 70 70 0 0 1 6.351 14.8 4.8 4.8 0 0 1 8 15.8m5 3.446a1.75 1.75 0 1 0 0 .004z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
