/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-share',
   styleUrl: './crai-icon-share.css',
   shadow: true,
   })
export class CraiIconShare {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19 14a4.97 4.97 0 0 0-3.818 1.81l-5.4-2.437c.137-.445.21-.907.218-1.373a5 5 0 0 0-.211-1.36l5.394-2.45A4.972 4.972 0 1 0 14 5c0 .142.03.276.042.415L8.1 8.112A4.95 4.95 0 0 0 5 7a5 5 0 0 0 0 10 4.95 4.95 0 0 0 3.09-1.1l5.952 2.687c-.012.139-.042.272-.042.413a5 5 0 1 0 5-5m0-11a2 2 0 1 1 0 4 2 2 0 0 1 0-4M5 14a2 2 0 1 1 0-4.001 2 2 0 0 1 0 4m14 7a2 2 0 1 1 0-4 2 2 0 0 1 0 4"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
