/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-skateboard',
   styleUrl: './crai-icon-skateboard.css',
   shadow: true,
   })
export class CraiIconSkateboard {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.561 7.439a1.5 1.5 0 0 1 0 2.122l-3 3a1.5 1.5 0 0 1-2.122-2.122l.44-.439L14 9.121l-.439.44a1.5 1.5 0 1 1-2.122-2.122l3-3a1.5 1.5 0 1 1 2.122 2.122l-.44.439.879.879.439-.44a1.5 1.5 0 0 1 2.122 0m-9.122 7-.439.44L9.121 14l.44-.439a1.5 1.5 0 0 0-2.122-2.122l-3 3a1.5 1.5 0 1 0 2.122 2.122l.439-.44.879.879-.44.439a1.5 1.5 0 1 0 2.122 2.122l3-3a1.5 1.5 0 0 0-2.122-2.122M24 7.891a7.84 7.84 0 0 1-2.312 5.579l-8.218 8.218A7.89 7.89 0 1 1 2.312 10.53l8.218-8.218A7.89 7.89 0 0 1 24 7.891m-3 0a4.89 4.89 0 0 0-8.349-3.458l-8.218 8.218a4.89 4.89 0 1 0 6.916 6.916l8.218-8.218A4.86 4.86 0 0 0 21 7.891"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
