/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-car',
   styleUrl: './crai-icon-car.css',
   shadow: true,
   })
export class CraiIconCar {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21.005 3.5a5.335 5.335 0 0 0-5-3.5H7.992A5.335 5.335 0 0 0 3 3.5L.416 10.59A6.9 6.9 0 0 0 0 12.954v2.728a5.31 5.31 0 0 0 3 4.763V22a2 2 0 0 0 4 0v-1h10v1a2 2 0 0 0 4 0v-1.555a5.31 5.31 0 0 0 3-4.763v-2.728a6.9 6.9 0 0 0-.416-2.364zM5.813 4.526A2.33 2.33 0 0 1 7.992 3h8.016a2.33 2.33 0 0 1 2.179 1.526L20.54 11H3.46zM18.682 18H5.318A2.32 2.32 0 0 1 3 15.682V14h2v.5a1.5 1.5 0 0 0 3 0V14h8v.5a1.5 1.5 0 1 0 3 0V14h2v1.682A2.32 2.32 0 0 1 18.682 18"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
