/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-bell-ring',
   styleUrl: './crai-icon-bell-ring.css',
   shadow: true,
   })
export class CraiIconBellRing {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M.22 4.283a1.5 1.5 0 0 1 .5-2.062l3.269-2a1.5 1.5 0 1 1 1.563 2.558l-3.269 2a1.5 1.5 0 0 1-2.062-.5zm23.068 13.7a1.5 1.5 0 0 0-2.064.489l-2 3.241a1.5 1.5 0 1 0 2.552 1.576l2-3.241a1.5 1.5 0 0 0-.488-2.066zm-2.453-2.5-3.6 5.865a5.53 5.53 0 0 1-4.75 2.65A5.5 5.5 0 0 1 9.1 22.815a4.183 4.183 0 0 1-5.956-5.872l-1.494-1.5a5.54 5.54 0 0 1-1.6-4.589A5.48 5.48 0 0 1 2.637 6.8l5.487-3.387A8.98 8.98 0 0 1 18.2 3.68l1.24-1.241a1.5 1.5 0 0 1 2.122 2.122L20.322 5.8a9.05 9.05 0 0 1 .513 9.686zm-3.6-8.707a6.02 6.02 0 0 0-7.52-.823l-5.499 3.4a2.5 2.5 0 0 0-1.18 1.853 2.56 2.56 0 0 0 .742 2.12l6.912 6.928a2.563 2.563 0 0 0 3.99-.473l3.574-5.818a6.025 6.025 0 0 0-1.018-7.184z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
