/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-comment-check',
   styleUrl: './crai-icon-comment-check.css',
   shadow: true,
   })
export class CraiIconCommentCheck {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 24h-5.466A13.5 13.5 0 0 1 3 19.79a11.47 11.47 0 0 1-2.947-8.9A12.024 12.024 0 0 1 9.908.187a11.64 11.64 0 0 1 9.654 2.57A12.45 12.45 0 0 1 24 12.323V18.5a5.507 5.507 0 0 1-5.5 5.5M12.03 3a9.02 9.02 0 0 0-8.988 8.164 8.5 8.5 0 0 0 2.18 6.605A10.5 10.5 0 0 0 13.034 21H18.5a2.5 2.5 0 0 0 2.5-2.5v-6.176a9.47 9.47 0 0 0-3.366-7.27A8.64 8.64 0 0 0 12.03 3M10.5 17a2.5 2.5 0 0 1-1.77-.732l-2.774-2.69a1.5 1.5 0 0 1 2.088-2.155L10.5 13.8l5.45-5.369a1.501 1.501 0 1 1 2.106 2.136l-5.796 5.708A2.48 2.48 0 0 1 10.5 17"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
