/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-check',
   styleUrl: './crai-icon-check.css',
   shadow: true,
   })
export class CraiIconCheck {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M7.75 20.663a2.57 2.57 0 0 1-1.817-.753l-5.49-5.488a1.513 1.513 0 0 1 2.14-2.14l5.166 5.166L21.417 3.78a1.513 1.513 0 0 1 2.14 2.14L9.565 19.91a2.56 2.56 0 0 1-1.816.753"/></svg>
        </Host>
    );
  }
}
