/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-trash',
   styleUrl: './crai-icon-trash.css',
   shadow: true,
   })
export class CraiIconTrash {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M23 4.5A1.5 1.5 0 0 0 21.5 3h-3.776A4.49 4.49 0 0 0 13.5 0h-3a4.49 4.49 0 0 0-4.224 3H2.5a1.5 1.5 0 0 0 0 3H3v12.5A5.5 5.5 0 0 0 8.5 24h7a5.5 5.5 0 0 0 5.5-5.5V6h.5A1.5 1.5 0 0 0 23 4.5m-5 14a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 6 18.5V6h12z"/><path d="M9.5 18a1.5 1.5 0 0 0 1.5-1.5v-6a1.5 1.5 0 0 0-3 0v6A1.5 1.5 0 0 0 9.5 18m5 0a1.5 1.5 0 0 0 1.5-1.5v-6a1.5 1.5 0 0 0-3 0v6a1.5 1.5 0 0 0 1.5 1.5"/></svg>
        </Host>
    );
  }
}
