/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-rainbow',
   styleUrl: './crai-icon-rainbow.css',
   shadow: true,
   })
export class CraiIconRainbow {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M22.5 21a1.5 1.5 0 0 1-1.5-1.5V15C20.526 3.066 3.47 3.075 3 15v4.5a1.5 1.5 0 0 1-3 0V15C.661-.924 23.345-.911 24 15v4.5a1.5 1.5 0 0 1-1.5 1.5M19 19.5V15c-.33-9.267-13.673-9.26-14 0v4.5a1.5 1.5 0 0 0 3 0V15a4 4 0 1 1 8 0v4.5a1.5 1.5 0 1 0 3 0m-5 0V15a2 2 0 0 0-4 0v4.5a1.5 1.5 0 0 0 1.5 1.5h1a1.5 1.5 0 0 0 1.5-1.5"/></svg>
        </Host>
    );
  }
}
