/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-undo-alt',
   styleUrl: './crai-icon-undo-alt.css',
   shadow: true,
   })
export class CraiIconUndoAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M7.7 15.008a1.5 1.5 0 0 1-2.121 0L.858 10.283a2.93 2.93 0 0 1 0-4.145l4.725-4.725A1.5 1.5 0 0 1 7.7 3.533L4.467 6.702H18.68A5.325 5.325 0 0 1 24 12.02v6.68a5.323 5.323 0 0 1-5.318 5.319H5.318a1.5 1.5 0 0 1 0-3H18.68A2.32 2.32 0 0 0 21 18.7v-6.68a2.32 2.32 0 0 0-2.32-2.32H4.522L7.7 12.888a1.5 1.5 0 0 1 0 2.12"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
