/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-butterfly',
   styleUrl: './crai-icon-butterfly.css',
   shadow: true,
   })
export class CraiIconButterfly {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M10 2a2 2 0 1 1 4 0 2 2 0 0 1-4 0m11.247 11.175a6.82 6.82 0 0 1 1.464 6.679 4.38 4.38 0 0 1-4.351 3.148 4.3 4.3 0 0 1-1.819-.486 17.2 17.2 0 0 1-3.041-2.025v1.057a1.5 1.5 0 1 1-3 0v-1.023a17.2 17.2 0 0 1-2.99 1.985 4.28 4.28 0 0 1-3.669.145 4.38 4.38 0 0 1-2.5-2.8 6.75 6.75 0 0 1 1.485-6.616 8 8 0 0 1-.493-.443A7.55 7.55 0 0 1 0 7.5C0 1.313 3.749 1 4.5 1 7.391 1 9.873 3.841 12 6.756 14.129 3.842 16.609 1 19.5 1c.752 0 4.5.313 4.5 6.5a7.55 7.55 0 0 1-2.326 5.29c-.135.134-.281.26-.427.385M10.5 14.513A9.8 9.8 0 0 1 7.52 15a6.8 6.8 0 0 1-1.932-.281A3.86 3.86 0 0 0 4.214 19a1.39 1.39 0 0 0 1.354.997 1.3 1.3 0 0 0 .546-.144c2.558-1.341 4.148-3.086 4.384-4.162zm0-4.7-.371-.519C9.1 7.842 6.369 4 4.5 4 3.576 4 3 5.34 3 7.5a4.54 4.54 0 0 0 1.434 3.158A4.28 4.28 0 0 0 7.48 12a5.3 5.3 0 0 0 3.02-.8zm9.548 7.879a3.77 3.77 0 0 0-1.542-2.968l-.017-.015a7.2 7.2 0 0 1-2.009.3 9.7 9.7 0 0 1-2.98-.488v1.111c.175 1.069 1.814 2.864 4.431 4.236a1.28 1.28 0 0 0 1.106.039 1.4 1.4 0 0 0 .8-.892c.139-.43.21-.877.211-1.328zM21 7.5c-.092-7.6-5.433-.722-7.124 1.787q-.207.292-.379.529V11.2a5.3 5.3 0 0 0 3.02.8 4.26 4.26 0 0 0 3.049-1.347A4.54 4.54 0 0 0 21 7.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
