/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-physics',
   styleUrl: './crai-icon-physics.css',
   shadow: true,
   })
export class CraiIconPhysics {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.4 1.592c-1.812-1.807-5-2.759-10.417 1.008C6.571-1.166 3.378-.215 1.57 1.592S-1.19 6.59 2.578 12C-1.19 17.41-.237 20.6 1.57 22.408a5.27 5.27 0 0 0 3.844 1.6c1.7 0 3.857-.7 6.569-2.594 2.713 1.89 4.868 2.595 6.569 2.595a5.27 5.27 0 0 0 3.844-1.6C24.2 20.6 25.157 17.41 21.388 12 25.157 6.59 24.2 3.4 22.4 1.592m-3.928 1.416a2.45 2.45 0 0 1 1.8.707c1.355 1.354.585 3.6-.823 5.8a45 45 0 0 0-2.4-2.584 48 48 0 0 0-2.585-2.395 8.15 8.15 0 0 1 4.008-1.528M17.617 12a43 43 0 0 1-2.688 2.944c-.73.73-1.775 1.72-2.946 2.687a43 43 0 0 1-2.945-2.687A43 43 0 0 1 6.35 12a43 43 0 0 1 2.688-2.944 43 43 0 0 1 2.945-2.688 43 43 0 0 1 2.946 2.688c.731.731 1.72 1.773 2.688 2.944M3.694 3.715a2.44 2.44 0 0 1 1.8-.707A8.14 8.14 0 0 1 9.5 4.538a46 46 0 0 0-2.585 2.395 48 48 0 0 0-2.398 2.584C3.11 7.313 2.339 5.07 3.694 3.715m0 16.57c-1.355-1.354-.584-3.6.823-5.8a45 45 0 0 0 2.4 2.584c.913.91 1.762 1.7 2.579 2.4-2.206 1.402-4.448 2.17-5.802.816m16.578 0c-1.355 1.354-3.6.586-5.8-.818a48 48 0 0 0 4.981-4.984c1.404 2.204 2.174 4.448.819 5.802"/><path d="M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
