/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-glass-cheers',
   styleUrl: './crai-icon-glass-cheers.css',
   shadow: true,
   })
export class CraiIconGlassCheers {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m1.056 22.611 2.011.625c.024.01.045.024.07.032s.05.006.075.013l2.1.652a1.5 1.5 0 0 0 .888-2.866l-.644-.2L6.2 19a5.15 5.15 0 0 0 4.955-3.7L12 12.811l.818 2.41a5.19 5.19 0 0 0 4.982 3.78l.647 1.868-.644.2a1.5 1.5 0 1 0 .888 2.866l2.1-.652c.025-.007.05 0 .075-.013l.07-.032 2.011-.625a1.5 1.5 0 1 0-.888-2.865l-.746.231-.643-1.856a5.085 5.085 0 0 0 2.118-5.753l-1.692-5A3.33 3.33 0 0 0 17 5.122l-3.55.984a3.3 3.3 0 0 0-1.45.855c-.401-.405-.9-.7-1.448-.856L7 5.123a3.31 3.31 0 0 0-4.08 2.2l-1.729 5.121a5.09 5.09 0 0 0 2.142 5.677l-.643 1.856-.746-.23a1.5 1.5 0 1 0-.888 2.864m12.985-13.45a.34.34 0 0 1 .208-.16l3.55-.985A.4.4 0 0 1 17.89 8a.37.37 0 0 1 .346.283L19.157 11h-4.6l-.538-1.587a.32.32 0 0 1 .022-.253M6.107 8q.048 0 .094.012L9.751 9a.34.34 0 0 1 .208.163.3.3 0 0 1 .041.204L9.447 11h-4.6l.933-2.76A.34.34 0 0 1 6.107 8M16.5 4a1.5 1.5 0 0 0 1.061-.439l1-1A1.5 1.5 0 1 0 16.44.44l-1 1A1.5 1.5 0 0 0 16.5 4M6.439 3.561A1.5 1.5 0 1 0 8.56 1.44l-1-1a1.5 1.5 0 0 0-2.122 2.122zM12 4a1.5 1.5 0 0 0 1.5-1.5v-1a1.5 1.5 0 1 0-3 0v1A1.5 1.5 0 0 0 12 4"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
