/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-drumstick',
   styleUrl: './crai-icon-drumstick.css',
   shadow: true,
   })
export class CraiIconDrumstick {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21.49 2.51a8.575 8.575 0 0 0-12.115 0c-2.238 2.238-3.063 7.032-3.36 10.658-.057.78.092 1.56.432 2.264l-3.1 3.1A2 2 0 1 0 2 22a2 2 0 1 0 3.469-1.348L8.56 17.56a4.4 4.4 0 0 0 2.27.425c3.628-.3 8.422-1.122 10.659-3.36a8.606 8.606 0 0 0 0-12.116m-2.121 9.99c-1.208 1.207-4.491 2.14-8.784 2.491a1.458 1.458 0 0 1-1.58-1.58c.352-4.289 1.284-7.573 2.495-8.78a5.567 5.567 0 0 1 7.869 7.87"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
