/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-caret-left',
   styleUrl: './crai-icon-caret-left.css',
   shadow: true,
   })
export class CraiIconCaretLeft {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M13.293 18.586 7.707 13a1 1 0 0 1 0-1.414L13.293 6A1 1 0 0 1 15 6.707v11.172a1 1 0 0 1-1.707.707"/></svg>
        </Host>
    );
  }
}
