/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-search-heart',
   styleUrl: './crai-icon-search-heart.css',
   shadow: true,
   })
export class CraiIconSearchHeart {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12.75 7a2.37 2.37 0 0 0-2.25 2.476A2.37 2.37 0 0 0 8.25 7 2.37 2.37 0 0 0 6 9.476c0 1.947 2.538 4.265 3.8 5.28.409.329.991.329 1.4 0 1.264-1.015 3.8-3.333 3.8-5.28A2.37 2.37 0 0 0 12.75 7"/><path d="m23.562 21.439-4.643-4.644c3.474-4.642 2.527-11.221-2.114-14.695C12.163-1.374 5.584-.427 2.11 4.215s-2.527 11.22 2.115 14.694a10.5 10.5 0 0 0 12.58 0l4.643 4.645a1.495 1.495 0 1 0 2.114-2.114zM3.082 10.542a7.47 7.47 0 1 1 7.47 7.47 7.48 7.48 0 0 1-7.47-7.47"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
