/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-phone-cross',
   styleUrl: './crai-icon-phone-cross.css',
   shadow: true,
   })
export class CraiIconPhoneCross {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.7 14.025a3.584 3.584 0 0 0-4.945 0l-.41.4a11.6 11.6 0 0 1-5.759-5.778l.388-.394a3.52 3.52 0 0 0 .04-4.91L7.86 1.025a3.583 3.583 0 0 0-4.907-.04l-1.017.883-.075.07c-7.9 8.27 11.923 28.1 20.2 20.2l.07-.075.884-1.016a3.517 3.517 0 0 0-.082-4.946zm.156 4.942q-.036.037-.07.075l-.878 1.008C14.654 24.773-.91 10.127 3.95 4.1l1.008-.877q.04-.035.076-.072a.49.49 0 0 1 .668-.04l2.152 2.313a.485.485 0 0 1-.009.717L6.736 7.267a1.5 1.5 0 0 0-.322 1.61 14.85 14.85 0 0 0 8.732 8.723 1.5 1.5 0 0 0 1.586-.332l1.127-1.109.01-.009c.278-.213.45-.21.747.04l2.237 2.074a.5.5 0 0 1 0 .703zM23.56 6.44a1.5 1.5 0 0 1-2.12 2.122l-1.94-1.94-1.94 1.94a1.5 1.5 0 0 1-2.12-2.122l1.937-1.94-1.937-1.939A1.5 1.5 0 0 1 17.56.44l1.94 1.94L21.44.44a1.5 1.5 0 1 1 2.12 2.122l-1.939 1.94z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
