/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-document-signed',
   styleUrl: './crai-icon-document-signed.css',
   shadow: true,
   })
export class CraiIconDocumentSigned {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M16.652 15.548a1.5 1.5 0 0 1-.19 2.1A5.98 5.98 0 0 1 12.993 19a3.33 3.33 0 0 1-2.178-.841 2 2 0 0 0-.236-.174 3.5 3.5 0 0 0-1.1.649 1.5 1.5 0 0 1-1.97-2.263A5.4 5.4 0 0 1 10.636 15a3.13 3.13 0 0 1 2.032.8c.256.2.27.2.326.2a3.03 3.03 0 0 0 1.55-.656 1.5 1.5 0 0 1 2.109.204M15.5 10h-7a1.5 1.5 0 0 0 0 3h7a1.5 1.5 0 1 0 0-3M22 7.157V18.5a5.506 5.506 0 0 1-5.5 5.5h-9A5.506 5.506 0 0 1 2 18.5v-13A5.506 5.506 0 0 1 7.5 0h7.343a5.46 5.46 0 0 1 3.889 1.611l1.657 1.657a5.47 5.47 0 0 1 1.61 3.889M19 18.5V7h-2a2 2 0 0 1-2-2V3H7.5A2.5 2.5 0 0 0 5 5.5v13A2.5 2.5 0 0 0 7.5 21h9a2.5 2.5 0 0 0 2.5-2.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
