/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-shield-plus',
   styleUrl: './crai-icon-shield-plus.css',
   shadow: true,
   })
export class CraiIconShieldPlus {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M15 9.5h-1.5V8a1.5 1.5 0 1 0-3 0v1.5H9a1.5 1.5 0 0 0 0 3h1.5V14a1.5 1.5 0 1 0 3 0v-1.5H15a1.5 1.5 0 1 0 0-3"/><path d="M12 24c-.21 0-.417-.045-.61-.13C11 23.7 1.91 19.568 1.91 12V7.245a5.49 5.49 0 0 1 3.76-5.218L11.526.076c.308-.102.641-.102.95 0l5.855 1.952a5.49 5.49 0 0 1 3.76 5.218V12c0 8.618-9.223 11.792-9.615 11.923A1.5 1.5 0 0 1 12 24m0-20.92L6.619 4.874a2.5 2.5 0 0 0-1.71 2.372V12c0 4.735 5.42 7.952 7.168 8.865 1.757-.733 7.014-3.383 7.014-8.865V7.246a2.5 2.5 0 0 0-1.71-2.372z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
