/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-tooth',
   styleUrl: './crai-icon-tooth.css',
   shadow: true,
   })
export class CraiIconTooth {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M17.728 0a12.2 12.2 0 0 0-3.909.64A6 6 0 0 1 12 1a6 6 0 0 1-1.82-.36A12.2 12.2 0 0 0 6.272 0 6.1 6.1 0 0 0 0 6.272c0 6.127 3.083 12.117 5.4 16.09A3.33 3.33 0 0 0 8.37 24 2.78 2.78 0 0 0 11 21.183V15a1 1 0 1 1 2 0v6.183A2.783 2.783 0 0 0 15.628 24a3.33 3.33 0 0 0 2.97-1.637C20.917 18.39 24 12.4 24 6.272A6.1 6.1 0 0 0 17.728 0M16 20.86V15a4 4 0 0 0-8 0v5.86c-2.145-3.672-5-9.184-5-14.588A3.125 3.125 0 0 1 6.272 3a9.3 9.3 0 0 1 3.036.51c.866.305 1.774.47 2.692.49a8.7 8.7 0 0 0 2.691-.49A9.2 9.2 0 0 1 17.728 3 3.12 3.12 0 0 1 21 6.272c0 5.403-2.855 10.916-5 14.588"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
