/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-pizza-slice',
   styleUrl: './crai-icon-pizza-slice.css',
   shadow: true,
   })
export class CraiIconPizzaSlice {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.072.929a3.14 3.14 0 0 0-3.347-.721L3.354 6.653a5.3 5.3 0 0 0-3.19 6.2 15.69 15.69 0 0 0 10.98 10.983 5.305 5.305 0 0 0 6.206-3.2l6.457-16.4a3.13 3.13 0 0 0-.735-3.307M19.36 7.344a2.985 2.985 0 1 0-2.178 5.531l-2.62 6.654a2.3 2.3 0 0 1-.253.459c-5.076-.126-10.173-5.223-10.3-10.3a2.3 2.3 0 0 1 .45-.248l16.328-6.426a.13.13 0 0 1 .164.036.14.14 0 0 1 .05.126zM12 12a2 2 0 1 1-4 0 2 2 0 0 1 4 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
