/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-settings',
   styleUrl: './crai-icon-settings.css',
   shadow: true,
   })
export class CraiIconSettings {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M12 7.638a4.363 4.363 0 1 0 0 8.726 4.363 4.363 0 0 0 0-8.726m0 5.726a1.363 1.363 0 1 1 0-2.726 1.363 1.363 0 0 1 0 2.726"/><path d="M22 12a9.9 9.9 0 0 0-1.04-4.415l.513-.357a1.5 1.5 0 0 0-1.715-2.461l-.515.358a9.97 9.97 0 0 0-5.743-3V1.5a1.5 1.5 0 1 0-3 0v.625a9.97 9.97 0 0 0-5.743 3l-.515-.358a1.5 1.5 0 0 0-1.715 2.461l.514.357a9.88 9.88 0 0 0 0 8.83l-.514.357a1.5 1.5 0 0 0 1.715 2.461l.515-.358a9.97 9.97 0 0 0 5.743 3v.625a1.5 1.5 0 1 0 3 0v-.625a9.97 9.97 0 0 0 5.743-3l.515.358a1.5 1.5 0 0 0 1.715-2.461l-.514-.357A9.9 9.9 0 0 0 22 12m-10 7a7 7 0 1 1 7-7 7.01 7.01 0 0 1-7 7"/></svg>
        </Host>
    );
  }
}
