/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-edit',
   styleUrl: './crai-icon-edit.css',
   shadow: true,
   })
export class CraiIconEdit {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21 11.5V15h-3a3 3 0 0 0-3 3v3H4.5A1.5 1.5 0 0 1 3 19.5v-15A1.5 1.5 0 0 1 4.5 3h9a1.5 1.5 0 0 0 0-3h-9A4.5 4.5 0 0 0 0 4.5v15A4.5 4.5 0 0 0 4.5 24h11.984a4.5 4.5 0 0 0 3.181-1.317l3.017-3.017A4.5 4.5 0 0 0 24 16.485V11.5a1.5 1.5 0 1 0-3 0"/><path d="m17.793 1.793-12.5 12.5A1 1 0 0 0 5 15v3a1 1 0 0 0 1 1h3a1 1 0 0 0 .707-.293l12.33-12.331a3.38 3.38 0 0 0 .953-3.17 3.118 3.118 0 0 0-5.197-1.413"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
