/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-browser',
   styleUrl: './crai-icon-browser.css',
   shadow: true,
   })
export class CraiIconBrowser {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M5 11.5A1.5 1.5 0 0 1 6.5 10h11a1.5 1.5 0 1 1 0 3h-11A1.5 1.5 0 0 1 5 11.5M6.5 18h7a1.5 1.5 0 1 0 0-3h-7a1.5 1.5 0 1 0 0 3M24 6.5v11a5.506 5.506 0 0 1-5.5 5.5h-13A5.506 5.506 0 0 1 0 17.5v-11A5.506 5.506 0 0 1 5.5 1h13A5.506 5.506 0 0 1 24 6.5m-16-2a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0m-5 0a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0M21 8H3v9.5A2.5 2.5 0 0 0 5.5 20h13a2.5 2.5 0 0 0 2.5-2.5z"/></svg>
        </Host>
    );
  }
}
