/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-chart-tree',
   styleUrl: './crai-icon-chart-tree.css',
   shadow: true,
   })
export class CraiIconChartTree {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21.864 18.127A5.34 5.34 0 0 0 16.674 14H13.5v-1.616a6.282 6.282 0 1 0-3 0V14H7.326a5.34 5.34 0 0 0-5.19 4.127 3 3 0 1 0 2.921.69A2.33 2.33 0 0 1 7.326 17H10.5v1.4a3 3 0 1 0 3 0V17h3.174a2.33 2.33 0 0 1 2.269 1.817 3 3 0 1 0 2.921-.69M8.718 6.283a3.282 3.282 0 1 1 6.564 0 3.282 3.282 0 0 1-6.564 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
