/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-clouds',
   styleUrl: './crai-icon-clouds.css',
   shadow: true,
   })
export class CraiIconClouds {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M2.54 20.5a1.5 1.5 0 0 1-1.118-.5 5.5 5.5 0 0 1-1.23-2.282 5.77 5.77 0 0 1 2.5-6.3 8.1 8.1 0 0 1-.541-4.823A8.05 8.05 0 0 1 8.884.087 8.184 8.184 0 0 1 17.979 6a8.26 8.26 0 0 1 4.906 3.743 1.5 1.5 0 0 1-2.585 1.518 5.22 5.22 0 0 0-3.788-2.508 1.5 1.5 0 0 1-1.289-1.288 5.12 5.12 0 0 0-2-3.419 5.2 5.2 0 0 0-3.909-.99A5.055 5.055 0 0 0 5.1 7.15a5.12 5.12 0 0 0 .455 3.3 2.483 2.483 0 0 1-1.015 3.356 2.76 2.76 0 0 0-1.44 3.157c.1.386.29.742.557 1.037a1.5 1.5 0 0 1-1.117 2.5M18.85 24a5.5 5.5 0 0 0 1.107-.134 5.15 5.15 0 0 0 .154-10.024 2 2 0 0 1-.337-.1 6.22 6.22 0 0 0-6.628-3.677A6.11 6.11 0 0 0 8 15.971q-.01.478.058.95a3.728 3.728 0 0 0 .769 6.95q.466.12.947.13zm-1.838-9.086a3.05 3.05 0 0 0 2.335 1.825 2.148 2.148 0 0 1-.047 4.2 2.5 2.5 0 0 1-.479.062H9.814a.98.98 0 0 1-.786-.56c-.123-.458.3-.825.6-.95a2.45 2.45 0 0 0 1.444-2.783 3 3 0 0 1-.067-.68 3.11 3.11 0 0 1 2.567-2.992q.236-.034.475-.036a3.2 3.2 0 0 1 2.965 1.914"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
