/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-box',
   styleUrl: './crai-icon-box.css',
   shadow: true,
   })
export class CraiIconBox {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 5.5A5.506 5.506 0 0 0 18.5 0h-13A5.506 5.506 0 0 0 0 5.5v1c0 .914.36 1.79 1 2.442V18.5A5.506 5.506 0 0 0 6.5 24h11a5.506 5.506 0 0 0 5.5-5.5V8.942c.64-.651 1-1.528 1-2.442zm-21 0A2.5 2.5 0 0 1 5.5 3h13A2.5 2.5 0 0 1 21 5.5v1a.5.5 0 0 1-.5.5h-17a.5.5 0 0 1-.5-.5zm17 13a2.5 2.5 0 0 1-2.5 2.5h-11A2.5 2.5 0 0 1 4 18.5V10h16z"/><path d="M9.5 12h5a1.5 1.5 0 0 1 0 3h-5a1.5 1.5 0 0 1 0-3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
