/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-ambulance',
   styleUrl: './crai-icon-ambulance.css',
   shadow: true,
   })
export class CraiIconAmbulance {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.009 11.951 21.19 7.86A6.51 6.51 0 0 0 15.25 4h-.458l-.549-2.642a1.793 1.793 0 0 0-3.479 0L10.21 4H5.5A5.506 5.506 0 0 0 0 9.5v8a3.5 3.5 0 0 0 3 3.45V21a3 3 0 1 0 6 0h5a3 3 0 0 0 6 0h.5a3.5 3.5 0 0 0 3.5-3.5v-.878a11.4 11.4 0 0 0-.991-4.671M21 17.5a.5.5 0 0 1-.5.5h-17a.5.5 0 0 1-.5-.5v-8A2.5 2.5 0 0 1 5.5 7h9.75q.38.004.75.091V12a2 2 0 0 0 2 2h2.586c.276.847.415 1.732.414 2.622zm-8-5a1.5 1.5 0 0 1-1.5 1.5H11v.5a1.5 1.5 0 1 1-3 0V14h-.5a1.5 1.5 0 1 1 0-3H8v-.5a1.5 1.5 0 0 1 3 0v.5h.5a1.5 1.5 0 0 1 1.5 1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
