/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-interactive',
   styleUrl: './crai-icon-interactive.css',
   shadow: true,
   })
export class CraiIconInteractive {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M2.998 9.993A6.995 6.995 0 0 1 16.9 8.932l3.087 1.121v-.06C19.987 4.474 15.513 0 9.993 0S0 4.474 0 9.993s4.474 9.994 9.993 9.994h.061L8.933 16.9a6.995 6.995 0 0 1-5.935-6.907"/><path d="M13.558 8.07c.17 0 .34.028.51.044A4.49 4.49 0 1 0 8.1 14.06a5.496 5.496 0 0 1 5.458-5.99"/><path d="M23.542 21.423 20.9 18.779l1.665-1.665a2.64 2.64 0 0 0-.965-4.347l-6.833-2.484a3.498 3.498 0 0 0-4.482 4.483l2.484 6.833a2.63 2.63 0 0 0 1.91 1.675q.284.064.577.064c.698 0 1.367-.279 1.86-.774l1.664-1.665 2.644 2.643a1.5 1.5 0 1 0 2.12-2.12m-8.152-1.376L13.1 13.742a.48.48 0 0 1 .117-.524.47.47 0 0 1 .524-.117l6.305 2.289z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
