/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-usb-pendrive',
   styleUrl: './crai-icon-usb-pendrive.css',
   shadow: true,
   })
export class CraiIconUsbPendrive {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M19 8.762V4.5A4.505 4.505 0 0 0 14.5 0h-5A4.505 4.505 0 0 0 5 4.5v4.262A4.5 4.5 0 0 0 3 12.5V15a9 9 0 0 0 18 0v-2.5a4.5 4.5 0 0 0-2-3.738M8 4.5A1.5 1.5 0 0 1 9.5 3h5A1.5 1.5 0 0 1 16 4.5V8h-2a2 2 0 1 0-4 0H8zM18 15a6 6 0 1 1-12 0v-2.5A1.5 1.5 0 0 1 7.5 11h9a1.5 1.5 0 0 1 1.5 1.5z"/></svg>
        </Host>
    );
  }
}
