/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-headphones',
   styleUrl: './crai-icon-headphones.css',
   shadow: true,
   })
export class CraiIconHeadphones {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M21 11.555v-1.56a9 9 0 1 0-18 0v1.56a5.31 5.31 0 0 0-3 4.763v.364A5.324 5.324 0 0 0 5.318 22H5.5A2.5 2.5 0 0 0 8 19.5v-6a2.5 2.5 0 0 0-2-2.449V9.994a6 6 0 1 1 12 0v1.057a2.5 2.5 0 0 0-2 2.45v6a2.5 2.5 0 0 0 2.5 2.5h.182A5.324 5.324 0 0 0 24 16.681v-.364a5.31 5.31 0 0 0-3-4.763M5 18.978a2.32 2.32 0 0 1-2-2.3v-.364a2.32 2.32 0 0 1 2-2.3zm16-2.3a2.32 2.32 0 0 1-2 2.3v-4.956a2.32 2.32 0 0 1 2 2.3z"/></svg>
        </Host>
    );
  }
}
