/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-resize',
   styleUrl: './crai-icon-resize.css',
   shadow: true,
   })
export class CraiIconResize {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 0h-8A5.507 5.507 0 0 0 5 5.5v4.525A5.507 5.507 0 0 0 0 15.5v3A5.507 5.507 0 0 0 5.5 24h3a5.506 5.506 0 0 0 5.475-5H18.5a5.507 5.507 0 0 0 5.5-5.5v-8A5.507 5.507 0 0 0 18.5 0m-10 21h-3A2.5 2.5 0 0 1 3 18.5v-3a2.5 2.5 0 0 1 2-2.449v.449a5.507 5.507 0 0 0 5.5 5.5h.449A2.5 2.5 0 0 1 8.5 21M21 13.5a2.5 2.5 0 0 1-2.5 2.5H14v-.5c0-.938-.24-1.86-.7-2.678l2.7-2.7V11.5a1.5 1.5 0 1 0 3 0v-3A3.5 3.5 0 0 0 15.5 5h-3a1.5 1.5 0 0 0 0 3h1.379l-2.7 2.7c-.818-.46-1.74-.7-2.679-.7H8V5.5A2.5 2.5 0 0 1 10.5 3h8A2.5 2.5 0 0 1 21 5.5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
