/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-reflect',
   styleUrl: './crai-icon-reflect.css',
   shadow: true,
   })
export class CraiIconReflect {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 13.5h-21a1.5 1.5 0 1 1 0-3h21a1.5 1.5 0 1 1 0 3m-3.633-6.6a2.72 2.72 0 0 0-1.549-3.116L8.863.4A3.48 3.48 0 0 0 5.52.458 3.08 3.08 0 0 0 4 3.14v2.645A3.22 3.22 0 0 0 7.215 9H16a2.8 2.8 0 0 0 2.867-2.1M14.779 6H7.215A.215.215 0 0 1 7 5.785V3.14c0-.072.009-.077.042-.1A.4.4 0 0 1 7.235 3c.082 0 7.544 3 7.544 3M8.863 23.6l8.455-3.389q.064-.026.126-.057a2.72 2.72 0 0 0 1.423-3.06A2.8 2.8 0 0 0 16 15H7.215A3.22 3.22 0 0 0 4 18.214v2.645a3.08 3.08 0 0 0 1.52 2.681 3.4 3.4 0 0 0 1.713.46 3.55 3.55 0 0 0 1.63-.4m5.916-5.6S7.557 20.9 7.5 20.93a.49.49 0 0 1-.46.025c-.033-.02-.042-.025-.042-.1v-2.641A.215.215 0 0 1 7.215 18z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
