/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-luggage-rolling',
   styleUrl: './crai-icon-luggage-rolling.css',
   shadow: true,
   })
export class CraiIconLuggageRolling {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M3 21.484V22.5a1.5 1.5 0 0 0 3 0v-.409h12v.409a1.5 1.5 0 1 0 3 0v-1.016a5.5 5.5 0 0 0 3-4.893V12.5A5.506 5.506 0 0 0 18.5 7H17V5A5 5 0 0 0 7 5v2H5.5A5.506 5.506 0 0 0 0 12.5v4.091a5.5 5.5 0 0 0 3 4.893M10 5a2 2 0 1 1 4 0v2h-4zm-7 7.5A2.5 2.5 0 0 1 5.5 10h13a2.5 2.5 0 0 1 2.5 2.5v4.091a2.5 2.5 0 0 1-2.5 2.5h-13a2.5 2.5 0 0 1-2.5-2.5zm4 1A1.5 1.5 0 0 1 8.5 12h7a1.5 1.5 0 1 1 0 3h-7A1.5 1.5 0 0 1 7 13.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
