/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-dashboard',
   styleUrl: './crai-icon-dashboard.css',
   shadow: true,
   })
export class CraiIconDashboard {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.9 11.394A12 12 0 0 0 0 12.95a11.8 11.8 0 0 0 3.761 8.678A5.18 5.18 0 0 0 7.336 23h9.322a5.32 5.32 0 0 0 3.728-1.512A11.87 11.87 0 0 0 23.9 11.394m-5.607 7.944a2.33 2.33 0 0 1-1.635.662H7.336a2.23 2.23 0 0 1-1.52-.557A8.83 8.83 0 0 1 3 12.95 8.977 8.977 0 0 1 11.988 4q.531 0 1.06.06a9.01 9.01 0 0 1 7.877 7.713 8.9 8.9 0 0 1-2.631 7.565zm-9.24-3.853a1.5 1.5 0 1 1-2.209 2.03A6.97 6.97 0 0 1 5 12.786a6.82 6.82 0 0 1 6.377-6.76 1.5 1.5 0 0 1 .246 2.99A3.79 3.79 0 0 0 8 12.786c0 1 .375 1.964 1.053 2.7m9.888-1.792a6.94 6.94 0 0 1-1.785 3.823 1.5 1.5 0 0 1-2.209-2.032 3.95 3.95 0 0 0 1.02-2.177 1.5 1.5 0 0 1 2.974.386m-4.955-.558a2 2 0 1 1-2.121-2.12l2.574-2.576a1.5 1.5 0 0 1 2.122 2.122z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
