/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cloud-check',
   styleUrl: './crai-icon-cloud-check.css',
   shadow: true,
   })
export class CraiIconCloudCheck {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M11.671 24a3.5 3.5 0 0 1-2.47-1.025l-3.39-3.42a1.5 1.5 0 1 1 2.13-2.111l3.385 3.414a.5.5 0 0 0 .7 0l5.414-5.415a1.5 1.5 0 0 1 2.122 2.122l-5.415 5.414a3.5 3.5 0 0 1-2.476 1.02m-9.586-5.1A1.536 1.536 0 0 0 3.093 17a2.76 2.76 0 0 1 1.444-3.157 2.48 2.48 0 0 0 1.012-3.355 5.12 5.12 0 0 1-.456-3.3A5.05 5.05 0 0 1 9.308 3.1a5.2 5.2 0 0 1 5.253 2.497c.343.587.566 1.237.655 1.91a1.5 1.5 0 0 0 1.29 1.289 5.17 5.17 0 0 1 4.472 5.545v.053a1.467 1.467 0 0 0 1.385 1.567 1.536 1.536 0 0 0 1.613-1.418 8.16 8.16 0 0 0-6-8.506 8.1 8.1 0 0 0-2.95-4.341A8.2 8.2 0 0 0 8.881.125 8.05 8.05 0 0 0 2.146 6.63a8.1 8.1 0 0 0 .541 4.824 5.76 5.76 0 0 0-2.5 6.293l.047.174a1.45 1.45 0 0 0 1.407 1.044q.226 0 .444-.065"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
