/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-flag',
   styleUrl: './crai-icon-flag.css',
   shadow: true,
   })
export class CraiIconFlag {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.5 4h-4.051A4.49 4.49 0 0 0 11 0H4.5A4.505 4.505 0 0 0 0 4.5v18a1.5 1.5 0 0 0 3 0V14h6.551A4.49 4.49 0 0 0 14 18h5.5a4.505 4.505 0 0 0 4.5-4.5v-5A4.505 4.505 0 0 0 19.5 4M3 4.5A1.5 1.5 0 0 1 4.5 3H11a1.5 1.5 0 0 1 1.5 1.5v5A1.5 1.5 0 0 1 11 11H3zm18 9a1.5 1.5 0 0 1-1.5 1.5H14a1.5 1.5 0 0 1-1.478-1.283A4.49 4.49 0 0 0 15.5 9.5V7h4A1.5 1.5 0 0 1 21 8.5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
