/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-interlining',
   styleUrl: './crai-icon-interlining.css',
   shadow: true,
   })
export class CraiIconInterlining {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M10.544 7h12a1.5 1.5 0 0 0 0-3h-12a1.5 1.5 0 0 0 0 3m12 4h-12a1.5 1.5 0 1 0 0 3h12a1.5 1.5 0 0 0 0-3m0 7h-12a1.5 1.5 0 1 0 0 3h12a1.5 1.5 0 1 0 0-3M5.13 7a1 1 0 0 0 .707-1.707L3.751 3.207a1 1 0 0 0-1.414 0L.251 5.293A1 1 0 0 0 .958 7h.586v11H.958a1 1 0 0 0-.707 1.707l2.05 2.048a1 1 0 0 0 1.413 0l2.048-2.048A1 1 0 0 0 5.054 18h-.51V7z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
