/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-folder',
   styleUrl: './crai-icon-folder.css',
   shadow: true,
   })
export class CraiIconFolder {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M18.5 3h-6.008a.5.5 0 0 1-.232-.057L9.315 1.4A3.5 3.5 0 0 0 7.69 1H5.5A5.506 5.506 0 0 0 0 6.5v11A5.506 5.506 0 0 0 5.5 23h13a5.506 5.506 0 0 0 5.5-5.5v-9A5.506 5.506 0 0 0 18.5 3M21 17.5a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 17.5V7.967h17.94q.06.264.06.533z"/></svg>
        </Host>
    );
  }
}
