/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-stopwatch',
   styleUrl: './crai-icon-stopwatch.css',
   shadow: true,
   })
export class CraiIconStopwatch {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M13.5 8.5a1.5 1.5 0 1 0-3 0v3.19a2 2 0 1 0 3 0z"/><path d="M22.5 5.5a1.5 1.5 0 0 0 0-3c-.841 0-1-.159-1-1a1.5 1.5 0 1 0-3 0c-.008.584.09 1.165.289 1.715l-.618.685A10.9 10.9 0 0 0 13.5 2.115V1.5a1.5 1.5 0 1 0-3 0v.615A10.9 10.9 0 0 0 5.829 3.9l-.618-.685A4.9 4.9 0 0 0 5.5 1.5a1.5 1.5 0 0 0-3 0c0 .841-.159 1-1 1a1.5 1.5 0 0 0 0 3 5 5 0 0 0 1.523-.232l.579.643a11 11 0 1 0 16.8 0l.579-.643A5 5 0 0 0 22.5 5.5M12 21a8 8 0 1 1 8-8 8.01 8.01 0 0 1-8 8"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
