/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-salad',
   styleUrl: './crai-icon-salad.css',
   shadow: true,
   })
export class CraiIconSalad {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.145 11.7a4.2 4.2 0 0 0-2.036-1.473c.39-1.127.678-2.287.86-3.465a3.306 3.306 0 0 0-3.732-3.728 20 20 0 0 0-1.707.324l-.03-.614C16.4.1 13.213-.956 11 1.092 8.154-1.492 4.366.936 5.815 4.267a5.5 5.5 0 0 0-3.7 6.31 4.255 4.255 0 0 0-1.94 4.89 14.1 14.1 0 0 0 3.546 6.04A8.76 8.76 0 0 0 9.878 24h4.244a8.77 8.77 0 0 0 6.157-2.493 14.1 14.1 0 0 0 3.548-6.04 4.25 4.25 0 0 0-.682-3.767M18.647 6a.3.3 0 0 1 .262.085.3.3 0 0 1 .087.27 17.5 17.5 0 0 1-.912 3.44q-.034.098-.054.2h-4.974a2.5 2.5 0 0 1 .68-2.29c.67-.663 2.827-1.414 4.911-1.705M7.5 7a2.49 2.49 0 0 1 2.437 3H5.063A2.49 2.49 0 0 1 7.5 7m13.447 7.626a11.25 11.25 0 0 1-2.785 4.756A5.74 5.74 0 0 1 14.122 21H9.878a5.74 5.74 0 0 1-4.04-1.62 11.2 11.2 0 0 1-2.784-4.753 1.27 1.27 0 0 1 .2-1.13 1.22 1.22 0 0 1 1-.5h15.5a1.22 1.22 0 0 1 1 .5 1.27 1.27 0 0 1 .193 1.129"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
