/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cross',
   styleUrl: './crai-icon-cross.css',
   shadow: true,
   })
export class CraiIconCross {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m14.121 12 9.44-9.438A1.5 1.5 0 0 0 21.439.44L12 9.88 2.562.44A1.5 1.5 0 1 0 .44 2.562L9.88 12 .44 21.44a1.5 1.5 0 1 0 2.122 2.122L12 14.12l9.439 9.44a1.5 1.5 0 0 0 2.122-2.122z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
