/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-marker-time',
   styleUrl: './crai-icon-marker-time.css',
   shadow: true,
   })
export class CraiIconMarkerTime {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.78 3.238a10.967 10.967 0 0 0-15.561 0 11.1 11.1 0 0 0 .043 15.656L8 22.36a5.707 5.707 0 0 0 7.977.03l3.807-3.537a11.093 11.093 0 0 0-.004-15.615M17.7 16.7l-3.8 3.525a2.754 2.754 0 0 1-3.832-.03l-3.722-3.458a8.084 8.084 0 0 1 0-11.383 7.966 7.966 0 0 1 11.307 0A8.074 8.074 0 0 1 17.7 16.7m-2.135-2.135a1.5 1.5 0 0 1-2.122 0l-2.5-2.5A1.5 1.5 0 0 1 10.5 11V7.5a1.5 1.5 0 1 1 3 0v2.88l2.061 2.06a1.5 1.5 0 0 1 0 2.121z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
