/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-screen',
   styleUrl: './crai-icon-screen.css',
   shadow: true,
   })
export class CraiIconScreen {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 2h-13A5.506 5.506 0 0 0 0 7.5v6A5.506 5.506 0 0 0 5.5 19h5v2H8a1.5 1.5 0 1 0 0 3h8a1.5 1.5 0 1 0 0-3h-2.5v-2h5a5.506 5.506 0 0 0 5.5-5.5v-6A5.506 5.506 0 0 0 18.5 2M21 13.5a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 13.5v-6A2.5 2.5 0 0 1 5.5 5h13A2.5 2.5 0 0 1 21 7.5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
