/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-camping',
   styleUrl: './crai-icon-camping.css',
   shadow: true,
   })
export class CraiIconCamping {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M5.324 23.982H18.68a5.31 5.31 0 0 0 4.8-7.587l-6.661-13.3A5.27 5.27 0 0 0 12 .02a5.25 5.25 0 0 0-4.8 3.035L.5 16.434a5.31 5.31 0 0 0 4.823 7.548m-2.11-6.266L9.9 4.358a2.32 2.32 0 0 1 4.224.04l6.662 13.3a2.31 2.31 0 0 1-2.1 3.283h-2.027l-2.952-5.895a1.882 1.882 0 0 0-3.412 0l-2.95 5.9H5.324a2.31 2.31 0 0 1-2.11-3.266z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
