/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-school-bus',
   styleUrl: './crai-icon-school-bus.css',
   shadow: true,
   })
export class CraiIconSchoolBus {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M21 10.256V5.5A4.505 4.505 0 0 0 16.5 1h-12A4.505 4.505 0 0 0 0 5.5v11a3.5 3.5 0 0 0 3 3.45V20a3 3 0 0 0 6 0h6a3 3 0 0 0 6 0v-.05a3.5 3.5 0 0 0 3-3.45v-2a4.51 4.51 0 0 0-3-4.243M3 6h3v4H3zm6 0h3v11H9zm6 0h3v4h-3zM3 13h3v4H3.5a.5.5 0 0 1-.5-.5zm18 3.5a.5.5 0 0 1-.5.5H15v-4h4.5a1.5 1.5 0 0 1 1.5 1.5z"/></svg>
        </Host>
    );
  }
}
