/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-network',
   styleUrl: './crai-icon-network.css',
   shadow: true,
   })
export class CraiIconNetwork {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 19h-7.351a3.5 3.5 0 0 0-1.649-1.649V14h7.654A1.847 1.847 0 0 0 23 12.154V11a2 2 0 0 0-2-2V4.5A4.505 4.505 0 0 0 16.5 0h-9A4.505 4.505 0 0 0 3 4.5V9a2 2 0 0 0-2 2v1.154A1.847 1.847 0 0 0 2.846 14H10.5v3.351A3.5 3.5 0 0 0 8.851 19H1.5a1.5 1.5 0 1 0 0 3h7.351a3.479 3.479 0 0 0 6.3 0H22.5a1.5 1.5 0 1 0 0-3M8.934 9.678l-.329-.356A1 1 0 0 0 7.87 9H6V4.5A1.5 1.5 0 0 1 7.5 3h9A1.5 1.5 0 0 1 18 4.5V9h-1.87a1 1 0 0 0-.735.322l-.329.356a1 1 0 0 1-.735.322H9.669a1 1 0 0 1-.735-.322"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
