/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-file-check',
   styleUrl: './crai-icon-file-check.css',
   shadow: true,
   })
export class CraiIconFileCheck {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m20.389 4.268-2.657-2.657A5.46 5.46 0 0 0 13.842 0H7.5A5.506 5.506 0 0 0 2 5.5v13A5.506 5.506 0 0 0 7.5 24h9a5.506 5.506 0 0 0 5.5-5.5V8.157a5.47 5.47 0 0 0-1.611-3.889M16.499 21h-9A2.5 2.5 0 0 1 5 18.5v-13A2.5 2.5 0 0 1 7.5 3H13v4a2 2 0 0 0 2 2h4v9.5a2.5 2.5 0 0 1-2.5 2.5m.587-9.534a1.5 1.5 0 0 1-.052 2.12L13.448 17a3.5 3.5 0 0 1-4.923-.025L7 15.62a1.501 1.501 0 1 1 2-2.24l1.586 1.414A.58.58 0 0 0 11 15a.5.5 0 0 0 .353-.146l3.613-3.44a1.5 1.5 0 0 1 2.12.052"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
