/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-keyboard',
   styleUrl: './crai-icon-keyboard.css',
   shadow: true,
   })
export class CraiIconKeyboard {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M18.5 3h-5V1.5A1.5 1.5 0 0 0 12 0a1.5 1.5 0 0 0-1.5 1.5V3h-5A5.5 5.5 0 0 0 0 8.5v7A5.5 5.5 0 0 0 5.5 21h13a5.5 5.5 0 0 0 5.5-5.5v-7A5.5 5.5 0 0 0 18.5 3M21 15.5a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 15.5v-7A2.5 2.5 0 0 1 5.5 6h13A2.5 2.5 0 0 1 21 8.5z"/><path d="M6.5 11a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m5 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m6-3h-1a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 0 0-3m-6 5h-5a1.5 1.5 0 1 0 0 3h5a1.5 1.5 0 0 0 0-3m6 0h-1a1.5 1.5 0 1 0 0 3h1a1.5 1.5 0 0 0 0-3"/></svg>
        </Host>
    );
  }
}
