/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-filter',
   styleUrl: './crai-icon-filter.css',
   shadow: true,
   })
export class CraiIconFilter {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M14.5 24a1.5 1.5 0 0 1-.77-.214l-5-3A1.5 1.5 0 0 1 8 19.5v-5.165l-5.966-7.3A4.2 4.2 0 0 1 1 4.253 4.26 4.26 0 0 1 5.253 0h13.494a4.254 4.254 0 0 1 3.18 7.079L16 14.382V22.5a1.5 1.5 0 0 1-1.5 1.5M11 18.65l2 1.2v-6a1.5 1.5 0 0 1 .335-.946l6.305-7.767a1.3 1.3 0 0 0 .36-.884A1.256 1.256 0 0 0 18.747 3H5.253a1.254 1.254 0 0 0-.937 2.086l6.346 7.765A1.5 1.5 0 0 1 11 13.8z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
