/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-mode-portrait',
   styleUrl: './crai-icon-mode-portrait.css',
   shadow: true,
   })
export class CraiIconModePortrait {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 15.5A1.5 1.5 0 0 0 21 17v1.5a2.5 2.5 0 0 1-2.5 2.5H17a1.5 1.5 0 1 0 0 3h1.5a5.506 5.506 0 0 0 5.5-5.5V17a1.5 1.5 0 0 0-1.5-1.5m-21-7A1.5 1.5 0 0 0 3 7V5.5A2.5 2.5 0 0 1 5.5 3H7a1.5 1.5 0 0 0 0-3H5.5A5.506 5.506 0 0 0 0 5.5V7a1.5 1.5 0 0 0 1.5 1.5M7 21H5.5A2.5 2.5 0 0 1 3 18.5V17a1.5 1.5 0 0 0-3 0v1.5A5.506 5.506 0 0 0 5.5 24H7a1.5 1.5 0 0 0 0-3M18.5 0H17a1.5 1.5 0 1 0 0 3h1.5A2.5 2.5 0 0 1 21 5.5V7a1.5 1.5 0 1 0 3 0V5.5A5.506 5.506 0 0 0 18.5 0M12 11a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m-5.89 6.848A.993.993 0 0 0 7.1 19h9.8a.994.994 0 0 0 .992-1.152 6 6 0 0 0-11.78 0z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
