/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-sunrise',
   styleUrl: './crai-icon-sunrise.css',
   shadow: true,
   })
export class CraiIconSunrise {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M.819 17.52a4.77 4.77 0 0 0 5.05-.3.335.335 0 0 1 .407 0 4.91 4.91 0 0 0 5.594 0 .334.334 0 0 1 .406 0 4.91 4.91 0 0 0 5.592 0 .33.33 0 0 1 .408 0 4.69 4.69 0 0 0 5.05.3 1.5 1.5 0 0 0-1.508-2.594 1.72 1.72 0 0 1-1.8-.15 3.36 3.36 0 0 0-3.883 0 1.85 1.85 0 0 1-2.116 0 3.35 3.35 0 0 0-3.884 0 1.85 1.85 0 0 1-2.117 0 3.36 3.36 0 0 0-3.883 0 1.71 1.71 0 0 1-1.806.15 1.502 1.502 0 1 0-1.506 2.6zm20.929 3.28a1.71 1.71 0 0 1-1.806-.149 3.35 3.35 0 0 0-3.882 0 1.85 1.85 0 0 1-2.118 0 3.35 3.35 0 0 0-3.883 0 1.85 1.85 0 0 1-2.117 0 3.35 3.35 0 0 0-3.883 0 1.7 1.7 0 0 1-1.806.15A1.502 1.502 0 0 0 .747 23.4a4.77 4.77 0 0 0 5.05-.3.335.335 0 0 1 .406 0 4.91 4.91 0 0 0 5.594 0 .336.336 0 0 1 .407 0 4.91 4.91 0 0 0 5.594 0 .33.33 0 0 1 .406 0 4.69 4.69 0 0 0 5.048.3 1.5 1.5 0 1 0-1.5-2.6zM3.5 12h2.7a2.34 2.34 0 0 0 2.286-1.832 3.607 3.607 0 0 1 7.034 0A2.34 2.34 0 0 0 17.8 12h2.7a1.5 1.5 0 1 0 0-3h-2.19a6.6 6.6 0 0 0-.91-1.853l1.972-1.972a1.5 1.5 0 1 0-2.122-2.121l-2.094 2.094a6.6 6.6 0 0 0-1.656-.627V1.5a1.5 1.5 0 1 0-3 0v3.021a6.6 6.6 0 0 0-1.657.626L6.75 3.054a1.5 1.5 0 0 0-2.122 2.121L6.6 7.146A6.6 6.6 0 0 0 5.689 9h-2.19a1.5 1.5 0 0 0 0 3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
