/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-bread-slice',
   styleUrl: './crai-icon-bread-slice.css',
   shadow: true,
   })
export class CraiIconBreadSlice {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M10 11.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m3.5 3.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m-5 0a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M22 17.506v-7.152a5.26 5.26 0 0 0 1.847-5.33A5.38 5.38 0 0 0 18.541 1H5.459A5.38 5.38 0 0 0 .153 5.024 5.26 5.26 0 0 0 2 10.354v7.152A5.5 5.5 0 0 0 7.5 23h9a5.5 5.5 0 0 0 5.5-5.494M18.541 4a2.42 2.42 0 0 1 2.392 1.733 2.35 2.35 0 0 1-1.188 2.543A1.5 1.5 0 0 0 19 9.573v7.933A2.5 2.5 0 0 1 16.5 20h-9A2.5 2.5 0 0 1 5 17.506V9.573a1.5 1.5 0 0 0-.745-1.3 2.35 2.35 0 0 1-1.188-2.539A2.42 2.42 0 0 1 5.459 4z"/></svg>
        </Host>
    );
  }
}
