/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-arrow-up',
   styleUrl: './crai-icon-arrow-up.css',
   shadow: true,
   })
export class CraiIconArrowUp {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.427 4.91 14.508.993a3.583 3.583 0 0 0-4.95 0L5.639 4.911A1.5 1.5 0 0 0 7.76 7.03l2.78-2.779.023 18.25a1.5 1.5 0 1 0 3 0L13.54 4.266l2.766 2.766a1.498 1.498 0 0 0 2.467-.474 1.5 1.5 0 0 0-.346-1.647"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
