/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-map-marker-minus',
   styleUrl: './crai-icon-map-marker-minus.css',
   shadow: true,
   })
export class CraiIconMapMarkerMinus {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M8 22.36a5.706 5.706 0 0 0 7.976.03l3.808-3.537a11.093 11.093 0 0 0 0-15.615 10.967 10.967 0 0 0-15.56 0 11.1 11.1 0 0 0 .041 15.656zM6.346 5.354a7.967 7.967 0 0 1 11.308 0A8.074 8.074 0 0 1 17.7 16.7l-3.8 3.525a2.754 2.754 0 0 1-3.832-.03l-3.722-3.458a8.084 8.084 0 0 1 0-11.383M7 11a1.5 1.5 0 0 1 1.5-1.5h7a1.5 1.5 0 0 1 0 3h-7A1.5 1.5 0 0 1 7 11"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
