/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-home',
   styleUrl: './crai-icon-home.css',
   shadow: true,
   })
export class CraiIconHome {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.975 8.695 15.889 1.61a5.507 5.507 0 0 0-7.778 0L1.025 8.695A3.48 3.48 0 0 0 0 11.17v10.378a2.457 2.457 0 0 0 2.455 2.453h19.09A2.457 2.457 0 0 0 24 21.548V11.17a3.48 3.48 0 0 0-1.025-2.475M21 21.001h-5V17.82a3.82 3.82 0 0 0-3.818-3.818h-.364A3.82 3.82 0 0 0 8 17.82v3.182H3v-9.83c0-.133.052-.26.146-.355l7.086-7.086a2.5 2.5 0 0 1 3.535 0l7.087 7.086a.5.5 0 0 1 .146.354z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
