/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-at',
   styleUrl: './crai-icon-at.css',
   shadow: true,
   })
export class CraiIconAt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0A12.013 12.013 0 0 0 0 12c-.125 9.574 11.159 15.429 18.9 9.817a1.5 1.5 0 1 0-1.727-2.453C11.42 23.582 2.863 19.146 3 12 3.472.07 20.529.072 21 12v1.5a1.5 1.5 0 1 1-3 0V12c-.252-7.929-11.749-7.928-12 0a6.017 6.017 0 0 0 10.078 4.388A4.5 4.5 0 0 0 24 13.5V12A12.013 12.013 0 0 0 12 0m0 15a3 3 0 1 1 0-6 3 3 0 0 1 0 6"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
