/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-info',
   styleUrl: './crai-icon-info.css',
   shadow: true,
   })
export class CraiIconInfo {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0a12 12 0 1 0 12 12A12.013 12.013 0 0 0 12 0m0 21a9 9 0 1 1 9-9 9.01 9.01 0 0 1-9 9"/><path d="M11.545 9.545h-.3a1.577 1.577 0 0 0-1.605 1.393A1.5 1.5 0 0 0 11 12.532v4.65a1.5 1.5 0 1 0 3 0V12a2.455 2.455 0 0 0-2.455-2.455m.285-1.079a1.716 1.716 0 1 0 0-3.432 1.716 1.716 0 0 0 0 3.432"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
