/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-smile',
   styleUrl: './crai-icon-smile.css',
   shadow: true,
   })
export class CraiIconSmile {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M8.5 7A2.587 2.587 0 0 1 11 9.667C11 11 9.881 11 8.5 11S6 11 6 9.667A2.587 2.587 0 0 1 8.5 7M13 9.667C13 11 14.119 11 15.5 11S18 11 18 9.667A2.587 2.587 0 0 0 15.5 7 2.587 2.587 0 0 0 13 9.667M24 12a12 12 0 1 0-12 12 12.013 12.013 0 0 0 12-12m-3 0a9 9 0 1 1-9-9 9.01 9.01 0 0 1 9 9m-3.443 3.564a1.5 1.5 0 0 0-2.109-2.133A5.8 5.8 0 0 1 12 15a5.8 5.8 0 0 1-3.443-1.564 1.5 1.5 0 0 0-2.114 2.128A8.8 8.8 0 0 0 12 18a8.8 8.8 0 0 0 5.557-2.436"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
