/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-poker-chip',
   styleUrl: './crai-icon-poker-chip.css',
   shadow: true,
   })
export class CraiIconPokerChip {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0a12 12 0 1 0 12 12A12.013 12.013 0 0 0 12 0m8.617 9.415-2.871.861a6 6 0 0 0-4.022-4.022l.861-2.871a9.03 9.03 0 0 1 6.032 6.032m-7.879 6.216a.922.922 0 0 1-1.476 0l-1.893-2.523a1.85 1.85 0 0 1 0-2.216l1.893-2.523a.922.922 0 0 1 1.476 0l1.893 2.523a1.85 1.85 0 0 1 0 2.216zM9.415 3.383l.861 2.871a6 6 0 0 0-4.022 4.022l-2.871-.861a9.03 9.03 0 0 1 6.032-6.032m-6.032 11.2 2.871-.861a6.01 6.01 0 0 0 4.022 4.022l-.861 2.871a9.03 9.03 0 0 1-6.032-6.03zm11.2 6.032-.861-2.871a6.01 6.01 0 0 0 4.022-4.022l2.871.861a9.03 9.03 0 0 1-6.03 6.034z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
