/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-interrogation',
   styleUrl: './crai-icon-interrogation.css',
   shadow: true,
   })
export class CraiIconInterrogation {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0a12 12 0 1 0 12 12A12.013 12.013 0 0 0 12 0m0 21a9 9 0 1 1 9-9 9.01 9.01 0 0 1-9 9"/><path d="M12.005 19a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m.752-14.013a4.25 4.25 0 0 0-5 4.18 1.5 1.5 0 0 0 3 0 1.248 1.248 0 1 1 1.847 1.1 3.32 3.32 0 0 0-2.038 3.159 1.5 1.5 0 1 0 3 0q0-.11.016-.218c.14-.128.3-.234.471-.313a4.248 4.248 0 0 0-1.292-7.9z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
