/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-password',
   styleUrl: './crai-icon-password.css',
   shadow: true,
   })
export class CraiIconPassword {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M16 16.5a1.5 1.5 0 0 1-1.5 1.5h-5a1.5 1.5 0 1 1 0-3h5a1.5 1.5 0 0 1 1.5 1.5m-7.061-3.939a1.5 1.5 0 0 0 2.122 0l.939-.94.939.94a1.5 1.5 0 1 0 2.122-2.122l-.94-.939.94-.939a1.5 1.5 0 1 0-2.122-2.122L12 7.38l-.939-.94a1.5 1.5 0 0 0-2.122 2.122l.94.94-.94.938a1.5 1.5 0 0 0 0 2.122M5.5 15.001h-4a1.5 1.5 0 0 0 0 3h4a1.5 1.5 0 1 0 0-3m1.061-8.562a1.5 1.5 0 0 0-2.122 0l-.939.94-.939-.94A1.5 1.5 0 0 0 .439 8.561l.94.94-.94.938a1.5 1.5 0 0 0 2.122 2.122l.939-.94.939.94a1.5 1.5 0 1 0 2.122-2.122l-.94-.939.94-.939a1.5 1.5 0 0 0 0-2.122M22.5 15h-4a1.5 1.5 0 0 0 0 3h4a1.5 1.5 0 0 0 0-3m.121-5.5.94-.939a1.503 1.503 0 0 0 0-2.122 1.5 1.5 0 0 0-2.122 0l-.939.94-.939-.94a1.5 1.5 0 0 0-2.122 2.122l.94.94-.94.938a1.5 1.5 0 0 0 2.122 2.122l.939-.94.939.94a1.5 1.5 0 1 0 2.122-2.122z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
