/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-sticker',
   styleUrl: './crai-icon-sticker.css',
   shadow: true,
   })
export class CraiIconSticker {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.964 10.417a12.036 12.036 0 1 0-13.548 13.547q.268.036.538.036a4.37 4.37 0 0 0 3.066-1.29l8.689-8.69a4.33 4.33 0 0 0 1.255-3.603M3.057 11a9.042 9.042 0 0 1 17.505-1.978 12 12 0 0 0-11.54 11.539A9 9 0 0 1 3.057 11m8.97 9.457a9 9 0 0 1 8.432-8.431z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
