/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-syringe',
   styleUrl: './crai-icon-syringe.css',
   shadow: true,
   })
export class CraiIconSyringe {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m23.561 4.439-4-4A1.502 1.502 0 0 0 17 1.499c0 .398.158.78.439 1.062l.94.938-1.339 1.34a5.46 5.46 0 0 0-6.778.77L5.18 10.683a7.45 7.45 0 0 0-2.195 5.3v2.9l-2.548 2.56a1.5 1.5 0 1 0 2.126 2.116L5.109 21H8a7.44 7.44 0 0 0 5.3-2.2l5.082-5.074a5.5 5.5 0 0 0 .781-6.767L20.5 5.622l.939.94a1.5 1.5 0 1 0 2.122-2.122m-7.306 7.17-5.082 5.074A4.47 4.47 0 0 1 8 18H5.985v-2.015a4.5 4.5 0 0 1 .3-1.582l1.157 1.157a1.5 1.5 0 0 0 2.122-2.122l-1.45-1.447 1.88-1.876 1.445 1.445a1.5 1.5 0 1 0 2.122-2.122L12.117 8l.265-.264a2.555 2.555 0 0 1 3.529 0l.343.343a2.5 2.5 0 0 1 .001 3.532"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
