/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-tree-christmas',
   styleUrl: './crai-icon-tree-christmas.css',
   shadow: true,
   })
export class CraiIconTreeChristmas {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M3.448 20.071a3.66 3.66 0 0 0 3.22 1.93H10.5v.5a1.5 1.5 0 1 0 3 0V22h3.832a3.66 3.66 0 0 0 3.22-1.93 3.71 3.71 0 0 0-.166-3.8l-1.125-1.71q.26-.267.435-.594a2.66 2.66 0 0 0-.118-2.727l-1.731-2.634q.119-.155.211-.326a2.66 2.66 0 0 0-.087-2.71 2 2 0 0 0-.12-.163L14.052.915C14.028.888 14 .861 13.979.836a2.826 2.826 0 0 0-3.958 0 1 1 0 0 0-.07.076L6.135 5.4a2 2 0 0 0-.119.161 2.66 2.66 0 0 0 .129 3.057l-1.723 2.62a2.66 2.66 0 0 0 .313 3.32l-1.125 1.71a3.71 3.71 0 0 0-.162 3.803m2.672-2.156 2.131-3.24a1.5 1.5 0 0 0-.987-2.3l2.236-3.4A1.506 1.506 0 0 0 8.885 6.8L12 3.135 15.1 6.8a1.5 1.5 0 0 0-.6 2.175l2.237 3.4a1.5 1.5 0 0 0-.987 2.3l2.132 3.24a.7.7 0 0 1 .031.732.64.64 0 0 1-.579.354H6.668a.64.64 0 0 1-.579-.354.7.7 0 0 1 .031-.732"/><path d="M11.5 17a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m1-5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
