/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-envelope-marker',
   styleUrl: './crai-icon-envelope-marker.css',
   shadow: true,
   })
export class CraiIconEnvelopeMarker {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 16.5v2a5.506 5.506 0 0 1-5.5 5.5h-13A5.506 5.506 0 0 1 0 18.5v-10A5.506 5.506 0 0 1 5.5 3h6a1.5 1.5 0 0 1 0 3h-6a2.49 2.49 0 0 0-2.2 1.336l6.931 6.932a2.555 2.555 0 0 0 3.017.4 1.501 1.501 0 0 1 1.5 2.6 5.52 5.52 0 0 1-6.64-.874L3 11.278V18.5A2.5 2.5 0 0 0 5.5 21h13a2.5 2.5 0 0 0 2.5-2.5v-2a1.5 1.5 0 1 1 3 0M22 0h-5a2 2 0 0 0-2 2v9.654a1.35 1.35 0 0 0 2.193 1.054l2.307-1.845 2.307 1.845A1.35 1.35 0 0 0 24 11.654V2a2 2 0 0 0-2-2"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
