/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-wifi-alt',
   styleUrl: './crai-icon-wifi-alt.css',
   shadow: true,
   })
export class CraiIconWifiAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.511 16.463a1.5 1.5 0 0 1-1.061-.439 7.007 7.007 0 0 0-9.9 0A1.501 1.501 0 1 1 9.429 13.9a10.01 10.01 0 0 1 14.142 0 1.5 1.5 0 0 1-1.06 2.56zm-2.476 3.1a1.5 1.5 0 0 0 0-2.122 5 5 0 0 0-7.07 0 1.5 1.5 0 0 0 2.121 2.122 2.05 2.05 0 0 1 2.828 0 1.5 1.5 0 0 0 2.121 0M16.5 21a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m-6-.5A1.5 1.5 0 0 0 9 19H5.968a2.925 2.925 0 0 1-2.875-2.038 2.76 2.76 0 0 1 1.444-3.156 2.484 2.484 0 0 0 1.012-3.356 5.12 5.12 0 0 1-.456-3.3 5.05 5.05 0 0 1 4.215-4.093 5.2 5.2 0 0 1 3.909.988 5.12 5.12 0 0 1 2 3.42 1.5 1.5 0 0 0 1.289 1.287c.787.103 1.54.386 2.2.828a1.502 1.502 0 1 0 1.664-2.5A8.3 8.3 0 0 0 17.977 6a8.1 8.1 0 0 0-2.951-4.343A8.2 8.2 0 0 0 8.882.086a8.05 8.05 0 0 0-6.736 6.5 8.1 8.1 0 0 0 .541 4.825 5.76 5.76 0 0 0-2.5 6.3A5.886 5.886 0 0 0 5.968 22H9a1.5 1.5 0 0 0 1.5-1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
