/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-shopping-bag-add',
   styleUrl: './crai-icon-shopping-bag-add.css',
   shadow: true,
   })
export class CraiIconShoppingBagAdd {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 18H21v-1.5a1.5 1.5 0 1 0-3 0V18h-1.5a1.5 1.5 0 1 0 0 3H18v1.5a1.5 1.5 0 1 0 3 0V21h1.5a1.5 1.5 0 1 0 0-3"/><path d="M20.5 6H18A6 6 0 1 0 6 6H3.5A3.543 3.543 0 0 0 0 9.5v9A5.55 5.55 0 0 0 5.5 24h6a1.5 1.5 0 1 0 0-3h-6A2.476 2.476 0 0 1 3 18.5v-9a.472.472 0 0 1 .5-.5H6v1.5A1.54 1.54 0 0 0 7.5 12 1.54 1.54 0 0 0 9 10.5V9h6v1.5a1.5 1.5 0 1 0 3 0V9h2.5a.472.472 0 0 1 .5.5v2a1.5 1.5 0 1 0 3 0v-2A3.543 3.543 0 0 0 20.5 6M9 6a3 3 0 1 1 6 0z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
