/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-brush',
   styleUrl: './crai-icon-brush.css',
   shadow: true,
   })
export class CraiIconBrush {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 0h-13A5.507 5.507 0 0 0 0 5.5v5A7.51 7.51 0 0 0 7.5 18H8v2a4 4 0 1 0 8 0v-2h.5a7.51 7.51 0 0 0 7.5-7.5v-5A5.507 5.507 0 0 0 18.5 0m-13 3H6v.5a1.5 1.5 0 0 0 3 0V3h2v2.5a1.5 1.5 0 1 0 3 0V3h2v4.5a1.5 1.5 0 1 0 3 0V3.051A2.5 2.5 0 0 1 21 5.5V10H3V5.5A2.5 2.5 0 0 1 5.5 3m11 12h-2a1.5 1.5 0 0 0-1.5 1.5V20a1 1 0 0 1-2 0v-3.5A1.5 1.5 0 0 0 9.5 15h-2a4.5 4.5 0 0 1-3.738-2h16.476a4.5 4.5 0 0 1-3.738 2"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
