/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-broom',
   styleUrl: './crai-icon-broom.css',
   shadow: true,
   })
export class CraiIconBroom {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.56 1.12a1.5 1.5 0 0 0-2.12 0l-4.763 4.763a5.51 5.51 0 0 0-6.874-.39 15.2 15.2 0 0 1-4.06 2.154l-1.789.523A5.498 5.498 0 0 0 .46 15.643 12.5 12.5 0 0 0 6.1 21.96a14.35 14.35 0 0 0 6.454 1.355h.063c.75 0 1.48-.243 2.081-.694a15.02 15.02 0 0 0 6.008-9.466 5.55 5.55 0 0 0-1.577-4.91l-.288-.28 4.723-4.725a1.5 1.5 0 0 0-.003-2.119M12.884 20.23a.46.46 0 0 1-.283.085c-1.05 0-2.099-.107-3.128-.319a11.6 11.6 0 0 0 3.387-3.24l.494-.727a1.5 1.5 0 1 0-2.479-1.686l-.494.725a8.6 8.6 0 0 1-3.222 2.816l-1.038.52a9 9 0 0 1-1.553-1.617 11.6 11.6 0 0 0 3.724-2.44 1.5 1.5 0 0 0-2.1-2.14 8.6 8.6 0 0 1-3.084 1.924 2.48 2.48 0 0 1 1.677-3.078l.015-.004 1.786-.525a17.2 17.2 0 0 0 4.322-2.157l6.326 6.166a12.54 12.54 0 0 1-4.35 5.697"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
