/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-envelope-open',
   styleUrl: './crai-icon-envelope-open.css',
   shadow: true,
   })
export class CraiIconEnvelopeOpen {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m22.306 7.827-6.545-6.27a5.32 5.32 0 0 0-7.5-.02l-6.567 6.29A5.53 5.53 0 0 0 0 11.8v6.7A5.506 5.506 0 0 0 5.5 24h13a5.506 5.506 0 0 0 5.5-5.5v-6.7a5.53 5.53 0 0 0-1.694-3.973M10.36 3.68a2.33 2.33 0 0 1 3.3.021l5.382 5.156-5.276 5.411a2.56 2.56 0 0 1-3.536 0L4.887 8.923zM21 18.5a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 18.5v-6.7q0-.239.049-.473l5.062 5.063a5.524 5.524 0 0 0 7.791-.013l5.024-5.15q.07.282.074.573z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
