/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-flip-horizontal',
   styleUrl: './crai-icon-flip-horizontal.css',
   shadow: true,
   })
export class CraiIconFlipHorizontal {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M9.494 24H5.507a5.5 5.5 0 0 1-4.819-8.148l7.49-13.77a1.5 1.5 0 1 1 2.633 1.434L3.32 17.29A2.5 2.5 0 0 0 5.507 21h3.987a1.5 1.5 0 0 1 0 3m13.821-8.143-7.51-13.775a1.5 1.5 0 0 0-2.034-.6 1.69 1.69 0 0 0-.793 1.523V22.5a1.5 1.5 0 0 0 1.5 1.5h4.016a5.5 5.5 0 0 0 4.821-8.143"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
