/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-square-root',
   styleUrl: './crai-icon-square-root.css',
   shadow: true,
   })
export class CraiIconSquareRoot {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M15.99 5a2.51 2.51 0 0 0-2.4 1.794l-4.012 13.63A2.175 2.175 0 0 1 7.5 22.002a2.25 2.25 0 0 1-2.091-1.488l-2.31-6.7a2.94 2.94 0 0 0-1.952-1.85 1.5 1.5 0 1 1 .706-2.916 5.94 5.94 0 0 1 4.074 3.765l1.49 4.33 3.3-11.191A5.53 5.53 0 0 1 15.992 2H22.5a1.5 1.5 0 0 1 0 3zm7.41 6.3a1.5 1.5 0 0 0-2.1.3L19.5 14l-1.8-2.4a1.5 1.5 0 1 0-2.4 1.8l2.325 3.1-2.325 3.1a1.5 1.5 0 1 0 2.4 1.8l1.8-2.4 1.8 2.4a1.5 1.5 0 1 0 2.4-1.8l-2.325-3.1 2.325-3.1a1.5 1.5 0 0 0-.3-2.1"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
