/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-ice-skate',
   styleUrl: './crai-icon-ice-skate.css',
   shadow: true,
   })
export class CraiIconIceSkate {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 18a1.5 1.5 0 0 0-1.5 1.5 1.5 1.5 0 0 1-1.5 1.5h-3v-3h1.119a4.406 4.406 0 0 0 4.4-4.4 6.5 6.5 0 0 0-5.186-6.365L13.4 6.45a1.54 1.54 0 0 1-1.208-1.363l-.4-2.082A3.5 3.5 0 0 0 7.567.083c-.044.01-4.294 1.355-4.294 1.355A4.52 4.52 0 0 0 0 5.77v7.73A4.505 4.505 0 0 0 4.5 18v3h-3a1.5 1.5 0 1 0 0 3h18a4.505 4.505 0 0 0 4.5-4.5 1.5 1.5 0 0 0-1.5-1.5M3 13.5V5.77a1.52 1.52 0 0 1 1.136-1.458l4.125-1.307a.47.47 0 0 1 .349.085.56.56 0 0 1 .223.411l.289 1.493L7.494 5A1.5 1.5 0 0 0 7.5 8h.006l2.847-.01q.098.104.2.2L9.382 9.5a1.5 1.5 0 1 0 2.236 2l1.769-1.977 2.819.644A3.51 3.51 0 0 1 19.02 13.6a1.4 1.4 0 0 1-1.4 1.4H4.5A1.5 1.5 0 0 1 3 13.5M7.5 18h6v3h-6z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
