/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-train',
   styleUrl: './crai-icon-train.css',
   shadow: true,
   })
export class CraiIconTrain {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M13.5 17a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m7.38 4.909a1.5 1.5 0 0 1-2.759 1.182l-.879-2.051A13.7 13.7 0 0 1 12 22a13.7 13.7 0 0 1-5.242-.96l-.879 2.051a1.5 1.5 0 1 1-2.758-1.182l1.108-2.584A5.34 5.34 0 0 1 3 15.918V5.984A5.28 5.28 0 0 1 6.644.937 17.5 17.5 0 0 1 12 0c1.823.032 3.63.348 5.356.937A5.28 5.28 0 0 1 21 5.984v9.934c0 1.244-.434 2.45-1.228 3.408zM6 6.25C6 8.2 8.118 12 12 12s6-3.8 6-5.75v-.266a2.29 2.29 0 0 0-1.568-2.194 19 19 0 0 0-1.022-.295A1.5 1.5 0 0 1 14 4.5h-4a1.49 1.49 0 0 1-1.409-1c-.338.089-.678.183-1.023.295A2.29 2.29 0 0 0 6 5.984zM12 19a9.96 9.96 0 0 0 4.868-1.083 2.27 2.27 0 0 0 1.132-2V12.6a8.69 8.69 0 0 1-12 0v3.321a2.27 2.27 0 0 0 1.134 2A9.96 9.96 0 0 0 12 19"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
