/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cake-birthday',
   styleUrl: './crai-icon-cake-birthday.css',
   shadow: true,
   })
export class CraiIconCakeBirthday {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 21H22v-6.682A5.324 5.324 0 0 0 16.682 9H13.5V6.333A2.99 2.99 0 0 0 15 3.75 5.7 5.7 0 0 0 13.555.69a2.167 2.167 0 0 0-3.109 0A5.73 5.73 0 0 0 9 3.75a2.99 2.99 0 0 0 1.5 2.583V9H7.318A5.324 5.324 0 0 0 2 14.318V21h-.5a1.5 1.5 0 1 0 0 3h21a1.5 1.5 0 1 0 0-3M5 16.74a2.34 2.34 0 0 0 1.75-1.876A2.5 2.5 0 0 0 9.375 17 2.49 2.49 0 0 0 12 14.864 2.5 2.5 0 0 0 14.625 17a2.49 2.49 0 0 0 2.625-2.136A2.35 2.35 0 0 0 19 16.738V21H5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
