/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-copyright',
   styleUrl: './crai-icon-copyright.css',
   shadow: true,
   })
export class CraiIconCopyright {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12C23.993 5.376 18.625.007 12 0m0 21a9 9 0 1 1 9-9 9.01 9.01 0 0 1-9 9"/><path d="M14.6 9.333a1.5 1.5 0 1 0 2.121-2.122 6.769 6.769 0 1 0 0 9.578 1.5 1.5 0 1 0-2.12-2.122 3.772 3.772 0 1 1 0-5.334"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
