/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-utensils',
   styleUrl: './crai-icon-utensils.css',
   shadow: true,
   })
export class CraiIconUtensils {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.327.758a2.69 2.69 0 0 0-2.9-.55A2.4 2.4 0 0 0 16 2.449V22.5a1.5 1.5 0 1 0 3 0v-2.483c6.114-4.633 6.64-14.162 1.327-19.259M19 15.744v-12c2.491 2.892 2.712 8.978 0 12M13 1.5v6a6.506 6.506 0 0 1-5 6.318V22.5a1.5 1.5 0 0 1-3 0v-8.682A6.506 6.506 0 0 1 0 7.5v-6a1.5 1.5 0 0 1 3 0v6a3.5 3.5 0 0 0 2 3.149V1.5a1.5 1.5 0 0 1 3 0v9.149A3.5 3.5 0 0 0 10 7.5v-6a1.5 1.5 0 1 1 3 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
