/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cow',
   styleUrl: './crai-icon-cow.css',
   shadow: true,
   })
export class CraiIconCow {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.868 5.312A2.502 2.502 0 0 0 21.5 2h-2.55A1.512 1.512 0 1 0 16 1.5a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5 1.512 1.512 0 1 0-2.949.5h-2.55a2.5 2.5 0 0 0-2.37 3.312 8.7 8.7 0 0 0 1.66 3.077l3.24 13.417A2.49 2.49 0 0 0 7.5 24h9a2.49 2.49 0 0 0 2.47-2.194L22.207 8.39a8.7 8.7 0 0 0 1.66-3.077M16.56 19.006 13.5 19v-4.5a4.45 4.45 0 0 1 1.047-2.85 1.5 1.5 0 0 0 2.4-1.514A4.5 4.5 0 0 1 18 10s.656-.01.736-.013zm-9.118 0L5.264 9.987C5.344 9.99 6 10 6 10q.532.006 1.05.136a1.5 1.5 0 0 0 2.4 1.514 4.46 4.46 0 0 1 1.05 2.85V19zM16.534 5c.86.584 1.67 1.238 2.421 1.956C18.808 6.983 18 7 18 7a7.5 7.5 0 0 0-6 3.005A7.5 7.5 0 0 0 6 7s-.808-.017-.955-.044A19 19 0 0 1 7.466 5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
