/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-mars-double',
   styleUrl: './crai-icon-mars-double.css',
   shadow: true,
   })
export class CraiIconMarsDouble {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.99 8a1 1 0 0 0-1-1h-4.569a1 1 0 0 0-.707 1.707l1.229 1.229-2.038 2.038A6.45 6.45 0 0 0 13.5 11c-.181 0-.359.013-.536.028.015-.176.036-.349.036-.528a6.45 6.45 0 0 0-.974-3.4l2.038-2.038 1.229 1.229A1 1 0 0 0 17 5.577L16.99 1a1 1 0 0 0-1-1h-4.569a1 1 0 0 0-.707 1.707l1.229 1.229L9.9 4.974A6.5 6.5 0 1 0 6.5 17c.183 0 .36-.022.54-.037-.015.179-.04.355-.04.537a6.5 6.5 0 1 0 12.026-3.4l2.038-2.038 1.229 1.229A1 1 0 0 0 24 12.577zM3 10.5a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0M13.5 21a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
