/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-bike',
   styleUrl: './crai-icon-bike.css',
   shadow: true,
   })
export class CraiIconBike {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.328 12.2a29 29 0 0 0-1.09-2.877A13.3 13.3 0 0 1 18 5.5a.5.5 0 0 1 1 0 1.5 1.5 0 0 0 3 0 3.49 3.49 0 0 0-6.97-.3q-.03.15-.03.3c.017.648.123 1.291.314 1.911L11.6 10.3 7.1 7h1.4a1.5 1.5 0 1 0 0-3H5.47a2.469 2.469 0 0 0-1.457 4.462l5.126 3.752-1.093.85A4.95 4.95 0 0 0 5 12a5 5 0 1 0 5 5 5 5 0 0 0-.245-1.466l6.66-5.18s.587 1.4.8 1.989a5.012 5.012 0 1 0 3.112-.141zM5 19a2 2 0 1 1 0-4 2 2 0 0 1 0 4m14 0a2 2 0 1 1 0-4 2 2 0 0 1 0 4"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
