/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-circle-small',
   styleUrl: './crai-icon-circle-small.css',
   shadow: true,
   })
export class CraiIconCircleSmall {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M12 4.5a7.5 7.5 0 1 0 7.5 7.5A7.51 7.51 0 0 0 12 4.5m0 12a4.5 4.5 0 1 1 0-9 4.5 4.5 0 0 1 0 9"/></svg>
        </Host>
    );
  }
}
