/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-search-alt',
   styleUrl: './crai-icon-search-alt.css',
   shadow: true,
   })
export class CraiIconSearchAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M15.5 6a1.5 1.5 0 0 1 0 3h-7a1.5 1.5 0 1 1 0-3zm8.06 17.561a1.5 1.5 0 0 1-2.121 0l-2.011-2.012c-.6.293-1.26.448-1.928.451a4.5 4.5 0 1 1 4.5-4.5 4.44 4.44 0 0 1-.451 1.928l2.012 2.011a1.5 1.5 0 0 1 0 2.122M17.5 19a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m-6 2h-4A2.5 2.5 0 0 1 5 18.5v-13A2.5 2.5 0 0 1 7.5 3h11a.5.5 0 0 1 .5.5v7a1.5 1.5 0 1 0 3 0v-7A3.5 3.5 0 0 0 18.5 0h-11A5.506 5.506 0 0 0 2 5.5v13A5.506 5.506 0 0 0 7.5 24h4a1.5 1.5 0 1 0 0-3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
