/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-thumbs-up',
   styleUrl: './crai-icon-thumbs-up.css',
   shadow: true,
   })
export class CraiIconThumbsUp {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M22.752 8.01a5.46 5.46 0 0 0-4.257-2.03h-2.03l.09-.526A3.936 3.936 0 0 0 12.622.856 3.97 3.97 0 0 0 9.06 3.028L7.553 5.98H5.48A5.485 5.485 0 0 0 0 11.46v4.98a5.485 5.485 0 0 0 5.48 5.48h11.962a5.504 5.504 0 0 0 5.361-4.345l1.053-4.981a5.46 5.46 0 0 0-1.104-4.585M2.99 16.44v-4.98a2.49 2.49 0 0 1 2.49-2.491h1.495v9.962H5.479a2.49 2.49 0 0 1-2.49-2.49m17.943-4.465-1.054 4.981a2.5 2.5 0 0 1-2.436 1.975h-7.48V7.834l1.76-3.448c.186-.35.557-.56.952-.541a.95.95 0 0 1 .935 1.107l-.685 4.017h5.571a2.49 2.49 0 0 1 2.437 3.006"/></svg>
        </Host>
    );
  }
}
