/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-dollar',
   styleUrl: './crai-icon-dollar.css',
   shadow: true,
   })
export class CraiIconDollar {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M18.5 9.5A1.5 1.5 0 0 0 20 8v-.687A5.32 5.32 0 0 0 14.687 2H13.5v-.5a1.5 1.5 0 0 0-3 0V2H9.313a5.313 5.313 0 0 0-1.54 10.4l2.727.746V19H9.313A2.316 2.316 0 0 1 7 16.687V16a1.5 1.5 0 0 0-3 0v.687A5.32 5.32 0 0 0 9.313 22H10.5v.5a1.5 1.5 0 1 0 3 0V22h1.187a5.313 5.313 0 0 0 1.541-10.4l-2.728-.744V5h1.187A2.316 2.316 0 0 1 17 7.313V8a1.5 1.5 0 0 0 1.5 1.5m-3.118 4.979a2.314 2.314 0 0 1-.7 4.521H13.5v-5.035zM10.5 10.035l-1.882-.514A2.314 2.314 0 0 1 9.313 5H10.5z"/></svg>
        </Host>
    );
  }
}
