/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-shuffle',
   styleUrl: './crai-icon-shuffle.css',
   shadow: true,
   })
export class CraiIconShuffle {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M18.414 7.9v1.686a1 1 0 0 0 1.707.707l3.586-3.586a1 1 0 0 0 0-1.414L20.12 1.707a1 1 0 0 0-1.707.707v2.4c-3.35.732-5.6 2.781-7.51 4.911C8.718 7.316 6.08 5.021 1.83 4.586a5 5 0 0 0-.33-.039 1.5 1.5 0 0 0-.131 2.994c3.464.3 5.5 2.159 7.549 4.458-2.046 2.3-4.087 4.166-7.552 4.462a1.5 1.5 0 0 0 .134 2.992c.038 0 .073 0 .11-.008C6.84 19 9.65 15.753 12.149 12.86c1.91-2.21 3.644-4.16 6.266-4.96"/><path d="M20.121 13.707a1 1 0 0 0-1.707.707v1.7a9.2 9.2 0 0 1-3.452-2 1.466 1.466 0 0 0-2.062.157l-.025.028a1.49 1.49 0 0 0 .165 2.111 12 12 0 0 0 5.374 2.79v2.391a1 1 0 0 0 1.707.707l3.586-3.586a1 1 0 0 0 0-1.414z"/></svg>
        </Host>
    );
  }
}
