/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-fingerprint',
   styleUrl: './crai-icon-fingerprint.css',
   shadow: true,
   })
export class CraiIconFingerprint {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M8.5 22.437a1.5 1.5 0 0 1-.88-2.715c2.512-1.82 2.865-5.181 2.878-8.23A1.5 1.5 0 0 1 12 10h.006a1.503 1.503 0 0 1 1.494 1.507c-.01 2.3-.033 7.686-4.12 10.644a1.5 1.5 0 0 1-.88.286m6.028.994a14 14 0 0 0 1.985-3.331 1.5 1.5 0 0 0-2.762-1.174c-.392.94-.915 1.82-1.55 2.616a1.5 1.5 0 1 0 2.33 1.889zm3.408-9.838C18 12.572 18 11.663 18 11a6 6 0 0 0-8-5.658 1.5 1.5 0 1 0 1 2.828A3 3 0 0 1 15 11c0 .659 0 1.479-.058 2.407A1.5 1.5 0 0 0 16.347 15h.093a1.5 1.5 0 0 0 1.497-1.407M4.691 18.956a4.75 4.75 0 0 0 1.846-.618C8.978 16.873 8.99 13.77 9 11.506A1.5 1.5 0 0 0 7.505 10H7.5A1.5 1.5 0 0 0 6 11.494c-.009 2.385-.172 3.772-1 4.27-.212.118-.445.19-.686.217a1.5 1.5 0 0 0 .377 2.975m16.028 4.172A28.7 28.7 0 0 0 23 11a11 11 0 0 0-.774-4.054 1.5 1.5 0 0 0-2.788 1.108A7.9 7.9 0 0 1 20 11a25.9 25.9 0 0 1-2.006 10.872 1.5 1.5 0 1 0 2.725 1.256M4 12.5V11a8 8 0 0 1 11.787-7.046 1.5 1.5 0 0 0 1.426-2.64A11 11 0 0 0 1 11v1.5a1.5 1.5 0 0 0 3 0"/></svg>
        </Host>
    );
  }
}
