/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-resources',
   styleUrl: './crai-icon-resources.css',
   shadow: true,
   })
export class CraiIconResources {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21.5 2h-8A2.5 2.5 0 0 0 11 4.5v.3L9.735 2.608A2.54 2.54 0 0 0 8.213 1.38a2.5 2.5 0 0 0-2.846 1.163L.375 11.188a2.54 2.54 0 0 0-.3 1.93A2.5 2.5 0 0 0 2.5 15.002h2.7a7.074 7.074 0 1 0 13.6 0h2.7a2.5 2.5 0 0 0 2.5-2.5v-8A2.5 2.5 0 0 0 21.5 2M3.37 12l4.162-7.208L10.542 10a7.05 7.05 0 0 0-3.613 2zM12 21a4.074 4.074 0 1 1 0-8.148 4.074 4.074 0 0 1 0 8.149m9-9h-3.93A7.5 7.5 0 0 0 14 10.14V5h7z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
