/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-earnings',
   styleUrl: './crai-icon-earnings.css',
   shadow: true,
   })
export class CraiIconEarnings {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 0H13a1.5 1.5 0 0 0 0 3h5.5q.173.005.344.035l-18.4 18.4a1.5 1.5 0 1 0 2.122 2.122l18.4-18.4q.029.17.034.343V11a1.5 1.5 0 1 0 3 0V5.5A5.507 5.507 0 0 0 18.5 0"/><path d="M6.5 11a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9m0-6a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3m11 8a4.5 4.5 0 1 0 0 9 4.5 4.5 0 0 0 0-9m0 6a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
