/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-fish',
   styleUrl: './crai-icon-fish.css',
   shadow: true,
   })
export class CraiIconFish {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.654 5.25a4.53 4.53 0 0 0-3.083-1.82 4.53 4.53 0 0 0-1.82-3.084 1.718 1.718 0 0 0-2.75 1.37V7h-.5a25.6 25.6 0 0 0-4.5.38V7.2a2.178 2.178 0 0 0-2.51-2.169 6.75 6.75 0 0 0-5.483 6.483 13.3 13.3 0 0 0-3 7.9 4.28 4.28 0 0 0 1.257 3.336 3.93 3.93 0 0 0 3 1.247c4.2-.325 8.771-1.923 11.124-7h1.334c2.484.077 3.283-3.876.474-4h-.587c.264-1.484.395-2.99.39-4.497V8h5.285a1.717 1.717 0 0 0 1.37-2.75M4.5 21a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m4.8-1.428a9 9 0 0 0-4.893-4.879c1.682-2.846 4.842-4.384 9.55-4.65-.268 4.685-1.807 7.838-4.657 9.53"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
