/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-billiard',
   styleUrl: './crai-icon-billiard.css',
   shadow: true,
   })
export class CraiIconBilliard {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 6a6 6 0 1 0 0 12 6 6 0 0 0 0-12m2.786 5.271-2 4a1.5 1.5 0 0 1-2.492.122 1.5 1.5 0 0 1-.081-1.665L11 12h-.5a1.5 1.5 0 1 1 0-3h3a1.5 1.5 0 0 1 1.286 2.271M12 24a12 12 0 1 1 12-12 12.013 12.013 0 0 1-12 12m0-21a9 9 0 1 0 9 9 9.01 9.01 0 0 0-9-9"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
