/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-edit-alt',
   styleUrl: './crai-icon-edit-alt.css',
   shadow: true,
   })
export class CraiIconEditAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21 15h-3a3 3 0 0 0-3 3v3H4.5A1.5 1.5 0 0 1 3 19.5v-15A1.5 1.5 0 0 1 4.5 3h10a1.5 1.5 0 0 0 0-3h-10A4.5 4.5 0 0 0 0 4.5v15A4.5 4.5 0 0 0 4.5 24h11.985a4.5 4.5 0 0 0 3.181-1.318l3.016-3.016A4.5 4.5 0 0 0 24 16.485v-4.979a1.5 1.5 0 1 0-3 0z"/><path d="M20.963 1a2.96 2.96 0 0 0-2.113.98l-8.136 9.093a4.98 4.98 0 0 1 4.008 3.356l8.4-8.4a2.947 2.947 0 0 0 0-4.163A3 3 0 0 0 20.962 1M9.288 13.067c-2.317.446-3.465 3.026-3.963 4.634A1 1 0 0 0 6.281 19H10a3 3 0 0 0 2.988-3.274 3.106 3.106 0 0 0-3.7-2.66"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
