/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-list-check',
   styleUrl: './crai-icon-list-check.css',
   shadow: true,
   })
export class CraiIconListCheck {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M4.5 7a3.48 3.48 0 0 1-2.475-1.025L.5 4.62a1.501 1.501 0 0 1 2-2.24l1.584 1.414A.58.58 0 0 0 4.5 4a.5.5 0 0 0 .353-.146L8.466.414a1.5 1.5 0 0 1 2.068 2.172L6.948 6A3.45 3.45 0 0 1 4.5 7M24 3.5A1.5 1.5 0 0 0 22.5 2h-8a1.5 1.5 0 0 0 0 3h8A1.5 1.5 0 0 0 24 3.5M6.948 14l3.586-3.414a1.5 1.5 0 0 0-2.068-2.172l-3.613 3.44a.5.5 0 0 1-.707 0L2.56 10.268A1.5 1.5 0 0 0 .439 12.39l1.586 1.585A3.5 3.5 0 0 0 6.948 14M24 11.5a1.5 1.5 0 0 0-1.5-1.5h-8a1.5 1.5 0 0 0 0 3h8a1.5 1.5 0 0 0 1.5-1.5M6.948 22l3.586-3.414a1.5 1.5 0 0 0-2.068-2.172l-3.613 3.44A.5.5 0 0 1 4.5 20a.58.58 0 0 1-.416-.206L2.5 18.38a1.501 1.501 0 0 0-2 2.24l1.523 1.355A3.5 3.5 0 0 0 6.948 22M24 19.5a1.5 1.5 0 0 0-1.5-1.5h-8a1.5 1.5 0 0 0 0 3h8a1.5 1.5 0 0 0 1.5-1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
