/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-rocket',
   styleUrl: './crai-icon-rocket.css',
   shadow: true,
   })
export class CraiIconRocket {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M15 7.5a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0M13.5 12a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m-3 3a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3M23.841 3.555l-.075.209c-1.654 4.589-3.234 8.925-6.875 12.69a11.06 11.06 0 0 1-3.3 6.788A2.76 2.76 0 0 1 11.7 24 2.7 2.7 0 0 1 9 21.3v-1.63a5.3 5.3 0 0 1-1.607-.941l-1.832 1.833a1.5 1.5 0 1 1-2.122-2.122l1.834-1.834A5.3 5.3 0 0 1 4.128 14H2.7A2.7 2.7 0 0 1 0 11.3a2.76 2.76 0 0 1 .76-1.89 11.3 11.3 0 0 1 7.983-3.392c3.476-2.893 7.386-4.3 11.5-5.784l.208-.075a2.652 2.652 0 0 1 3.394 3.394zm-3.073-.321C16.412 4.806 12.635 6.24 9.4 9.473a26 26 0 0 0-1.921 2.449A2.32 2.32 0 0 0 7.74 14.9l1.424 1.42a2.32 2.32 0 0 0 2.976.258 17.6 17.6 0 0 0 2.388-1.978c3.232-3.235 4.672-7.012 6.24-11.368"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
