/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-checkbox',
   styleUrl: './crai-icon-checkbox.css',
   shadow: true,
   })
export class CraiIconCheckbox {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 24h-13A5.506 5.506 0 0 1 0 18.5v-13A5.506 5.506 0 0 1 5.5 0h13A5.506 5.506 0 0 1 24 5.5v13a5.506 5.506 0 0 1-5.5 5.5M5.5 3A2.5 2.5 0 0 0 3 5.5v13A2.5 2.5 0 0 0 5.5 21h13a2.5 2.5 0 0 0 2.5-2.5v-13A2.5 2.5 0 0 0 18.5 3z"/><path d="M9.667 17.787a2.36 2.36 0 0 1-1.68-.7L5 14.105a1.5 1.5 0 0 1 0-2.121v-.001a1.5 1.5 0 0 1 2.121 0l2.546 2.545 7.212-7.212A1.5 1.5 0 1 1 19 9.438l-7.654 7.654a2.36 2.36 0 0 1-1.679.695"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
