/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-e-learning',
   styleUrl: './crai-icon-e-learning.css',
   shadow: true,
   })
export class CraiIconELearning {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.679 2.63A4.2 4.2 0 0 0 18.328.878a4.3 4.3 0 0 0-3.783-.717l-1.6.448a3.4 3.4 0 0 0-.943.43 3.4 3.4 0 0 0-.942-.43L9.454.161a4.3 4.3 0 0 0-3.782.717A4.2 4.2 0 0 0 4.321 2.63 5.51 5.51 0 0 0 0 8v5.5A5.507 5.507 0 0 0 5.5 19h5v2h-2a1.5 1.5 0 1 0 0 3h7a1.5 1.5 0 1 0 0-3h-2v-2h5a5.507 5.507 0 0 0 5.5-5.5V8a5.51 5.51 0 0 0-4.321-5.37M13.5 3.8a.33.33 0 0 1 .251-.3l1.6-.448a1.31 1.31 0 0 1 1.525.64c.084.166.128.35.128.537v3.578a1.24 1.24 0 0 1-.925 1.176L13.5 9.7zm-6.015-.532a1.31 1.31 0 0 1 1.161-.217l1.6.448a.33.33 0 0 1 .25.3V9.7l-2.572-.717A1.24 1.24 0 0 1 7 7.807V4.228a1.19 1.19 0 0 1 .485-.96M21 13.5a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 13.5V8a2.49 2.49 0 0 1 1-1.988v1.8a4.25 4.25 0 0 0 3.116 4.065l3.2.9a6.25 6.25 0 0 0 3.36 0l3.2-.9A4.25 4.25 0 0 0 20 7.807v-1.8A2.49 2.49 0 0 1 21 8z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
