/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-football',
   styleUrl: './crai-icon-football.css',
   shadow: true,
   })
export class CraiIconFootball {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M13.185 16h-2.37a2.49 2.49 0 0 1-2.377-1.727l-.732-2.253a2.49 2.49 0 0 1 .908-2.8l1.916-1.388a2.49 2.49 0 0 1 2.938 0l1.917 1.392a2.49 2.49 0 0 1 .908 2.8l-.731 2.253A2.5 2.5 0 0 1 13.185 16M24 12A12 12 0 1 1 12 0a12.013 12.013 0 0 1 12 12m-12 9a9 9 0 0 0 1.544-.142l.848-2.781a2.99 2.99 0 0 1 2.847-2.084l2.817-.005a8.9 8.9 0 0 0 .871-2.9l-2.248-1.5a2.99 2.99 0 0 1-1.138-3.338l.853-2.573a9 9 0 0 0-2.458-1.756l-2.172 1.506a2.99 2.99 0 0 1-3.528 0L8.122 3.891a9 9 0 0 0-2.43 1.7l.767 2.657a2.99 2.99 0 0 1-1.138 3.338l-2.234 1.595a8.9 8.9 0 0 0 .857 2.807l2.816.005a2.99 2.99 0 0 1 2.848 2.083l.865 2.784q.758.135 1.527.14"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
