/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cloud-share',
   styleUrl: './crai-icon-cloud-share.css',
   shadow: true,
   })
export class CraiIconCloudShare {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 21a3 3 0 0 1-6 .014l-2.5-1.43A2.97 2.97 0 0 1 14 20a3 3 0 0 1 0-6 2.97 2.97 0 0 1 1.5.416l2.5-1.43A3 3 0 1 1 21 16a2.97 2.97 0 0 1-1.5-.416L17.023 17l2.477 1.416A2.97 2.97 0 0 1 21 18a3 3 0 0 1 3 3M9.308 3.057a5.2 5.2 0 0 1 5.254 2.496c.343.587.566 1.237.655 1.911a1.5 1.5 0 0 0 1.29 1.288q.511.069 1 .237a1.5 1.5 0 0 0 .976-2.837 8 8 0 0 0-.515-.158A8.176 8.176 0 0 0 8.882.087a8.05 8.05 0 0 0-6.736 6.5 8.1 8.1 0 0 0 .541 4.825 5.76 5.76 0 0 0-2.5 6.3A5.884 5.884 0 0 0 5.968 22H8.5a1.5 1.5 0 1 0 0-3H5.968a2.926 2.926 0 0 1-2.875-2.038 2.765 2.765 0 0 1 1.444-3.157A2.48 2.48 0 0 0 5.55 10.45a5.1 5.1 0 0 1-.456-3.3 5.05 5.05 0 0 1 4.215-4.093"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
