/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-ticket',
   styleUrl: './crai-icon-ticket.css',
   shadow: true,
   })
export class CraiIconTicket {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M15.5 0h-.688a1.5 1.5 0 0 0-1.5 1.5 1.313 1.313 0 1 1-2.625 0 1.5 1.5 0 0 0-1.5-1.5H8.5A5.506 5.506 0 0 0 3 5.5v15A3.5 3.5 0 0 0 6.5 24h2.687a1.5 1.5 0 0 0 1.5-1.5 1.314 1.314 0 1 1 2.625 0 1.5 1.5 0 0 0 1.5 1.5H17.5a3.5 3.5 0 0 0 3.5-3.5v-15A5.506 5.506 0 0 0 15.5 0m2 21h-1.45a4.3 4.3 0 0 0-8.1 0H6.5a.5.5 0 0 1-.5-.5V16h.5a1.5 1.5 0 1 0 0-3H6V5.5a2.5 2.5 0 0 1 1.971-2.443 4.3 4.3 0 0 0 8.058 0A2.5 2.5 0 0 1 18 5.5V13h-.5a1.5 1.5 0 1 0 0 3h.5v4.5a.5.5 0 0 1-.5.5"/><path d="M12.5 13h-1a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 0 0-3"/></svg>
        </Host>
    );
  }
}
