/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-pharmacy',
   styleUrl: './crai-icon-pharmacy.css',
   shadow: true,
   })
export class CraiIconPharmacy {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 24a4 4 0 0 1-4-4v-4H4a4 4 0 1 1 0-8h4V4a4 4 0 0 1 8 0v4h4a4 4 0 1 1 0 8h-4v4a4 4 0 0 1-4 4M4 11a1 1 0 0 0 0 2h5.5a1.5 1.5 0 0 1 1.5 1.5V20a1 1 0 0 0 2 0v-5.5a1.5 1.5 0 0 1 1.5-1.5H20a1 1 0 0 0 0-2h-5.5A1.5 1.5 0 0 1 13 9.5V4a1 1 0 0 0-2 0v5.5A1.5 1.5 0 0 1 9.5 11z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
