/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-lipstick',
   styleUrl: './crai-icon-lipstick.css',
   shadow: true,
   })
export class CraiIconLipstick {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M17 12.35V8.5A1.5 1.5 0 0 0 15.5 7H15V1.81A1.81 1.81 0 0 0 12.381.192l-1.965.983A2.56 2.56 0 0 0 9 3.465V7h-.5A1.5 1.5 0 0 0 7 8.5v3.85a3.5 3.5 0 0 0-2 3.15v3a5.506 5.506 0 0 0 5.5 5.5h3a5.506 5.506 0 0 0 5.5-5.5v-3a3.5 3.5 0 0 0-2-3.15M10 12v-2h4v2zm6 6.5a2.5 2.5 0 0 1-2.5 2.5h-3A2.5 2.5 0 0 1 8 18.5v-3a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 .5.5z"/></svg>
        </Host>
    );
  }
}
