/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-doctor',
   styleUrl: './crai-icon-doctor.css',
   shadow: true,
   })
export class CraiIconDoctor {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 5H17V3.5A3.5 3.5 0 0 0 13.5 0h-3A3.5 3.5 0 0 0 7 3.5V5H5.5A5.506 5.506 0 0 0 0 10.5v8A5.506 5.506 0 0 0 5.5 24h13a5.506 5.506 0 0 0 5.5-5.5v-8A5.506 5.506 0 0 0 18.5 5M10 3.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5V5h-4zm11 15a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 18.5v-8A2.5 2.5 0 0 1 5.5 8h13a2.5 2.5 0 0 1 2.5 2.5zm-4.5-4A1.5 1.5 0 0 1 15 16h-1.5v1.5a1.5 1.5 0 1 1-3 0V16H9a1.5 1.5 0 1 1 0-3h1.5v-1.5a1.5 1.5 0 1 1 3 0V13H15a1.5 1.5 0 0 1 1.5 1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
