/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-vector',
   styleUrl: './crai-icon-vector.css',
   shadow: true,
   })
export class CraiIconVector {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M5.5 0h-2A3.5 3.5 0 0 0 0 3.5v2a3.494 3.494 0 0 0 2.99 3.448v.545a1.5 1.5 0 0 0 2.998.014V8.95a3.485 3.485 0 0 0 2.96-2.94h.544a1.5 1.5 0 1 0 .016-2.998H8.95A3.494 3.494 0 0 0 5.5 0M6 5.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5zM20.5 0h-2a3.494 3.494 0 0 0-3.448 2.99h-.544a1.5 1.5 0 1 0-.016 2.998h.558a3.485 3.485 0 0 0 2.94 2.958v.545a1.5 1.5 0 1 0 2.998.016V8.95A3.494 3.494 0 0 0 24 5.5v-2A3.5 3.5 0 0 0 20.5 0m.5 5.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5zm.01 9.553v-.545a1.5 1.5 0 1 0-2.998-.014v.557a3.485 3.485 0 0 0-2.957 2.94h-.544a1.5 1.5 0 0 0-1.4 2.064 1.5 1.5 0 0 0 1.38.934h.559A3.494 3.494 0 0 0 18.5 24h2a3.5 3.5 0 0 0 3.5-3.5v-2a3.494 3.494 0 0 0-2.99-3.448M21 20.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5zM6.01 15.053v-.545a1.5 1.5 0 1 0-2.998-.014v.557A3.494 3.494 0 0 0 0 18.5v2A3.5 3.5 0 0 0 3.5 24h2a3.494 3.494 0 0 0 3.448-2.99h.544a1.5 1.5 0 1 0 .016-2.998H8.95a3.485 3.485 0 0 0-2.94-2.96M6 20.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
