/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-align-center',
   styleUrl: './crai-icon-align-center.css',
   shadow: true,
   })
export class CraiIconAlignCenter {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M1.5 6h21a1.5 1.5 0 0 0 0-3h-21a1.5 1.5 0 0 0 0 3m4 2a1.5 1.5 0 0 0 0 3h13a1.5 1.5 0 1 0 0-3zm13 10h-13a1.5 1.5 0 1 0 0 3h13a1.5 1.5 0 1 0 0-3m4-5h-21a1.5 1.5 0 1 0 0 3h21a1.5 1.5 0 1 0 0-3"/></svg>
        </Host>
    );
  }
}
