/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-jpg',
   styleUrl: './crai-icon-jpg.css',
   shadow: true,
   })
export class CraiIconJpg {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m10.258 5.473-.006-1.723h.838a.887.887 0 0 1 .889.86.886.886 0 0 1-.889.859zM24 4.5v11.343a5.46 5.46 0 0 1-1.611 3.889l-2.657 2.657A5.46 5.46 0 0 1 15.843 24H4.5A4.505 4.505 0 0 1 0 19.5v-15A4.505 4.505 0 0 1 4.5 0h15A4.505 4.505 0 0 1 24 4.5M14 6.584a1.993 1.993 0 0 0 2 1.985 2 2 0 0 0 2-1.984V6.25a.75.75 0 0 0-.75-.75h-.75a.5.5 0 0 0 0 1h.249v.084a.76.76 0 0 1-1.038.68.74.74 0 0 1-.461-.696V4.5a.742.742 0 0 1 1.136-.634.8.8 0 0 1 .276.293.626.626 0 1 0 1.11-.58A2.02 2.02 0 0 0 16 2.5a1.99 1.99 0 0 0-2 1.985zm-5 1.36a.625.625 0 0 0 1.25 0V6.723h.84a2.11 2.11 0 1 0 0-4.219H10a1 1 0 0 0-1 1zM4.072 7.4a2.11 2.11 0 0 0 1.849 1.17A2.07 2.07 0 0 0 8 6.506V3.15a.65.65 0 1 0-1.3 0v3.34a.77.77 0 0 1-.778.781.82.82 0 0 1-.687-.459.652.652 0 1 0-1.163.588M4.5 21H15v-4a2 2 0 0 1 2-2h4v-4H3v8.5A1.5 1.5 0 0 0 4.5 21"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
