/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-pencil',
   styleUrl: './crai-icon-pencil.css',
   shadow: true,
   })
export class CraiIconPencil {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.824 1.176a4.11 4.11 0 0 0-5.676 0L1.611 16.713A5.46 5.46 0 0 0 .001 20.6v1.9A1.5 1.5 0 0 0 1.5 24h1.9a5.46 5.46 0 0 0 3.888-1.611L22.824 6.852a4.02 4.02 0 0 0 0-5.676M5.166 20.268c-.47.467-1.104.73-1.766.732H3v-.4a2.52 2.52 0 0 1 .732-1.768L15.3 7.267 16.733 8.7zM20.7 4.731 18.854 6.58 17.42 5.146 19.27 3.3a1.037 1.037 0 0 1 1.433 0 1.015 1.015 0 0 1-.003 1.431"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
