/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-fox',
   styleUrl: './crai-icon-fox.css',
   shadow: true,
   })
export class CraiIconFox {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.07.534a2.45 2.45 0 0 0-2.084-.47 6.38 6.38 0 0 0-4.13 3.617 19 19 0 0 0-9.712 0A6.4 6.4 0 0 0 3.014.064 2.46 2.46 0 0 0 0 2.46v7.5a10.98 10.98 0 0 0 3.235 7.81l4.446 4.44a6.134 6.134 0 0 0 8.638 0l4.446-4.444A10.97 10.97 0 0 0 24 9.955V2.46a2.45 2.45 0 0 0-.93-1.926M4.85 5.974a1.5 1.5 0 0 0 1.916.943A18.5 18.5 0 0 1 12 6a18.6 18.6 0 0 1 5.234.917 1.5 1.5 0 0 0 1.916-.943A5 5 0 0 1 21 3.269v3.9a12.54 12.54 0 0 0-9 6.287A12.54 12.54 0 0 0 3 7.17v-3.9a5 5 0 0 1 1.85 2.705m.507 9.67a7.98 7.98 0 0 1-2.343-5.392c.693.165 1.37.395 2.02.686.06.588.275 1.15.622 1.63A3.71 3.71 0 0 0 8.8 14a9.9 9.9 0 0 1 1.647 5.144 2.9 2.9 0 0 0-.81.784zm13.287 0-4.284 4.283a2.9 2.9 0 0 0-.81-.784A9.87 9.87 0 0 1 15.2 14a3.71 3.71 0 0 0 3.147-1.431c.347-.48.562-1.042.622-1.63q.979-.436 2.02-.686a8 8 0 0 1-2.345 5.392"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
