/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-mobile',
   styleUrl: './crai-icon-mobile.css',
   shadow: true,
   })
export class CraiIconMobile {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M16.5 0h-9A5.506 5.506 0 0 0 2 5.5v13A5.506 5.506 0 0 0 7.5 24h9a5.506 5.506 0 0 0 5.5-5.5v-13A5.506 5.506 0 0 0 16.5 0M19 18.5a2.5 2.5 0 0 1-2.5 2.5h-3v-.5a1.5 1.5 0 0 0-3 0v.5h-3A2.5 2.5 0 0 1 5 18.5v-13A2.5 2.5 0 0 1 7.5 3h9A2.5 2.5 0 0 1 19 5.5zm-3-2a1.5 1.5 0 0 1-1.5 1.5h-5a1.5 1.5 0 1 1 0-3h5a1.5 1.5 0 0 1 1.5 1.5M12 4a4 4 0 0 0-4 4v3.5a1.5 1.5 0 0 0 2.908.5h2.184A1.5 1.5 0 0 0 16 11.5V8a4 4 0 0 0-4-4m0 3a1 1 0 0 1 1 1v1h-2V8a1 1 0 0 1 1-1"/></svg>
        </Host>
    );
  }
}
