/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-leaf',
   styleUrl: './crai-icon-leaf.css',
   shadow: true,
   })
export class CraiIconLeaf {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23 .988a3.39 3.39 0 0 0-2.725-.972C17.577.276 8.493 1.406 4.92 4.979a10 10 0 0 0-.973 12.953L.439 21.439a1.5 1.5 0 0 0 2.122 2.122l3.507-3.508a10 10 0 0 0 12.953-.973c3.623-3.623 4.716-12.68 4.964-15.371A3.39 3.39 0 0 0 23 .988m-6.1 15.97a6.99 6.99 0 0 1-8.68.942l8.341-8.34a1.5 1.5 0 1 0-2.122-2.122L6.1 15.78a6.99 6.99 0 0 1 .942-8.68c2.28-2.28 8.709-3.632 13.523-4.1a.4.4 0 0 1 .319.113.39.39 0 0 1 .116.32c-.445 4.792-1.784 11.209-4.1 13.525"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
