/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-form',
   styleUrl: './crai-icon-form.css',
   shadow: true,
   })
export class CraiIconForm {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M17 17.5a1.5 1.5 0 0 1-1.5 1.5h-7a1.5 1.5 0 1 1 0-3h7a1.5 1.5 0 0 1 1.5 1.5m5-10.343V18.5a5.506 5.506 0 0 1-5.5 5.5h-9A5.506 5.506 0 0 1 2 18.5v-13A5.506 5.506 0 0 1 7.5 0h7.343a5.46 5.46 0 0 1 3.889 1.61l1.657 1.658a5.46 5.46 0 0 1 1.61 3.889M18.985 7H17a2 2 0 0 1-2-2V3.016C14.947 3.012 7.5 3 7.5 3A2.5 2.5 0 0 0 5 5.5v13A2.5 2.5 0 0 0 7.5 21h9a2.5 2.5 0 0 0 2.5-2.5S18.988 7.053 18.985 7M14.5 9h-5a2.5 2.5 0 1 0 0 5h5a2.5 2.5 0 0 0 0-5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
