/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-shield-exclamation',
   styleUrl: './crai-icon-shield-exclamation.css',
   shadow: true,
   })
export class CraiIconShieldExclamation {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 24a1.5 1.5 0 0 1-.671-.158l-.38-.191c-2.097-1.05-8.95-4.98-8.95-11.5v-5.1a5.27 5.27 0 0 1 3.618-5.01l5.91-1.964c.307-.101.638-.101.945 0l5.91 1.96A5.27 5.27 0 0 1 22 7.047v5.1c0 7.37-6.922 10.728-9.043 11.58l-.394.16c-.179.074-.37.113-.563.114m0-20.92-5.44 1.8A2.27 2.27 0 0 0 5 7.048v5.1c0 4.607 5.143 7.705 7.068 8.7 1.9-.808 6.932-3.444 6.932-8.7v-5.1a2.27 2.27 0 0 0-1.561-2.162zm1.5 9.42v-6a1.5 1.5 0 0 0-3 0v6a1.5 1.5 0 1 0 3 0M12 15a1.5 1.5 0 1 0 0 3.002A1.5 1.5 0 0 0 12 15"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
