/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-taxi',
   styleUrl: './crai-icon-taxi.css',
   shadow: true,
   })
export class CraiIconTaxi {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 10a1.5 1.5 0 0 0-1.5-1.5h-1.468l-.779-2.63A5.46 5.46 0 0 0 15.6 2.048 4 4 0 0 0 12.117 0h-.234A3.99 3.99 0 0 0 8.4 2.044a5.47 5.47 0 0 0-4.712 3.845L2.916 8.5H1.5a1.5 1.5 0 0 0 0 3h.528l-.477 1.628A4.461 4.461 0 0 0 3 20.724V22a2 2 0 0 0 4 0v-1h10v1a2 2 0 0 0 4 0v-1.276a4.46 4.46 0 0 0 1.386-7.648L21.92 11.5h.58A1.5 1.5 0 0 0 24 10M6.56 6.758A2.49 2.49 0 0 1 8.947 5H15a2.48 2.48 0 0 1 2.382 1.74L18.939 12H5.008zM19.5 18h-15a1.5 1.5 0 1 1 0-3H5v.5a1.5 1.5 0 0 0 3 0V15h8v.5a1.5 1.5 0 1 0 3 0V15h.5a1.5 1.5 0 1 1 0 3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
