/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-delete',
   styleUrl: './crai-icon-delete.css',
   shadow: true,
   })
export class CraiIconDelete {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m17.56 10.561-1.44 1.44 1.44 1.438a1.5 1.5 0 0 1-2.121 2.122l-1.44-1.44-1.438 1.44a1.5 1.5 0 1 1-2.122-2.122L11.879 12l-1.44-1.439A1.5 1.5 0 0 1 12.56 8.44L14 9.88l1.439-1.44a1.5 1.5 0 0 1 2.122 2.122M24 7.001v10a5.006 5.006 0 0 1-5 5H9.977a5.53 5.53 0 0 1-4.37-2.16l-5.3-6.93a1.5 1.5 0 0 1 0-1.822l5.3-6.93A5.53 5.53 0 0 1 9.977 2H19a5.006 5.006 0 0 1 5 5m-3 0a2 2 0 0 0-2-2H9.977a2.52 2.52 0 0 0-1.987.98L3.389 12l4.6 6.018A2.52 2.52 0 0 0 9.977 19H19a2 2 0 0 0 2-2z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
