/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cocktail',
   styleUrl: './crai-icon-cocktail.css',
   shadow: true,
   })
export class CraiIconCocktail {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.46 2.273A4.37 4.37 0 0 0 19.628 0H4.372A4.37 4.37 0 0 0 .54 2.273a4.27 4.27 0 0 0 .144 4.411A14.03 14.03 0 0 0 10.5 12.9V21h-3a1.5 1.5 0 1 0 0 3h9a1.5 1.5 0 1 0 0-3h-3v-8.1a14.03 14.03 0 0 0 9.816-6.217 4.27 4.27 0 0 0 .144-4.41M12 10a11.07 11.07 0 0 1-8.817-5h17.634A11.07 11.07 0 0 1 12 10"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
