/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-unlock',
   styleUrl: './crai-icon-unlock.css',
   shadow: true,
   })
export class CraiIconUnlock {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M16.5 8.001H8v-.773a4.228 4.228 0 0 1 7.927-2.047 1.5 1.5 0 1 0 2.623-1.456A7.227 7.227 0 0 0 5 7.228v1.38A5.5 5.5 0 0 0 2 13.5v5A5.506 5.506 0 0 0 7.5 24h9a5.506 5.506 0 0 0 5.5-5.5v-5a5.506 5.506 0 0 0-5.5-5.499m2.5 10.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 5 18.5v-5A2.5 2.5 0 0 1 7.5 11h9a2.5 2.5 0 0 1 2.5 2.5z"/><path d="M11.5 14h1a1.5 1.5 0 0 1 0 3h-1a1.5 1.5 0 1 1 0-3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
