/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-book',
   styleUrl: './crai-icon-book.css',
   shadow: true,
   })
export class CraiIconBook {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M16.5 0h-8A6.51 6.51 0 0 0 2 6.5v13A4.505 4.505 0 0 0 6.5 24h10a5.507 5.507 0 0 0 5.5-5.5v-13A5.507 5.507 0 0 0 16.5 0M8 3.051V15H6.5a4.5 4.5 0 0 0-1.5.276V6.5a3.494 3.494 0 0 1 3-3.449M19 18.5a2.5 2.5 0 0 1-2.5 2.5h-10a1.5 1.5 0 1 1 0-3H19zM11 15V3h5.5A2.5 2.5 0 0 1 19 5.5V15z"/></svg>
        </Host>
    );
  }
}
