/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-chart-set-theory',
   styleUrl: './crai-icon-chart-set-theory.css',
   shadow: true,
   })
export class CraiIconChartSetTheory {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.42 9.592q.08-.542.08-1.092A7.5 7.5 0 1 0 4.58 9.592 7.5 7.5 0 1 0 12 22.5a7.5 7.5 0 1 0 7.42-12.9zM12 4a4.505 4.505 0 0 1 4.472 5A7.46 7.46 0 0 0 12 10.5 7.46 7.46 0 0 0 7.528 9 4.505 4.505 0 0 1 12 4M3 16.5a4.5 4.5 0 0 1 2.607-4.082 7.55 7.55 0 0 0 3.473 2.99A7.5 7.5 0 0 0 10 20.24a4.5 4.5 0 0 1-7-3.74M16.5 21a4.47 4.47 0 0 1-2.5-.76 7.5 7.5 0 0 0 .92-4.832 7.55 7.55 0 0 0 3.473-2.99A4.5 4.5 0 0 1 16.5 21"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
