/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-menu-dots-vertical',
   styleUrl: './crai-icon-menu-dots-vertical.css',
   shadow: true,
   })
export class CraiIconMenuDotsVertical {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M12 5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5m0 9.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5m0 9.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/></svg>
        </Host>
    );
  }
}
