/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-spinner-alt',
   styleUrl: './crai-icon-spinner-alt.css',
   shadow: true,
   })
export class CraiIconSpinnerAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 5a1.5 1.5 0 0 1-1.5-1.5v-2a1.5 1.5 0 1 1 3 0v2A1.5 1.5 0 0 1 12 5m1.5 17.5v-2a1.5 1.5 0 1 0-3 0v2a1.5 1.5 0 1 0 3 0M5 12a1.5 1.5 0 0 0-1.5-1.5h-2a1.5 1.5 0 1 0 0 3h2A1.5 1.5 0 0 0 5 12m19 0a1.5 1.5 0 0 0-1.5-1.5h-2a1.5 1.5 0 1 0 0 3h2A1.5 1.5 0 0 0 24 12m-6.524-6.671.981-1.743a1.5 1.5 0 0 0-2.613-1.473l-.982 1.743a1.5 1.5 0 1 0 2.614 1.473m-9.32 16.558.982-1.743a1.5 1.5 0 0 0-2.614-1.473l-.981 1.743a1.5 1.5 0 0 0 2.613 1.473M5.9 8.567a1.5 1.5 0 0 0-.57-2.043l-1.744-.981a1.5 1.5 0 0 0-1.473 2.613l1.743.982A1.5 1.5 0 0 0 5.9 8.567m16.558 9.32a1.5 1.5 0 0 0-.57-2.043l-1.743-.982a1.5 1.5 0 1 0-1.473 2.614l1.743.981a1.5 1.5 0 0 0 2.043-.57M8.567 5.9a1.5 1.5 0 0 0 .571-2.043l-.982-1.744a1.5 1.5 0 0 0-2.613 1.473l.981 1.743a1.5 1.5 0 0 0 2.043.571m9.32 16.558a1.5 1.5 0 0 0 .57-2.043l-.981-1.743a1.5 1.5 0 0 0-2.614 1.473l.982 1.743a1.5 1.5 0 0 0 2.043.57m2.257-13.32 1.743-.982a1.5 1.5 0 0 0-1.473-2.613l-1.743.981a1.5 1.5 0 0 0 1.473 2.614M3.586 18.457l1.743-.981a1.5 1.5 0 1 0-1.473-2.614l-1.743.982a1.5 1.5 0 0 0 1.473 2.613"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
