/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-time-past',
   styleUrl: './crai-icon-time-past.css',
   shadow: true,
   })
export class CraiIconTimePast {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0a12.03 12.03 0 0 0-7.96 3.04L2.707 1.707A1 1 0 0 0 1 2.414V7a1 1 0 0 0 1 1h4.586a1 1 0 0 0 .707-1.707L6.158 5.158A9 9 0 1 1 3.1 13.316a1.51 1.51 0 0 0-2.613-.824 1.5 1.5 0 0 0-.372 1.171 12.02 12.02 0 0 0 12.359 10.328 12.114 12.114 0 0 0 11.517-11.517A12.013 12.013 0 0 0 12 0"/><path d="M11.5 7A1.5 1.5 0 0 0 10 8.5v4.292a2 2 0 0 0 .586 1.414L12.38 16a1.5 1.5 0 0 0 2.121-2.12l-1.5-1.5V8.5A1.5 1.5 0 0 0 11.5 7"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
