/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-flower-bouquet',
   styleUrl: './crai-icon-flower-bouquet.css',
   shadow: true,
   })
export class CraiIconFlowerBouquet {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 11.6a3.56 3.56 0 0 0-1.625-3.025 11.8 11.8 0 0 0 .615-5.046 2.6 2.6 0 0 0-1.052-2.035 2.49 2.49 0 0 0-2.165-.4 12.8 12.8 0 0 0-4.3 2.167A16 16 0 0 0 14 .937a2.492 2.492 0 0 0-3.9 0 16 16 0 0 0-1.5 2.375 12.8 12.8 0 0 0-4.378-2.219 2.49 2.49 0 0 0-2.16.4A2.6 2.6 0 0 0 1.01 3.529a11.8 11.8 0 0 0 .613 5.046A3.56 3.56 0 0 0 0 11.6c0 4.933 7.34 8.066 10 9.04a4.4 4.4 0 0 0-.76.9 1.53 1.53 0 0 0-.01 1.624c.325.524.9.84 1.516.836h2.508a1.77 1.77 0 0 0 1.518-.842 1.53 1.53 0 0 0-.01-1.625 4 4 0 0 0-.408-.533H16.5a1.5 1.5 0 0 1 1.5 1.5 1.5 1.5 0 0 0 3 0 4.49 4.49 0 0 0-2.445-3.98C21.282 16.932 24 14.6 24 11.6m-6.817-5.8c.03-.044.097-.125.097-.125A7.9 7.9 0 0 1 20 4.168a7.8 7.8 0 0 1-.387 3.22 1.4 1.4 0 0 1-.96.578 1.44 1.44 0 0 1-1.1-.293 1.35 1.35 0 0 1-.37-1.873M12.05 3.353a9.8 9.8 0 0 1 1.5 3.148 1.5 1.5 0 0 1-3 0 9.8 9.8 0 0 1 1.5-3.148m-8.083.815a7.9 7.9 0 0 1 2.72 1.507s.068.08.098.125a1.35 1.35 0 0 1-.372 1.873 1.44 1.44 0 0 1-1.1.293 1.4 1.4 0 0 1-.959-.578 7.8 7.8 0 0 1-.387-3.22M21 11.6c0 1.935-2.924 3.893-5.654 5.206a9 9 0 0 0 .634-2.06 1.5 1.5 0 1 0-2.96-.49 8.2 8.2 0 0 1-.995 2.492 10.2 10.2 0 0 1-1.061-2.576 1.5 1.5 0 1 0-2.928.656q.245 1.037.683 2.008c-2.748-1.313-5.72-3.286-5.72-5.236a.58.58 0 0 1 .583-.6h16.836a.58.58 0 0 1 .582.6"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
