/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-time-half-past',
   styleUrl: './crai-icon-time-half-past.css',
   shadow: true,
   })
export class CraiIconTimeHalfPast {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M10 12c.002-.483.18-.949.5-1.31V7a1.5 1.5 0 1 1 3 0v3.69a1.966 1.966 0 0 1 0 2.62v2.19a1.5 1.5 0 1 1-3 0v-2.19A2 2 0 0 1 10 12m2-12a1.5 1.5 0 0 0 0 3 9 9 0 0 1 0 18 1.5 1.5 0 1 0 0 3 12 12 0 0 0 0-24M3 12a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0M6.74 1.394a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M2.913 5.25a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M6.74 19.606a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M2.913 15.75a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
