/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-arrow-small-down',
   styleUrl: './crai-icon-arrow-small-down.css',
   shadow: true,
   })
export class CraiIconArrowSmallDown {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M18.061 12.354a1.5 1.5 0 0 0-2.122 0L13.5 14.793V6a1.5 1.5 0 0 0-3 0v8.793l-2.439-2.439a1.5 1.5 0 0 0-2.122 2.121l3.586 3.586a3.5 3.5 0 0 0 4.95 0l3.586-3.586a1.5 1.5 0 0 0 0-2.121"/></svg>
        </Host>
    );
  }
}
