/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-grid',
   styleUrl: './crai-icon-grid.css',
   shadow: true,
   })
export class CraiIconGrid {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M2 17.5h2.5a2 2 0 0 1 2 2V22a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a2 2 0 0 1 2-2m17.5 0H22a2 2 0 0 1 2 2V22a2 2 0 0 1-2 2h-2.5a2 2 0 0 1-2-2v-2.5a2 2 0 0 1 2-2M2 8.75h2.5a2 2 0 0 1 2 2v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a2 2 0 0 1 2-2m17.5 0H22a2 2 0 0 1 2 2v2.5a2 2 0 0 1-2 2h-2.5a2 2 0 0 1-2-2v-2.5a2 2 0 0 1 2-2M2 0h2.5a2 2 0 0 1 2 2v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2m8.75 17.5h2.5a2 2 0 0 1 2 2V22a2 2 0 0 1-2 2h-2.5a2 2 0 0 1-2-2v-2.5a2 2 0 0 1 2-2m0-8.75h2.5a2 2 0 0 1 2 2v2.5a2 2 0 0 1-2 2h-2.5a2 2 0 0 1-2-2v-2.5a2 2 0 0 1 2-2m0-8.75h2.5a2 2 0 0 1 2 2v2.5a2 2 0 0 1-2 2h-2.5a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2m8.75 0H22a2 2 0 0 1 2 2v2.5a2 2 0 0 1-2 2h-2.5a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
