/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-sad',
   styleUrl: './crai-icon-sad.css',
   shadow: true,
   })
export class CraiIconSad {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M8.5 7A2.587 2.587 0 0 1 11 9.667C11 11 9.881 11 8.5 11S6 11 6 9.667A2.587 2.587 0 0 1 8.5 7M13 9.667C13 11 14.119 11 15.5 11S18 11 18 9.667A2.587 2.587 0 0 0 15.5 7 2.587 2.587 0 0 0 13 9.667M24 12a12 12 0 1 0-12 12 12.013 12.013 0 0 0 12-12m-3 0a9 9 0 1 1-9-9 9.01 9.01 0 0 1 9 9m-3.935 5.056a1.5 1.5 0 0 0-.009-2.122 7.576 7.576 0 0 0-10.112 0 1.493 1.493 0 0 0 1.035 2.552 1.5 1.5 0 0 0 1.065-.413 4.594 4.594 0 0 1 5.91 0 1.5 1.5 0 0 0 2.111-.02z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
