/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-bookmark',
   styleUrl: './crai-icon-bookmark.css',
   shadow: true,
   })
export class CraiIconBookmark {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M17.5 0h-11A5.507 5.507 0 0 0 1 5.5v14.972a3.5 3.5 0 0 0 6.044 2.4l4.912-5.2 5.013 5.25a3.501 3.501 0 0 0 6.03-2.412V5.5A5.507 5.507 0 0 0 17.5 0M20 20.51a.499.499 0 0 1-.861.345l-6.1-6.391a1.5 1.5 0 0 0-2.175.006l-6 6.345a.48.48 0 0 1-.55.122.47.47 0 0 1-.314-.465V5.5A2.5 2.5 0 0 1 6.5 3h11A2.5 2.5 0 0 1 20 5.5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
