/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cursor-text',
   styleUrl: './crai-icon-cursor-text.css',
   shadow: true,
   })
export class CraiIconCursorText {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M17.5 21H16a2.5 2.5 0 0 1-2.5-2.5V16h3a1.5 1.5 0 1 0 0-3h-3V5.5A2.5 2.5 0 0 1 16 3h1.5a1.5 1.5 0 0 0 0-3H16a5.48 5.48 0 0 0-4 1.737A5.48 5.48 0 0 0 8 0H6.5a1.5 1.5 0 1 0 0 3H8a2.5 2.5 0 0 1 2.5 2.5V13h-3a1.5 1.5 0 1 0 0 3h3v2.5A2.5 2.5 0 0 1 8 21H6.5a1.5 1.5 0 1 0 0 3H8a5.48 5.48 0 0 0 4-1.737A5.48 5.48 0 0 0 16 24h1.5a1.5 1.5 0 1 0 0-3"/></svg>
        </Host>
    );
  }
}
