/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-gamepad',
   styleUrl: './crai-icon-gamepad.css',
   shadow: true,
   })
export class CraiIconGamepad {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M17.7 3H6.3C4.4 3 2.7 4 1.7 5.7.6 7.6 0 9.8 0 12c0 4.9 2 10 5.3 10 1.8 0 3.3-1.4 4-3.7.1-.2.2-.3.4-.3h4.6c.2 0 .4.1.4.3 1 3.2 2.9 3.7 3.9 3.7C22 22 24 16.9 24 12c0-2.2-.6-4.4-1.7-6.4C21.4 4 19.6 3 17.7 3m1 16c-.3 0-.7-.5-1-1.6-.5-1.4-1.8-2.4-3.3-2.4H9.7c-1.5 0-2.8 1-3.3 2.4-.3 1-.8 1.6-1.1 1.6-.6-.1-2.3-2.6-2.3-7 0-1.7.5-3.4 1.3-4.9.4-.7 1.2-1.1 2-1.1h11.4c.8 0 1.6.4 2 1.1.9 1.5 1.3 3.2 1.3 4.9 0 4.4-1.7 6.9-2.3 7"/><path d="M10.5 9H10v-.5C10 7.7 9.3 7 8.5 7S7 7.7 7 8.5V9h-.5C5.7 9 5 9.7 5 10.5S5.7 12 6.5 12H7v.5c0 .8.7 1.5 1.5 1.5s1.5-.7 1.5-1.5V12h.5c.8 0 1.5-.7 1.5-1.5S11.3 9 10.5 9m6.5 3a2 2 0 1 0 0-4 2 2 0 0 0 0 4"/></svg>
        </Host>
    );
  }
}
