/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-hourglass',
   styleUrl: './crai-icon-hourglass.css',
   shadow: true,
   })
export class CraiIconHourglass {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M16.632 24H7.368a4.38 4.38 0 0 1-3.319-1.523 4.3 4.3 0 0 1-1-3.451A12.2 12.2 0 0 1 6.983 12a12.2 12.2 0 0 1-3.935-7.025 4.3 4.3 0 0 1 1-3.451A4.38 4.38 0 0 1 7.368 0h9.264a4.38 4.38 0 0 1 4.195 3.138 4.3 4.3 0 0 1 .123 1.833A12.24 12.24 0 0 1 17.012 12a12.23 12.23 0 0 1 3.94 7.03 4.3 4.3 0 0 1-1 3.447A4.38 4.38 0 0 1 16.632 24m0-21H7.368a1.38 1.38 0 0 0-1.046.48 1.3 1.3 0 0 0-.307 1.048c.337 2.243 1.746 4.362 4.188 6.3a1.5 1.5 0 0 1 0 2.352c-2.442 1.933-3.851 4.052-4.188 6.3a1.3 1.3 0 0 0 .307 1.048A1.38 1.38 0 0 0 7.368 21h9.264a1.38 1.38 0 0 0 1.046-.481 1.3 1.3 0 0 0 .307-1.044c-.335-2.236-1.745-4.355-4.191-6.3a1.5 1.5 0 0 1 0-2.348c2.446-1.946 3.856-4.065 4.191-6.3a1.3 1.3 0 0 0-.307-1.045A1.38 1.38 0 0 0 16.632 3"/></svg>
        </Host>
    );
  }
}
