/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-soup',
   styleUrl: './crai-icon-soup.css',
   shadow: true,
   })
export class CraiIconSoup {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M14.122 24H9.877a8.77 8.77 0 0 1-6.157-2.493 14.1 14.1 0 0 1-3.546-6.04A4.26 4.26 0 0 1 4.252 10h15.5a4.284 4.284 0 0 1 4.079 5.467 14.1 14.1 0 0 1-3.548 6.04A8.76 8.76 0 0 1 14.122 24m-9.87-11a1.22 1.22 0 0 0-1 .5 1.27 1.27 0 0 0-.2 1.128 11.24 11.24 0 0 0 2.783 4.755A5.74 5.74 0 0 0 9.877 21h4.245a5.74 5.74 0 0 0 4.04-1.618 11.25 11.25 0 0 0 2.785-4.756 1.27 1.27 0 0 0-.2-1.128 1.22 1.22 0 0 0-1-.5zM17 6.5a5.17 5.17 0 0 0-1.44-3.647A1.76 1.76 0 0 1 15 1.5 1.5 1.5 0 0 0 13.5 0 1.5 1.5 0 0 0 12 1.5a4.76 4.76 0 0 0 1.439 3.473c.377.418.578.965.561 1.527a1.5 1.5 0 0 0 3 0m-5 1v-.308a4.9 4.9 0 0 0-1.439-3.474A1.9 1.9 0 0 1 10 2.364V1.5a1.5 1.5 0 1 0-3 0v.864a4.88 4.88 0 0 0 1.44 3.475A1.8 1.8 0 0 1 9 7.192V7.5a1.5 1.5 0 0 0 3 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
