/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-minus-small',
   styleUrl: './crai-icon-minus-small.css',
   shadow: true,
   })
export class CraiIconMinusSmall {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M16.5 13.5h-9a1.5 1.5 0 1 1 0-3h9a1.5 1.5 0 1 1 0 3"/></svg>
        </Host>
    );
  }
}
