/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-room-service',
   styleUrl: './crai-icon-room-service.css',
   shadow: true,
   })
export class CraiIconRoomService {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M23 19.093V16a11.01 11.01 0 0 0-9.5-10.885V4.31a1.995 1.995 0 1 0-3 0v.805A11.01 11.01 0 0 0 1 16v3.092A1.5 1.5 0 0 0 1.5 22h21a1.5 1.5 0 0 0 .5-2.908M12 8a8.01 8.01 0 0 1 8 8v3H4v-3a8.01 8.01 0 0 1 8-8"/></svg>
        </Host>
    );
  }
}
