/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cursor-plus',
   styleUrl: './crai-icon-cursor-plus.css',
   shadow: true,
   })
export class CraiIconCursorPlus {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M15.5 7a8.5 8.5 0 1 0 8.5 8.5A8.51 8.51 0 0 0 15.5 7m0 14a5.5 5.5 0 1 1 5.5-5.5 5.507 5.507 0 0 1-5.5 5.5m3-7a1.5 1.5 0 1 1 0 3H17v1.5a1.5 1.5 0 0 1-3 0V17h-1.5a1.5 1.5 0 0 1 0-3H14v-1.5a1.5 1.5 0 1 1 3 0V14zM7.745 7.745l-1.85 3.7A1 1 0 0 1 5 12h-.019a1 1 0 0 1-.89-.586L.145 2.74A2.01 2.01 0 0 1 .588.59 1.99 1.99 0 0 1 2.65.108q.045.015.09.037l8.675 3.944a1 1 0 0 1 .033 1.8z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
