/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-raindrops',
   styleUrl: './crai-icon-raindrops.css',
   shadow: true,
   })
export class CraiIconRaindrops {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M17 24a7.01 7.01 0 0 1-7-7c0-1.927 1.474-4.58 4.379-7.885a3.515 3.515 0 0 1 5.24 0C22.527 12.42 24 15.073 24 17a7.01 7.01 0 0 1-7 7m0-13.07a.48.48 0 0 0-.368.167C13.954 14.142 13 16.143 13 17a4 4 0 1 0 8 0c0-.857-.954-2.858-3.633-5.9a.48.48 0 0 0-.367-.17M5.5 12.483a5.506 5.506 0 0 1-5.5-5.5c0-.808.246-2.243 2.375-5.341a3.82 3.82 0 0 1 6.249 0C10.754 4.74 11 6.175 11 6.982a5.506 5.506 0 0 1-5.5 5.5M5.5 3a.77.77 0 0 0-.653.342C3.052 5.955 3 6.886 3 6.982a2.5 2.5 0 0 0 5 0c0-.1-.052-1.027-1.848-3.641A.77.77 0 0 0 5.5 3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
