/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-star',
   styleUrl: './crai-icon-star.css',
   shadow: true,
   })
export class CraiIconStar {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M6.852 23.437a3.6 3.6 0 0 1-2.121-.7A3.57 3.57 0 0 1 3.4 18.683l1.17-3.619-3.08-2.252A3.625 3.625 0 0 1 3.63 6.26H7.4l1.145-3.57a3.627 3.627 0 0 1 6.906 0L16.6 6.26h3.77a3.625 3.625 0 0 1 2.139 6.552l-3.079 2.252 1.17 3.62a3.626 3.626 0 0 1-5.6 4.034l-3-2.206-3 2.207a3.62 3.62 0 0 1-2.148.718M3.63 9.26a.626.626 0 0 0-.37 1.131l3.956 2.891a1.5 1.5 0 0 1 .542 1.672l-1.5 4.65a.626.626 0 0 0 .966.7l3.889-2.86a1.5 1.5 0 0 1 1.778 0l3.889 2.86a.626.626 0 0 0 .966-.7l-1.5-4.65a1.5 1.5 0 0 1 .542-1.673l3.955-2.89a.626.626 0 0 0-.369-1.132H15.5a1.5 1.5 0 0 1-1.428-1.042L12.6 3.607a.626.626 0 0 0-1.192 0l-1.483 4.61A1.5 1.5 0 0 1 8.5 9.26z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
