/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-gas-pump',
   styleUrl: './crai-icon-gas-pump.css',
   shadow: true,
   })
export class CraiIconGasPump {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.529 2.471a1.5 1.5 0 0 0-2.121 0l-2.969 2.968A1.5 1.5 0 0 0 18 6.5v11a.5.5 0 0 1-.5.5H16V5.5A5.507 5.507 0 0 0 10.5 0h-5A5.507 5.507 0 0 0 0 5.5v13A5.507 5.507 0 0 0 5.5 24h5a5.5 5.5 0 0 0 4.9-3.01c.034 0 .067.01.1.01h2a3.5 3.5 0 0 0 3.5-3.5V7.121l2.529-2.529a1.5 1.5 0 0 0 0-2.121M5.5 3h5A2.5 2.5 0 0 1 13 5.5V9h-2.184a3 3 0 0 0-.521-.91l.491-.819a1.5 1.5 0 0 0-2.572-1.542l-.8 1.33A2.99 2.99 0 0 0 5.184 9H3V5.5A2.5 2.5 0 0 1 5.5 3m5 18h-5A2.5 2.5 0 0 1 3 18.5V12h10v6.5a2.5 2.5 0 0 1-2.5 2.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
