/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-call-incoming',
   styleUrl: './crai-icon-call-incoming.css',
   shadow: true,
   })
export class CraiIconCallIncoming {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.7 14.025a3.585 3.585 0 0 0-4.946 0l-.409.4a11.6 11.6 0 0 1-5.758-5.778l.388-.394a3.52 3.52 0 0 0 .039-4.91L7.862 1.025a3.583 3.583 0 0 0-4.908-.04l-1.092.953c-7.895 8.27 11.923 28.1 20.2 20.2.024-.025.954-1.09.954-1.09a3.516 3.516 0 0 0-.081-4.947zm.157 4.942c-.025.024-.949 1.083-.949 1.083C14.655 24.773-.91 10.127 3.95 4.1c0 0 1.059-.924 1.084-.949a.487.487 0 0 1 .667-.04l2.153 2.313a.485.485 0 0 1-.009.717L6.737 7.267a1.5 1.5 0 0 0-.323 1.61 14.86 14.86 0 0 0 8.732 8.723 1.5 1.5 0 0 0 1.588-.332l1.134-1.118c.29-.214.441-.212.748.04l2.238 2.074a.5.5 0 0 1 0 .703zM15 8V3.526a1 1 0 0 1 1.707-.707l1.187 1.187L21.437.442a1.5 1.5 0 0 1 2.126 2.116l-3.548 3.57 1.166 1.165A1 1 0 0 1 20.474 9H16a1 1 0 0 1-1-1"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
