/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-angle-double-left',
   styleUrl: './crai-icon-angle-double-left.css',
   shadow: true,
   })
export class CraiIconAngleDoubleLeft {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 24a1.5 1.5 0 0 1-1.06-.439l-7.676-7.672a5.5 5.5 0 0 1 0-7.778L10.936.439a1.5 1.5 0 0 1 2.121 2.122l-7.672 7.671a2.5 2.5 0 0 0 0 3.536l7.672 7.671A1.5 1.5 0 0 1 12 24"/><path d="M21.542 24a1.5 1.5 0 0 1-1.061-.439L11.4 14.475a3.505 3.505 0 0 1 0-4.95L20.481.44A1.5 1.5 0 0 1 22.6 2.561l-9.086 9.085a.5.5 0 0 0 0 .708L22.6 21.44A1.5 1.5 0 0 1 21.542 24"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
