/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-notebook',
   styleUrl: './crai-icon-notebook.css',
   shadow: true,
   })
export class CraiIconNotebook {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M19 2.607V1.5a1.5 1.5 0 1 0-3 0V2h-2.5v-.5a1.5 1.5 0 1 0-3 0V2H8v-.5a1.5 1.5 0 1 0-3 0v1.107A5.5 5.5 0 0 0 2 7.5v11A5.506 5.506 0 0 0 7.5 24h9a5.507 5.507 0 0 0 5.5-5.5v-11a5.5 5.5 0 0 0-3-4.893M19 18.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 5 18.5v-11A2.5 2.5 0 0 1 7.5 5h9A2.5 2.5 0 0 1 19 7.5zm-2-10a1.5 1.5 0 0 1-1.5 1.5h-7a1.5 1.5 0 0 1 0-3h7A1.5 1.5 0 0 1 17 8.5m-3.5 5A1.5 1.5 0 0 1 12 15H8.5a1.5 1.5 0 1 1 0-3H12a1.5 1.5 0 0 1 1.5 1.5"/></svg>
        </Host>
    );
  }
}
