/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-triangle',
   styleUrl: './crai-icon-triangle.css',
   shadow: true,
   })
export class CraiIconTriangle {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.586 23.046H4.414a4.39 4.39 0 0 1-3.759-2.083 4.31 4.31 0 0 1-.2-4.216l7.61-13.393a4.428 4.428 0 0 1 7.892.04l7.543 13.28a4.34 4.34 0 0 1-.159 4.289 4.39 4.39 0 0 1-3.755 2.083M12 3.955a1.4 1.4 0 0 0-1.27.774l-.039.074-7.59 13.353a1.29 1.29 0 0 0 .1 1.226 1.4 1.4 0 0 0 1.208.664h15.177a1.394 1.394 0 0 0 1.411-1.306 1.3 1.3 0 0 0-.14-.658L13.308 4.8A1.45 1.45 0 0 0 12 3.955"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
