/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-volume',
   styleUrl: './crai-icon-volume.css',
   shadow: true,
   })
export class CraiIconVolume {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.79 4.255a1.5 1.5 0 0 0-2.12 2.121 7.95 7.95 0 0 1 0 11.246 1.5 1.5 0 0 0 2.12 2.121 10.95 10.95 0 0 0 0-15.488"/><path d="M18.652 12a4.354 4.354 0 0 0-3.243-4.2V1.68A1.498 1.498 0 0 0 13.638.203 12.06 12.06 0 0 0 6.252 4.77H5.5a5.506 5.506 0 0 0-5.5 5.5v3.456a5.506 5.506 0 0 0 5.5 5.5h.754a12.06 12.06 0 0 0 7.384 4.572q.135.025.271.025a1.5 1.5 0 0 0 1.5-1.5V16.2a4.35 4.35 0 0 0 3.243-4.2m-6.243 8.321a9.1 9.1 0 0 1-4.124-3.415 1.5 1.5 0 0 0-1.256-.679H5.5a2.5 2.5 0 0 1-2.5-2.5v-3.456a2.5 2.5 0 0 1 2.5-2.5h1.529a1.5 1.5 0 0 0 1.256-.679 9.1 9.1 0 0 1 4.124-3.415z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
