/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-user',
   styleUrl: './crai-icon-user.css',
   shadow: true,
   })
export class CraiIconUser {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M11.452 14.019A8.19 8.19 0 0 0 4 22.284v.217a1.5 1.5 0 0 0 3 0v-.277a5.153 5.153 0 0 1 4.5-5.2A5.006 5.006 0 0 1 17 22v.5a1.5 1.5 0 0 0 3 0V22a8.01 8.01 0 0 0-8.548-7.982M12 12a6 6 0 1 0 0-12 6 6 0 0 0 0 12m0-9a3 3 0 1 1 0 6 3 3 0 0 1 0-6"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
