/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-tennis',
   styleUrl: './crai-icon-tennis.css',
   shadow: true,
   })
export class CraiIconTennis {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.49 3.51a11.995 11.995 0 1 0 0 16.97 12.014 12.014 0 0 0 0-16.97m.276 6.476a7.086 7.086 0 0 1-6.752-6.752 8.92 8.92 0 0 1 6.752 6.752M3.245 14A7.09 7.09 0 0 1 10 20.756 8.92 8.92 0 0 1 3.245 14m15.125 4.36a8.96 8.96 0 0 1-5.38 2.573 10.04 10.04 0 0 0-9.922-9.922 8.96 8.96 0 0 1 7.953-7.953 10.06 10.06 0 0 0 9.92 9.93 8.96 8.96 0 0 1-2.571 5.372"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
