/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-rugby',
   styleUrl: './crai-icon-rugby.css',
   shadow: true,
   })
export class CraiIconRugby {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.024 1.975C18.5-1.554 9.377-.178 4.6 4.6s-6.151 13.9-2.624 17.424A8.32 8.32 0 0 0 7.913 24c4.27-.039 8.37-1.68 11.487-4.6 4.777-4.779 6.15-13.9 2.624-17.424m-4.746 15.3a14.04 14.04 0 0 1-7.845 3.61l-6.32-6.318a14.04 14.04 0 0 1 3.609-7.846 14.04 14.04 0 0 1 7.846-3.608l6.318 6.318a14.04 14.04 0 0 1-3.608 7.846zm.283-5.717a1.5 1.5 0 0 1-2.122 0l-.44-.438-.878.88.44.438a1.5 1.5 0 1 1-2.122 2.122l-.44-.44-.878.88.44.438a1.5 1.5 0 1 1-2.122 2.122l-3-3a1.5 1.5 0 0 1 2.122-2.122l.439.44.879-.879-.44-.439a1.5 1.5 0 0 1 2.122-2.122l.439.44.879-.879-.44-.439a1.5 1.5 0 1 1 2.122-2.122l3 3a1.5 1.5 0 0 1 0 2.122z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
