/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-disk',
   styleUrl: './crai-icon-disk.css',
   shadow: true,
   })
export class CraiIconDisk {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m22.682 4.333-3.015-3.014a4.47 4.47 0 0 0-3.182-1.32H4.5A4.505 4.505 0 0 0 0 4.5v15A4.505 4.505 0 0 0 4.5 24h15a4.505 4.505 0 0 0 4.5-4.5V7.516a4.47 4.47 0 0 0-1.318-3.182M21 19.5a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 19.5v-15A1.5 1.5 0 0 1 4.5 3H6a4 4 0 0 0 4 4h3a4 4 0 0 0 3.991-3.907c.208.072.397.19.554.346l3.016 3.016c.282.28.44.662.439 1.06z"/><path d="M12 18a4 4 0 1 0 0-8 4 4 0 0 0 0 8"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
