/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-medicine',
   styleUrl: './crai-icon-medicine.css',
   shadow: true,
   })
export class CraiIconMedicine {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M16 6.522V5q.001-.025-.005-.05A2.5 2.5 0 0 0 15.5 0h-7a2.5 2.5 0 0 0-.495 4.95Q7.999 4.975 8 5v1.522A5.51 5.51 0 0 0 3 12v6.5A5.506 5.506 0 0 0 8.5 24h7a5.506 5.506 0 0 0 5.5-5.5V12a5.51 5.51 0 0 0-5-5.478M18 18.5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 6 18.5V12a2.5 2.5 0 0 1 2.5-2.5h1A1.5 1.5 0 0 0 11 8V5h2v3a1.5 1.5 0 0 0 1.5 1.5h1A2.5 2.5 0 0 1 18 12zM16 15a1.5 1.5 0 0 1-1.5 1.5h-1v1a1.5 1.5 0 1 1-3 0v-1h-1a1.5 1.5 0 1 1 0-3h1v-1a1.5 1.5 0 1 1 3 0v1h1A1.5 1.5 0 0 1 16 15"/></svg>
        </Host>
    );
  }
}
