/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-camera',
   styleUrl: './crai-icon-camera.css',
   shadow: true,
   })
export class CraiIconCamera {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.738 4.012 16.245.779A2 2 0 0 0 14.661 0H9.339a2 2 0 0 0-1.583.779L5.262 4.012A5.5 5.5 0 0 0 0 9.5v9A5.506 5.506 0 0 0 5.5 24h13a5.506 5.506 0 0 0 5.5-5.5v-9a5.5 5.5 0 0 0-5.262-5.488M21 18.5a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 18.5v-9A2.5 2.5 0 0 1 5.5 7h13A2.5 2.5 0 0 1 21 9.5z"/><path d="M12 8.5a5.5 5.5 0 1 0 5.5 5.5A5.506 5.506 0 0 0 12 8.5m0 8a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
