/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-time-fast',
   styleUrl: './crai-icon-time-fast.css',
   shadow: true,
   })
export class CraiIconTimeFast {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M9.5 24h-8a1.5 1.5 0 1 1 0-3h8a1.5 1.5 0 1 1 0 3m-2-5h-6a1.5 1.5 0 1 1 0-3h6a1.5 1.5 0 1 1 0 3m-2-5h-4a1.5 1.5 0 1 1 0-3h4a1.5 1.5 0 1 1 0 3"/><path d="M14.5 23.721a1.5 1.5 0 0 1-.354-2.958A9.022 9.022 0 1 0 3.843 8.141a1.5 1.5 0 0 1-2.711-1.284 12.023 12.023 0 1 1 13.723 16.821 1.5 1.5 0 0 1-.355.043"/><path d="M12.5 6A1.5 1.5 0 0 0 11 7.5v4.293a2 2 0 0 0 .586 1.414L13.38 15a1.5 1.5 0 0 0 2.121-2.121l-1.5-1.5V7.5A1.5 1.5 0 0 0 12.5 6"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
