/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-layers',
   styleUrl: './crai-icon-layers.css',
   shadow: true,
   })
export class CraiIconLayers {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="m.912 10.6 9.288 5.57a3.49 3.49 0 0 0 3.6 0l9.288-5.57a1.86 1.86 0 0 0 0-3.192L13.8 1.831a3.49 3.49 0 0 0-3.6 0L.912 7.401a1.86 1.86 0 0 0 0 3.191zm10.831-6.2a.5.5 0 0 1 .514 0L19.918 9l-7.66 4.6a.5.5 0 0 1-.515 0L4.083 9z"/><path d="M13.286 18.83a2.5 2.5 0 0 1-2.572 0l-8.442-5.064A1.5 1.5 0 0 0 0 15.052a1.5 1.5 0 0 0 .728 1.286L9.17 21.4a5.49 5.49 0 0 0 5.66 0l8.442-5.065a1.5 1.5 0 1 0-1.544-2.57z"/></svg>
        </Host>
    );
  }
}
