/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-indent',
   styleUrl: './crai-icon-indent.css',
   shadow: true,
   })
export class CraiIconIndent {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M22.5 6h-21a1.5 1.5 0 0 1 0-3h21a1.5 1.5 0 0 1 0 3m0 5h-13a1.5 1.5 0 1 1 0-3h13a1.5 1.5 0 0 1 0 3m0 10h-21a1.5 1.5 0 1 1 0-3h21a1.5 1.5 0 1 1 0 3m0-5h-13a1.5 1.5 0 0 1 0-3h13a1.5 1.5 0 1 1 0 3m-20.793-.255 2.974-2.974a1.09 1.09 0 0 0 0-1.542L1.707 8.255A1 1 0 0 0 0 8.963v6.074a1 1 0 0 0 1.707.708"/></svg>
        </Host>
    );
  }
}
