/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-chart-pyramid',
   styleUrl: './crai-icon-chart-pyramid.css',
   shadow: true,
   })
export class CraiIconChartPyramid {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.5 17.672 15.922 2.43a4.38 4.38 0 0 0-7.845 0L.502 17.672a4.38 4.38 0 0 0 3.923 6.33h15.15a4.38 4.38 0 0 0 3.924-6.33m-4.912-3.151H5.413l1.985-3.993h9.208zM12 2.993a1.36 1.36 0 0 1 1.241.77l1.874 3.771H8.886l1.874-3.771c.23-.475.714-.775 1.242-.77m8.753 17.358c-.25.411-.697.66-1.178.657H4.426a1.386 1.386 0 0 1-1.242-2.003l.74-1.49h16.153l.74 1.49c.218.428.194.94-.063 1.346"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
