/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-microphone-alt',
   styleUrl: './crai-icon-microphone-alt.css',
   shadow: true,
   })
export class CraiIconMicrophoneAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.449 16a5.5 5.5 0 0 0-3.925 1.63c-2.28 2.285-5.518 3.4-9.9 3.4h-1.1a.5.5 0 0 1-.484-.325.51.51 0 0 1 .115-.58l.511-.512a9.5 9.5 0 0 0 6.121-2.78l3.834-3.849c.049 0 .1.012.147.014.087 0 .174.006.26.006a6.07 6.07 0 0 0 4.286-1.778l.912-.913a6.08 6.08 0 0 0-.4-8.944A6.213 6.213 0 0 0 10.5 1.9l-.578.58A6.42 6.42 0 0 0 8.069 7.6L4.32 11.356a9.53 9.53 0 0 0-2.771 6.128L1.033 18a3.53 3.53 0 0 0 2.493 6.024h1.1c5.218 0 9.151-1.4 12.023-4.278a2.53 2.53 0 0 1 1.8-.748A2.557 2.557 0 0 1 21 21.56v.966a1.5 1.5 0 1 0 3 0v-.966A5.56 5.56 0 0 0 18.449 16M12.041 4.6l.577-.578A3.42 3.42 0 0 1 15.028 3a2.88 2.88 0 0 1 1.87.663A3.076 3.076 0 0 1 17.1 8.19l-.912.914a3.047 3.047 0 0 1-4.502-.203 3.226 3.226 0 0 1 .355-4.3m-5.6 8.88 2.821-2.83c.045.057.075.122.122.178.33.39.707.737 1.123 1.031l-2.843 2.85a6.54 6.54 0 0 1-2.92 1.7c.3-1.11.886-2.122 1.7-2.935z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
