/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-duplicate',
   styleUrl: './crai-icon-duplicate.css',
   shadow: true,
   })
export class CraiIconDuplicate {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M20.521 1.729A5.5 5.5 0 0 0 16.53 0H13.5a5.507 5.507 0 0 0-5.475 5H7.5A5.506 5.506 0 0 0 2 10.5v8A5.506 5.506 0 0 0 7.5 24h4a5.506 5.506 0 0 0 5.5-5.5v-.525a5.506 5.506 0 0 0 5-5.475V5.47a5.45 5.45 0 0 0-1.479-3.741M14 18.5a2.5 2.5 0 0 1-2.5 2.5h-4A2.5 2.5 0 0 1 5 18.5v-8A2.5 2.5 0 0 1 7.5 8H8v4.5a5.506 5.506 0 0 0 5.5 5.5h.5zm5-6a2.5 2.5 0 0 1-2.5 2.5h-3a2.5 2.5 0 0 1-2.5-2.5v-7A2.5 2.5 0 0 1 13.5 3H16v1a2 2 0 0 0 2 2h1z"/></svg>
        </Host>
    );
  }
}
