/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cake-wedding',
   styleUrl: './crai-icon-cake-wedding.css',
   shadow: true,
   })
export class CraiIconCakeWedding {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 21H22v-3.5a5.5 5.5 0 0 0-3-4.893V11.5a5.5 5.5 0 0 0-2.756-4.759L15.661 3.8a1 1 0 0 0-.981-.8h-.36a1 1 0 0 0-.981.8L12.9 6H11l.5-2a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1l.635 2.542A5.5 5.5 0 0 0 5 11.5v1.107A5.5 5.5 0 0 0 2 17.5V21h-.5a1.5 1.5 0 1 0 0 3h21a1.5 1.5 0 1 0 0-3m-12-12h3a2.5 2.5 0 0 1 2.5 2.5v.5H8v-.5A2.5 2.5 0 0 1 10.5 9M5 17.74a2.34 2.34 0 0 0 1.75-1.876A2.5 2.5 0 0 0 9.375 18 2.49 2.49 0 0 0 12 15.864 2.5 2.5 0 0 0 14.625 18a2.49 2.49 0 0 0 2.625-2.136A2.35 2.35 0 0 0 19 17.738V21H5z"/><path d="M9.5 3a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m5 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
