/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-backpack',
   styleUrl: './crai-icon-backpack.css',
   shadow: true,
   })
export class CraiIconBackpack {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M20 14.141V12a8 8 0 0 0-4-6.916V4a4 4 0 1 0-8 0v1.084A8 8 0 0 0 4 12v2.141A3.99 3.99 0 0 0 1 18v2a4 4 0 0 0 4 4h14a4 4 0 0 0 4-4v-2a3.99 3.99 0 0 0-3-3.859M17 21H7v-.258a5.93 5.93 0 0 1 10 0zm0-4.463a8.9 8.9 0 0 0-10 0V12a5 5 0 1 1 10 0zM15 11.5a1.5 1.5 0 0 1-1.5 1.5h-3a1.5 1.5 0 1 1 0-3h3a1.5 1.5 0 0 1 1.5 1.5"/></svg>
        </Host>
    );
  }
}
