/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-calculator',
   styleUrl: './crai-icon-calculator.css',
   shadow: true,
   })
export class CraiIconCalculator {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 24h-13A5.506 5.506 0 0 1 0 18.5v-13A5.506 5.506 0 0 1 5.5 0h13A5.506 5.506 0 0 1 24 5.5v13a5.506 5.506 0 0 1-5.5 5.5M5.5 3A2.5 2.5 0 0 0 3 5.5v13A2.5 2.5 0 0 0 5.5 21h13a2.5 2.5 0 0 0 2.5-2.5v-13A2.5 2.5 0 0 0 18.5 3zM19 7a2 2 0 0 0-2-2H7a2 2 0 1 0 0 4h10a2 2 0 0 0 2-2M6.5 11.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m5 0a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m-5 4.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m5 0a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m7.5 1.5a1.5 1.5 0 0 0-1.5-1.5h-1a1.5 1.5 0 1 0 0 3h1a1.5 1.5 0 0 0 1.5-1.5m0-4.5a1.5 1.5 0 0 0-1.5-1.5h-1a1.5 1.5 0 1 0 0 3h1A1.5 1.5 0 0 0 19 13"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
