/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-label',
   styleUrl: './crai-icon-label.css',
   shadow: true,
   })
export class CraiIconLabel {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m20.214 4.392-7.48-4.2a1.5 1.5 0 0 0-1.468 0l-7.48 4.2A3.5 3.5 0 0 0 2 7.443V17.5A6.51 6.51 0 0 0 8.5 24h7a6.51 6.51 0 0 0 6.5-6.5V7.443a3.5 3.5 0 0 0-1.786-3.05M19 17.5a3.5 3.5 0 0 1-3.5 3.5h-7A3.5 3.5 0 0 1 5 17.5V7.443a.5.5 0 0 1 .255-.436L12 3.221l6.744 3.786a.5.5 0 0 1 .256.436z"/><path d="M12 11a2 2 0 1 0 0-4 2 2 0 0 0 0 4"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
