/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-time-quarter-to',
   styleUrl: './crai-icon-time-quarter-to.css',
   shadow: true,
   })
export class CraiIconTimeQuarterTo {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 12a12 12 0 0 1-24 0 1.5 1.5 0 0 1 3 0 9 9 0 1 0 9-9 1.5 1.5 0 0 1 0-3 12.013 12.013 0 0 1 12 12M7 12a1.5 1.5 0 0 0 1.5 1.5h2.19a1.99 1.99 0 0 0 2.81-2.81V6.5a1.5 1.5 0 1 0-3 0v4h-2A1.5 1.5 0 0 0 7 12m-.26-7.106a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3M2.913 8.75a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
