/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-pound',
   styleUrl: './crai-icon-pound.css',
   shadow: true,
   })
export class CraiIconPound {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M20.5 21H8.493c.355-.96.526-1.977.507-3v-4h5.5a1.5 1.5 0 1 0 0-3H9V8a5.013 5.013 0 0 1 10-.5 1.5 1.5 0 1 0 3 0C22 3.505 18.262 0 14 0a8.01 8.01 0 0 0-8 8v3H4.5a1.5 1.5 0 1 0 0 3H6v4c0 2.583-.737 3-2.5 3a1.5 1.5 0 1 0 0 3h17a1.5 1.5 0 1 0 0-3"/></svg>
        </Host>
    );
  }
}
