/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-network-cloud',
   styleUrl: './crai-icon-network-cloud.css',
   shadow: true,
   })
export class CraiIconNetworkCloud {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.448 19H15.1a3.5 3.5 0 0 0-1.65-1.649v-3.35c1.045 0 1.935-.01 2.4-.02a5.5 5.5 0 0 0 1.106-.133 5.141 5.141 0 0 0 .155-10.009l-.185-.043c-.056-.013-.14-.033-.129-.009l-.025-.049A6.22 6.22 0 0 0 10.148.065 6.03 6.03 0 0 0 5.14 4.608a5.9 5.9 0 0 0-.124 2.3 3.74 3.74 0 0 0 .822 6.943q.442.114.9.127c.562.013 2.062.022 3.71.022v3.351a3.5 3.5 0 0 0-1.648 1.65H1.448a1.5 1.5 0 1 0 0 3H8.8a3.48 3.48 0 0 0 6.3 0h7.35a1.5 1.5 0 0 0 0-3zM6.583 10.943a.79.79 0 0 1-.549-.522.84.84 0 0 1 .546-.943A2.444 2.444 0 0 0 8.024 6.7a3 3 0 0 1 .026-1.366 3.08 3.08 0 0 1 2.52-2.3q.24-.033.48-.034a3.2 3.2 0 0 1 2.963 1.91 3.05 3.05 0 0 0 2.334 1.823 2.141 2.141 0 0 1-.046 4.18 2.6 2.6 0 0 1-.508.061c-1.548.028-7.719.034-8.977 0a1 1 0 0 1-.233-.03"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
