/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-glasses',
   styleUrl: './crai-icon-glasses.css',
   shadow: true,
   })
export class CraiIconGlasses {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.5 0A4.505 4.505 0 0 0 15 4.5a1.5 1.5 0 1 0 3 0 1.5 1.5 0 1 1 3 0v9.107a5.47 5.47 0 0 0-6.845 1.534 3.94 3.94 0 0 0-4.31 0A5.47 5.47 0 0 0 3 13.607V4.5a1.5 1.5 0 0 1 3 0 1.5 1.5 0 0 0 3 0 4.5 4.5 0 0 0-9 0v14a5.5 5.5 0 0 0 11 0 1 1 0 0 1 2 0 5.5 5.5 0 0 0 11 0v-14A4.505 4.505 0 0 0 19.5 0m-14 21a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5m13 0a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
