/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-tornado',
   styleUrl: './crai-icon-tornado.css',
   shadow: true,
   })
export class CraiIconTornado {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M15 24h-3.5a1.5 1.5 0 1 1 0-3H15a1 1 0 0 0 0-2H7a4 4 0 1 1 0-8h13a1 1 0 0 0 0-2H4.5a4.5 4.5 0 0 1 0-9h18a1.5 1.5 0 0 1 0 3h-18a1.5 1.5 0 0 0 0 3H20a4 4 0 1 1 0 8H7a1 1 0 0 0 0 2h8a4 4 0 1 1 0 8"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
