/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-pyramid',
   styleUrl: './crai-icon-pyramid.css',
   shadow: true,
   })
export class CraiIconPyramid {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.51 24H4.488a4.44 4.44 0 0 1-3.832-2.17 4.5 4.5 0 0 1-.145-4.42L8.022 2.429A4.46 4.46 0 0 1 12 0a4.47 4.47 0 0 1 3.977 2.428l7.52 15A4.508 4.508 0 0 1 19.51 24M10.677 3.808 3.171 18.78a1.5 1.5 0 0 0 .04 1.49 1.47 1.47 0 0 0 1.277.723H19.51a1.5 1.5 0 0 0 1.326-2.2l-7.519-15A1.46 1.46 0 0 0 12 3.006a1.47 1.47 0 0 0-1.323.802"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
