/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-rectangle-horizontal',
   styleUrl: './crai-icon-rectangle-horizontal.css',
   shadow: true,
   })
export class CraiIconRectangleHorizontal {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M18.5 3h-13A5.506 5.506 0 0 0 0 8.5v7A5.506 5.506 0 0 0 5.5 21h13a5.506 5.506 0 0 0 5.5-5.5v-7A5.506 5.506 0 0 0 18.5 3M21 15.5a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 15.5v-7A2.5 2.5 0 0 1 5.5 6h13A2.5 2.5 0 0 1 21 8.5z"/></svg>
        </Host>
    );
  }
}
