/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-head-side-thinking',
   styleUrl: './crai-icon-head-side-thinking.css',
   shadow: true,
   })
export class CraiIconHeadSideThinking {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.882 4.437A11.042 11.042 0 0 0 .39 8.1a10.96 10.96 0 0 0 2 9.641c.378.463.593 1.037.611 1.634v.11A4.513 4.513 0 0 0 7.5 24h5a4.51 4.51 0 0 0 4.256-3.039 5.475 5.475 0 0 0 4.77-4.579l.144-.885A2.456 2.456 0 0 0 24 12.954c0-1.599-2.947-7.072-4.118-8.517m.512 8.063a1.5 1.5 0 0 0-1.48 1.26l-.349 2.14A2.49 2.49 0 0 1 16.1 18h-.6a1.5 1.5 0 0 0-1.5 1.5 1.5 1.5 0 0 1-1.5 1.5h-5A1.51 1.51 0 0 1 6 19.485v-.11A5.65 5.65 0 0 0 4.76 15.9a7.93 7.93 0 0 1-1.475-7.02 8.06 8.06 0 0 1 6.387-5.766q.665-.111 1.34-.114a8.1 8.1 0 0 1 6.5 3.275 32.7 32.7 0 0 1 3.325 6.225zm-4.169-4.449a1.5 1.5 0 0 0-2.043-.57l-.708.4a4 4 0 0 0-.974-.58v-.8a1.5 1.5 0 0 0-3 0v.8c-.35.147-.679.343-.974.583l-.708-.4A1.501 1.501 0 1 0 6.344 10.1l.707.4a4 4 0 0 0-.05.5q.008.255.05.506l-.707.4a1.5 1.5 0 0 0 1.474 2.614l.708-.4c.295.24.623.434.974.58v.8a1.5 1.5 0 0 0 3 0v-.8c.35-.147.679-.343.974-.584l.708.4a1.5 1.5 0 1 0 1.474-2.614l-.707-.4q.042-.249.051-.502a4 4 0 0 0-.05-.506l.706-.4a1.5 1.5 0 0 0 .57-2.043M12 11.001a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
