/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-arrow-down',
   styleUrl: './crai-icon-arrow-down.css',
   shadow: true,
   })
export class CraiIconArrowDown {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M18.427 16.935a1.5 1.5 0 0 0-2.121 0l-2.781 2.779L13.5 1.5A1.5 1.5 0 0 0 12 0a1.5 1.5 0 0 0-1.5 1.5l.023 18.2-2.763-2.765a1.5 1.5 0 0 0-2.121 2.121l3.919 3.919a3.5 3.5 0 0 0 4.949 0l3.92-3.919a1.5 1.5 0 0 0 0-2.121"/></svg>
        </Host>
    );
  }
}
