/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-vector-alt',
   styleUrl: './crai-icon-vector-alt.css',
   shadow: true,
   })
export class CraiIconVectorAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21 15.035V11.5a9 9 0 0 0-4.578-7.836 4.5 4.5 0 0 0-8.844 0A9 9 0 0 0 3 11.5v3.536A3.5 3.5 0 0 0 0 18.5v2A3.5 3.5 0 0 0 3.5 24h2A3.5 3.5 0 0 0 9 20.5v-2a3.5 3.5 0 0 0-3-3.464V11.5a5.99 5.99 0 0 1 2.181-4.623 4.5 4.5 0 0 0 7.638 0A5.99 5.99 0 0 1 18 11.5v3.536a3.5 3.5 0 0 0-3 3.464v2a3.5 3.5 0 0 0 3.5 3.5h2a3.5 3.5 0 0 0 3.5-3.5v-2a3.5 3.5 0 0 0-3-3.464M6 20.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5zM12 6a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m9 14.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
