/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-bank',
   styleUrl: './crai-icon-bank.css',
   shadow: true,
   })
export class CraiIconBank {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 22.5a1.5 1.5 0 0 1-1.5 1.5h-21a1.5 1.5 0 1 1 0-3h21a1.5 1.5 0 0 1 1.5 1.5M.37 9.34A3.03 3.03 0 0 1 .5 6.229a5.1 5.1 0 0 1 1.785-1.67L9.444.653a5.31 5.31 0 0 1 5.112 0l7.16 3.907c.72.403 1.333.975 1.784 1.667a3.03 3.03 0 0 1 .134 3.115A3.13 3.13 0 0 1 21 10.99V16h.5a1.5 1.5 0 0 1 0 3h-19a1.5 1.5 0 1 1 0-3H3v-5.01A3.13 3.13 0 0 1 .37 9.34M6 16h2v-5H6zm5-5v5h2v-5zm7 5v-5h-2v5zM3 7.887A.14.14 0 0 0 3.131 8h17.738A.145.145 0 0 0 21 7.885a2.15 2.15 0 0 0-.721-.693l-7.16-3.906a2.33 2.33 0 0 0-2.236 0L3.722 7.192A2.1 2.1 0 0 0 3 7.887"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
