/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-building',
   styleUrl: './crai-icon-building.css',
   shadow: true,
   })
export class CraiIconBuilding {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 5h-2.525A5.506 5.506 0 0 0 10.5 0h-5A5.506 5.506 0 0 0 0 5.5v13A5.506 5.506 0 0 0 5.5 24h13a5.506 5.506 0 0 0 5.5-5.5v-8A5.506 5.506 0 0 0 18.5 5M3 18.5v-13A2.5 2.5 0 0 1 5.5 3h5A2.5 2.5 0 0 1 13 5.5V21H5.5A2.5 2.5 0 0 1 3 18.5m18 0a2.5 2.5 0 0 1-2.5 2.5H16V8h2.5a2.5 2.5 0 0 1 2.5 2.5zm-1-7a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m0 5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0M7 6.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m0 5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m5-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m0 5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m-5 5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m5 0a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
