/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-hamburger',
   styleUrl: './crai-icon-hamburger.css',
   shadow: true,
   })
export class CraiIconHamburger {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 14a2 2 0 0 0-1-1.723V10.5A10.51 10.51 0 0 0 12.5 0h-1A10.51 10.51 0 0 0 1 10.5v1.777a2 2 0 0 0 0 3.446v.777A7.51 7.51 0 0 0 8.5 24h7a7.51 7.51 0 0 0 7.5-7.5v-.777A1.99 1.99 0 0 0 24 14M11.5 3h1a7.51 7.51 0 0 1 7.5 7.5V12H4v-1.5A7.51 7.51 0 0 1 11.5 3m4 18h-7A4.505 4.505 0 0 1 4 16.5v-.474c1.592.126 2.172.874 3.784 2.273a2.814 2.814 0 0 0 3.716 0C13.818 16.287 13.87 16 17 16h3v.5a4.505 4.505 0 0 1-4.5 4.5M6 8.5a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0m4-2a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
