/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-redo-alt',
   styleUrl: './crai-icon-redo-alt.css',
   shadow: true,
   })
export class CraiIconRedoAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M16.3 15.007a1.5 1.5 0 0 0 2.121 0l4.726-4.725a2.934 2.934 0 0 0 0-4.145l-4.731-4.725a1.5 1.5 0 1 0-2.116 2.12L19.532 6.7H5.319A5.326 5.326 0 0 0 0 12.019v6.68a5.324 5.324 0 0 0 5.318 5.319h13.364a1.5 1.5 0 0 0 0-3H5.318A2.32 2.32 0 0 1 3 18.7v-6.681a2.32 2.32 0 0 1 2.319-2.32h14.159L16.3 12.887a1.5 1.5 0 0 0 0 2.12"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
