/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-map-marker-cross',
   styleUrl: './crai-icon-map-marker-cross.css',
   shadow: true,
   })
export class CraiIconMapMarkerCross {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M8.44 12.439 9.88 11 8.44 9.561a1.5 1.5 0 0 1 2.121-2.122l1.44 1.44 1.438-1.44a1.5 1.5 0 0 1 2.122 2.122L14.121 11l1.44 1.439a1.5 1.5 0 0 1-2.122 2.122L12 13.121l-1.439 1.44a1.5 1.5 0 1 1-2.122-2.122m-4.178 6.455A11.1 11.1 0 0 1 4.22 3.238a10.967 10.967 0 0 1 15.561 0 11.09 11.09 0 0 1 0 15.615l-3.808 3.537A5.706 5.706 0 0 1 8 22.36zm2.084-2.157 3.722 3.454a2.755 2.755 0 0 0 3.833.03l3.8-3.521a8.074 8.074 0 0 0-.044-11.342 7.966 7.966 0 0 0-11.308 0 8.084 8.084 0 0 0-.003 11.379"/></svg>
        </Host>
    );
  }
}
