/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-letter-case',
   styleUrl: './crai-icon-letter-case.css',
   shadow: true,
   })
export class CraiIconLetterCase {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M7.7 5.127a1.5 1.5 0 0 0-2.684 0l-4.856 9.7a1.5 1.5 0 1 0 2.683 1.343L3.435 15h5.848l.585 1.17a1.5 1.5 0 0 0 1.343.83 1.5 1.5 0 0 0 1.344-2.175zM4.935 12l1.424-2.848L7.783 12zM22.5 6.5a1.5 1.5 0 0 0-1.4.978A4.9 4.9 0 0 0 19 7a5 5 0 0 0 0 10 4.95 4.95 0 0 0 2.1-.478A1.5 1.5 0 0 0 24 16V8a1.5 1.5 0 0 0-1.5-1.5M19 14a2 2 0 1 1 0-4.001 2 2 0 0 1 0 4"/></svg>
        </Host>
    );
  }
}
