/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-chart-pie',
   styleUrl: './crai-icon-chart-pie.css',
   shadow: true,
   })
export class CraiIconChartPie {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0a12 12 0 1 0 12 12A12.013 12.013 0 0 0 12 0m8.415 8.836-7.5 1.458c-.044-.085-.093-.167-.131-.255L9.847 3.271a8.94 8.94 0 0 1 10.568 5.565M3 12a9 9 0 0 1 4.094-7.535l2.938 6.768a7.24 7.24 0 0 0 2.237 2.867l5.855 4.481A8.985 8.985 0 0 1 3 12m16.954 4.2-4.394-3.364 5.429-1.055c0 .073.011.145.011.219a8.94 8.94 0 0 1-1.046 4.2"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
