/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-asterik',
   styleUrl: './crai-icon-asterik.css',
   shadow: true,
   })
export class CraiIconAsterik {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M22.874 14.877a3.83 3.83 0 0 0-1.817-2.372l-.883-.5.884-.505a3.82 3.82 0 0 0 1.816-2.372 3.93 3.93 0 0 0-.449-3.043A4.3 4.3 0 0 0 19 4.005a3.9 3.9 0 0 0-2.062.51L16 5.051V4a4 4 0 1 0-8 0v1.051l-.939-.536A3.9 3.9 0 0 0 5.019 4a4.33 4.33 0 0 0-3.448 2.088 3.93 3.93 0 0 0 .223 4.408c.312.409.703.75 1.15 1.004l.883.5-.884.505a3.83 3.83 0 0 0-1.817 2.372 3.93 3.93 0 0 0 .449 3.04 4.28 4.28 0 0 0 3.743 2.075 3.9 3.9 0 0 0 1.744-.507L8 18.949V20a4 4 0 1 0 8 0v-1.051l.939.536A3.9 3.9 0 0 0 19 20a4.32 4.32 0 0 0 3.43-2.083 3.93 3.93 0 0 0 .444-3.04m-3.09 1.609a1.03 1.03 0 0 1-1.357.394l-3.183-1.817A1.5 1.5 0 0 0 13 16.366V20a1 1 0 1 1-2 0v-3.634a1.5 1.5 0 0 0-2.244-1.3L5.574 16.88a1.033 1.033 0 0 1-1.362-.4.98.98 0 0 1 .219-1.37L7.6 13.3a1.5 1.5 0 0 0 0-2.606L4.432 8.891a1.074 1.074 0 0 1-.216-1.377 1.03 1.03 0 0 1 1.357-.394l3.183 1.817A1.5 1.5 0 0 0 11 7.634V4a1 1 0 0 1 2 0v3.634a1.5 1.5 0 0 0 2.244 1.3l3.182-1.814a1.034 1.034 0 0 1 1.363.4 1.06 1.06 0 0 1-.22 1.368L16.4 10.7a1.5 1.5 0 0 0 0 2.606l3.165 1.806a1.037 1.037 0 0 1 .219 1.374"/></svg>
        </Host>
    );
  }
}
