/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-rewind',
   styleUrl: './crai-icon-rewind.css',
   shadow: true,
   })
export class CraiIconRewind {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M10.492 20.81A4.14 4.14 0 0 1 8.038 20L1.7 15.352a4.155 4.155 0 0 1 0-6.7L8.037 4a4.16 4.16 0 0 1 6.436 2.135L17.386 4A4.156 4.156 0 0 1 24 7.352v9.3A4.156 4.156 0 0 1 17.386 20l-2.913-2.135a4.175 4.175 0 0 1-3.981 2.944m-.01-14.62a1.12 1.12 0 0 0-.671.228l-6.338 4.65a1.157 1.157 0 0 0 0 1.865l6.339 4.65a1.157 1.157 0 0 0 1.84-.935v-1.61a1.5 1.5 0 0 1 2.387-1.21l5.12 3.754A1.158 1.158 0 0 0 21 16.648v-9.3a1.158 1.158 0 0 0-1.841-.934l-5.12 3.755a1.5 1.5 0 0 1-2.387-1.21V7.352a1.13 1.13 0 0 0-.633-1.032 1.2 1.2 0 0 0-.537-.13"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
