/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-shop',
   styleUrl: './crai-icon-shop.css',
   shadow: true,
   })
export class CraiIconShop {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m24 10.092-1.249-5.784A5.466 5.466 0 0 0 17.382 0H6.618a5.466 5.466 0 0 0-5.369 4.308L.036 9.766 0 11.046a4.32 4.32 0 0 0 1 2.746V18.5A5.506 5.506 0 0 0 6.5 24h11a5.506 5.506 0 0 0 5.5-5.5v-4.709a4.32 4.32 0 0 0 1-2.745zm-21 .165 1.177-5.3A2.5 2.5 0 0 1 6.618 3H7v1.5a1.5 1.5 0 0 0 3 0V3h4v1.5a1.5 1.5 0 1 0 3 0V3h.382a2.5 2.5 0 0 1 2.441 1.958L21 10.256v.79a1.364 1.364 0 0 1-2.727 0 2.455 2.455 0 1 0-4.909 0 1.364 1.364 0 0 1-2.728 0 2.455 2.455 0 1 0-4.909 0 1.364 1.364 0 0 1-2.727 0zM17.5 21h-11A2.5 2.5 0 0 1 4 18.5v-3.129c.122.011.239.037.364.037a4.37 4.37 0 0 0 3.818-2.253 4.362 4.362 0 0 0 7.636 0 4.37 4.37 0 0 0 3.818 2.253c.125 0 .242-.026.364-.037V18.5a2.5 2.5 0 0 1-2.5 2.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
