/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-life-ring',
   styleUrl: './crai-icon-life-ring.css',
   shadow: true,
   })
export class CraiIconLifeRing {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21.468 19.346a11.92 11.92 0 0 0 0-14.692l1.593-1.593A1.5 1.5 0 1 0 20.939.939l-1.593 1.593a11.92 11.92 0 0 0-14.692 0L3.061.939A1.5 1.5 0 1 0 .939 3.061l1.593 1.593a11.92 11.92 0 0 0 0 14.692L.939 20.939a1.5 1.5 0 1 0 2.122 2.122l1.593-1.593a11.92 11.92 0 0 0 14.692 0l1.593 1.593a1.5 1.5 0 1 0 2.122-2.122zM21 12a8.94 8.94 0 0 1-1.672 5.206l-2.678-2.677a5.12 5.12 0 0 0 0-5.058l2.678-2.677A8.94 8.94 0 0 1 21 12M9.682 12a2.318 2.318 0 1 1 4.636 0 2.318 2.318 0 0 1-4.636 0M12 3c1.867 0 3.688.585 5.206 1.672L14.529 7.35a5.12 5.12 0 0 0-5.058 0L6.794 4.672A8.94 8.94 0 0 1 12 3m-9 9c0-1.867.585-3.688 1.672-5.206L7.35 9.471a5.12 5.12 0 0 0 0 5.058l-2.678 2.677A8.94 8.94 0 0 1 3 12m9 9a8.94 8.94 0 0 1-5.206-1.672l2.677-2.678a5.12 5.12 0 0 0 5.058 0l2.677 2.678A8.94 8.94 0 0 1 12 21"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
