/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-angle-double-small-right',
   styleUrl: './crai-icon-angle-double-small-right.css',
   shadow: true,
   })
export class CraiIconAngleDoubleSmallRight {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M13.1 19.5a1.5 1.5 0 0 1-1.061-2.561l4.586-4.585a.5.5 0 0 0 0-.708l-4.582-4.585a1.5 1.5 0 0 1 2.121-2.122l4.586 4.586a3.505 3.505 0 0 1 0 4.95l-4.586 4.586a1.5 1.5 0 0 1-1.064.439"/><path d="M6.1 19.5a1.5 1.5 0 0 1-1.061-2.561L9.982 12l-4.94-4.939a1.5 1.5 0 1 1 2.122-2.122l6 6a1.5 1.5 0 0 1 0 2.122l-6 6A1.5 1.5 0 0 1 6.1 19.5"/></svg>
        </Host>
    );
  }
}
