/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-dart',
   styleUrl: './crai-icon-dart.css',
   shadow: true,
   })
export class CraiIconDart {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.227 0H17.31a4.74 4.74 0 0 0-3.374 1.4L10.4 4.935A4.8 4.8 0 0 0 9 8.311v3.671c-2.635 1.953-5.642 4.206-6.077 4.641a3.06 3.06 0 0 0-.781 3.114l-1.7 1.7a1.5 1.5 0 0 0 2.122 2.122l1.7-1.7a3.06 3.06 0 0 0 3.113-.78c.435-.435 2.689-3.442 4.642-6.078h3.671a4.74 4.74 0 0 0 3.374-1.4l3.536-3.536A4.8 4.8 0 0 0 24 6.69V4.772A4.78 4.78 0 0 0 19.227 0M21 6.69c-.001.47-.188.92-.519 1.253l-3.538 3.537a1.76 1.76 0 0 1-1.253.52h-1.458l.309-.42 4.02-4.019a1.5 1.5 0 1 0-2.122-2.122l-4.021 4.022-.418.307V8.311c.001-.47.188-.92.519-1.254l3.538-3.537A1.76 1.76 0 0 1 17.31 3h1.917A1.774 1.774 0 0 1 21 4.772z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
