/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-diamond',
   styleUrl: './crai-icon-diamond.css',
   shadow: true,
   })
export class CraiIconDiamond {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.148 5.7 20.28 1.827A4.37 4.37 0 0 0 16.729 0H7.27a4.36 4.36 0 0 0-3.53 1.8L.8 5.721a4.35 4.35 0 0 0 .118 5.2l8.41 11.789A3.39 3.39 0 0 0 12 24a3.42 3.42 0 0 0 2.715-1.35l8.3-11.609a4.365 4.365 0 0 0 .133-5.341M3.227 7.487 6.16 3.571A1.37 1.37 0 0 1 7.27 3h2.39L8.18 8.182l.086.318h7.466l.085-.318L14.338 3h2.39a1.38 1.38 0 0 1 1.126.592l2.879 3.89a1.32 1.32 0 0 1 .22 1.018h-5.22l-3.22 12.075-.193.271A.4.4 0 0 1 12 21a.4.4 0 0 1-.274-.094l-.241-.337L8.267 8.5H3.04a1.3 1.3 0 0 1 .186-1.013"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
