/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cream',
   styleUrl: './crai-icon-cream.css',
   shadow: true,
   })
export class CraiIconCream {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22 11.351v-1.85a3.494 3.494 0 0 0-3.037-3.454 12.7 12.7 0 0 0-1.624-5.64.994.994 0 0 0-1.692.15 3.94 3.94 0 0 1-3.685 2.456H10c-3.08 0-4.26 1.7-4.714 3.01A3.5 3.5 0 0 0 2 9.5v1.851a3.5 3.5 0 0 0-2 3.15v4A5.507 5.507 0 0 0 5.5 24h13a5.507 5.507 0 0 0 5.5-5.5v-4a3.5 3.5 0 0 0-2-3.15M5.5 9.001h13a.5.5 0 0 1 .5.5V11H5V9.5a.5.5 0 0 1 .5-.5M21 18.5a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 18.5v-4a.5.5 0 0 1 .5-.5h17a.5.5 0 0 1 .5.5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
