/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-quote-right',
   styleUrl: './crai-icon-quote-right.css',
   shadow: true,
   })
export class CraiIconQuoteRight {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M8 4H4a4 4 0 0 0-4 4v4a2 2 0 0 0 2 2h5a5.006 5.006 0 0 1-5 5 1.5 1.5 0 1 0 0 3 8.01 8.01 0 0 0 8-8V6a2 2 0 0 0-2-2m14 0h-4a4 4 0 0 0-4 4v4a2 2 0 0 0 2 2h5a5.006 5.006 0 0 1-5 5 1.5 1.5 0 1 0 0 3 8.01 8.01 0 0 0 8-8V6a2 2 0 0 0-2-2"/></svg>
        </Host>
    );
  }
}
