/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-opacity',
   styleUrl: './crai-icon-opacity.css',
   shadow: true,
   })
export class CraiIconOpacity {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M13.24.063a12.2 12.2 0 0 0-3.059.074c-.78.132-1.306.87-1.175 1.651.017.101.077.297.077.297a1.456 1.456 0 0 0 1.63 1.006Q11.353 3.001 12 3v18q-.646 0-1.287-.091a1.456 1.456 0 0 0-1.63 1.006l-.037.126a1.427 1.427 0 0 0 1.121 1.82q.912.138 1.833.139c6.627.007 12.005-5.36 12.012-11.988A12 12 0 0 0 13.24.063M3.006 17.077l-.119.068a1.428 1.428 0 0 0-.461 2.09c.598.79 1.291 1.503 2.063 2.124a1.43 1.43 0 0 0 2.004-.26 6 6 0 0 0 .166-.257 1.434 1.434 0 0 0-.338-1.858 9 9 0 0 1-1.468-1.514 1.434 1.434 0 0 0-1.847-.393M6.659 3.16l-.07-.117a1.43 1.43 0 0 0-2.1-.4 12 12 0 0 0-2.065 2.125 1.43 1.43 0 0 0 .313 1.995c.047.035.263.162.263.162.627.35 1.418.183 1.848-.393.43-.56.923-1.068 1.47-1.514.564-.446.71-1.24.341-1.858M3 12q0-.528.061-1.055a1.43 1.43 0 0 0-1.052-1.568l-.133-.035a1.446 1.446 0 0 0-1.794 1.25 12 12 0 0 0 0 2.82c.083.795.795 1.37 1.589 1.287a5 5 0 0 0 .344-.073 1.43 1.43 0 0 0 1.05-1.567A9 9 0 0 1 3.001 12"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
