/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-forward',
   styleUrl: './crai-icon-forward.css',
   shadow: true,
   })
export class CraiIconForward {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M4.16 20.809A4.17 4.17 0 0 1 0 16.648v-9.3A4.157 4.157 0 0 1 6.615 4l2.912 2.135A4.16 4.16 0 0 1 15.962 4L22.3 8.648a4.156 4.156 0 0 1 0 6.7L15.963 20a4.16 4.16 0 0 1-6.436-2.135L6.615 20a4.14 4.14 0 0 1-2.455.809m6.688-7.272a1.5 1.5 0 0 1 1.5 1.5v1.61a1.157 1.157 0 0 0 1.841.935l6.338-4.65a1.157 1.157 0 0 0 0-1.865l-6.339-4.65a1.157 1.157 0 0 0-1.84.935v1.61a1.5 1.5 0 0 1-2.388 1.21L4.841 6.419A1.158 1.158 0 0 0 3 7.352v9.3a1.158 1.158 0 0 0 1.841.934l5.119-3.76c.258-.188.569-.29.888-.29"/></svg>
        </Host>
    );
  }
}
