/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cube',
   styleUrl: './crai-icon-cube.css',
   shadow: true,
   })
export class CraiIconCube {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.437 4.08 14.665.748a5.35 5.35 0 0 0-5.33 0L3.563 4.08A5.34 5.34 0 0 0 .9 8.7v6.664a5.35 5.35 0 0 0 2.665 4.616l5.772 3.332a5.34 5.34 0 0 0 5.33 0l5.772-3.332a5.35 5.35 0 0 0 2.66-4.621v-6.66a5.34 5.34 0 0 0-2.662-4.62m-9.6-.734a2.34 2.34 0 0 1 2.33 0L18.6 6.484l-5.183 2.994a2.85 2.85 0 0 1-2.834 0L5.4 6.484zm-5.774 14.03A2.34 2.34 0 0 1 3.9 15.36V9.082l5.185 2.993c.444.257.92.453 1.417.584v7.857zm13.874 0-5.437 3.14v-7.857c.496-.13.973-.327 1.417-.584L20.1 9.082v6.277a2.34 2.34 0 0 1-1.163 2.018"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
