/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-marker',
   styleUrl: './crai-icon-marker.css',
   shadow: true,
   })
export class CraiIconMarker {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M12 0A10.513 10.513 0 0 0 1.5 10.5c0 2.826 2.2 6.766 6.541 11.709a5.274 5.274 0 0 0 7.92 0C20.3 17.267 22.5 13.327 22.5 10.5A10.513 10.513 0 0 0 12 0m1.706 20.231a2.33 2.33 0 0 1-3.412 0c-3.683-4.195-5.8-7.742-5.8-9.73a7.5 7.5 0 0 1 15 0c.006 1.988-2.105 5.535-5.788 9.73"/><path d="M12 6.055a4.363 4.363 0 1 0 0 8.726 4.363 4.363 0 0 0 0-8.726m0 5.726a1.363 1.363 0 1 1 0-2.726 1.363 1.363 0 0 1 0 2.726"/></svg>
        </Host>
    );
  }
}
