/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-ice-cream',
   styleUrl: './crai-icon-ice-cream.css',
   shadow: true,
   })
export class CraiIconIceCream {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M16.9 4.032a5.007 5.007 0 0 0-9.8 0 5.787 5.787 0 0 0-4.275 8.7l5.866 9.412a3.91 3.91 0 0 0 6.617.008L21.2 12.7c2.154-3.491-.277-8.383-4.3-8.668M18.981 9.6a97 97 0 0 1-5.47.376L13.5 9.8a2.743 2.743 0 0 1 5.481-.2M12 3a2 2 0 0 1 1.931 1.507 5.8 5.8 0 0 0-1.925 1.409c-.541-.6-1.2-1.08-1.937-1.41A2 2 0 0 1 12 3M7.705 7a2.82 2.82 0 0 1 2.8 2.883l.006.089C8.393 9.9 6.191 9.709 5.019 9.6A2.7 2.7 0 0 1 7.705 7m5.05 13.578a.886.886 0 0 1-1.515-.01l-4.888-7.84c3.759.34 7.541.34 11.3 0z"/></svg>
        </Host>
    );
  }
}
