/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-phone-slash',
   styleUrl: './crai-icon-phone-slash.css',
   shadow: true,
   })
export class CraiIconPhoneSlash {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.934 16.1a3.515 3.515 0 0 1 .082 4.947s-.93 1.066-.954 1.09c-3.44 3.2-7.766 1.85-11.86-.61a1.5 1.5 0 0 1 1.6-2.54c2.935 1.646 5.681 3.044 8.107 1.064 0 0 .924-1.06.949-1.083a.5.5 0 0 0 0-.707l-2.238-2.075c-.3-.25-.469-.252-.747-.04l-1.136 1.119a1.5 1.5 0 0 1-1.588.33q-.27-.099-.532-.213a1.5 1.5 0 0 1 .651-2.88l.492-.485a3.59 3.59 0 0 1 4.941.008zm.627-13.539-21 21A1.5 1.5 0 1 1 .439 21.44L4.88 17c-4-4.7-7.018-10.6-3.018-15.06.025-.026 1.092-.956 1.092-.956a3.583 3.583 0 0 1 4.908.041l2.152 2.318a3.493 3.493 0 0 1-.039 4.91l-.388.393c.383.8.845 1.56 1.381 2.265L21.439.44a1.5 1.5 0 0 1 2.122 2.122M7 14.881l1.827-1.828a16.4 16.4 0 0 1-2.413-4.176 1.5 1.5 0 0 1 .323-1.61l1.108-1.126a.485.485 0 0 0 .009-.717L5.7 3.106a.487.487 0 0 0-.667.04c-.024.025-1.083.954-1.083.954C1.5 7 4.224 11.592 7 14.88"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
