/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-bowling',
   styleUrl: './crai-icon-bowling.css',
   shadow: true,
   })
export class CraiIconBowling {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M16 15.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m1 0a1.5 1.5 0 1 0 2.998 0 1.5 1.5 0 0 0-2.998 0m1-3a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0m6 3a8.489 8.489 0 0 1-13.484 6.874A4.15 4.15 0 0 1 7.25 24h-2.5a4.19 4.19 0 0 1-3.82-2.543A11.6 11.6 0 0 1 0 16.773c.104-1.918.735-3.77 1.825-5.353A6.54 6.54 0 0 0 3 8.5q-.198-1.208-.548-2.38A9.6 9.6 0 0 1 2 4a3.827 3.827 0 0 1 4-4 3.827 3.827 0 0 1 4 4 9.6 9.6 0 0 1-.452 2.12A19 19 0 0 0 9 8.5c.018.415.114.822.285 1.2A8.5 8.5 0 0 1 24 15.5M5 4c.02.117.21.824.349 1.34.172.641.312 1.182.422 1.66h.458c.11-.478.25-1.019.422-1.66.139-.516.329-1.223.349-1.418C7 3.29 6.71 3 6 3s-1 .29-1 1m3.322 16.255A8.6 8.6 0 0 0 9 16.773a7.86 7.86 0 0 0-1.423-3.854A12.7 12.7 0 0 1 6.216 10h-.432a12.7 12.7 0 0 1-1.361 2.92A7.86 7.86 0 0 0 3 16.772a8.6 8.6 0 0 0 .678 3.481 1.18 1.18 0 0 0 1.07.746h2.5a1.18 1.18 0 0 0 1.074-.745M21 15.5a5.491 5.491 0 0 0-10.163-2.895A8.8 8.8 0 0 1 12 16.773a12.5 12.5 0 0 1-.3 2.7A5.493 5.493 0 0 0 21 15.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
