/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-rectabgle-vertical',
   styleUrl: './crai-icon-rectabgle-vertical.css',
   shadow: true,
   })
export class CraiIconRectabgleVertical {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M15.5 0h-7A5.506 5.506 0 0 0 3 5.5v13A5.506 5.506 0 0 0 8.5 24h7a5.506 5.506 0 0 0 5.5-5.5v-13A5.506 5.506 0 0 0 15.5 0M18 18.5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 6 18.5v-13A2.5 2.5 0 0 1 8.5 3h7A2.5 2.5 0 0 1 18 5.5z"/></svg>
        </Host>
    );
  }
}
