/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-inbox',
   styleUrl: './crai-icon-inbox.css',
   shadow: true,
   })
export class CraiIconInbox {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M3.5 5.5h17a1.5 1.5 0 0 1 0 3h-17a1.5 1.5 0 0 1 0-3m0-5h17a1.5 1.5 0 0 1 0 3h-17a1.5 1.5 0 0 1 0-3m15 23h-13A5.506 5.506 0 0 1 0 18v-4a3.5 3.5 0 0 1 3.5-3.5H7A1.5 1.5 0 0 1 8.5 12a2.5 2.5 0 0 0 2.5 2.5h2a2.5 2.5 0 0 0 2.5-2.5 1.5 1.5 0 0 1 1.5-1.5h3.5A3.5 3.5 0 0 1 24 14v4a5.506 5.506 0 0 1-5.5 5.5m-15-10a.5.5 0 0 0-.5.5v4a2.5 2.5 0 0 0 2.5 2.5h13A2.5 2.5 0 0 0 21 18v-4a.5.5 0 0 0-.5-.5h-2.208a5.51 5.51 0 0 1-5.292 4h-2a5.51 5.51 0 0 1-5.292-4z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
