/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-database',
   styleUrl: './crai-icon-database.css',
   shadow: true,
   })
export class CraiIconDatabase {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.562 8.5A4.994 4.994 0 0 0 19 0H5a4.994 4.994 0 0 0-3.562 8.5 4.98 4.98 0 0 0 0 7A4.994 4.994 0 0 0 5 24h14a4.994 4.994 0 0 0 3.562-8.5 4.98 4.98 0 0 0 0-7M5 14a2 2 0 1 1 0-4v.5a1.5 1.5 0 0 0 3 0V10h2v.5a1.5 1.5 0 0 0 3 0V10h6a2 2 0 1 1 0 4zM5 3v.5a1.5 1.5 0 1 0 3 0V3h2v.5a1.5 1.5 0 0 0 3 0V3h6a2 2 0 1 1 0 4H5a2 2 0 1 1 0-4m14 18H5a2 2 0 1 1 0-4v.5a1.5 1.5 0 0 0 3 0V17h2v.5a1.5 1.5 0 0 0 3 0V17h6a2 2 0 1 1 0 4"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
