/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-download',
   styleUrl: './crai-icon-download.css',
   shadow: true,
   })
export class CraiIconDownload {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M8.85 17.7a4.5 4.5 0 0 0 6.365 0l3.212-3.212a1.5 1.5 0 1 0-2.121-2.121l-2.783 2.782L13.5 1.5a1.5 1.5 0 0 0-3 0l.02 13.627-2.76-2.761a1.5 1.5 0 0 0-2.121 2.121z"/><path d="M22.5 14.5A1.5 1.5 0 0 0 21 16v4.591a.41.41 0 0 1-.409.409H3.409A.41.41 0 0 1 3 20.591V16a1.5 1.5 0 0 0-3 0v4.591A3.413 3.413 0 0 0 3.409 24h17.182A3.413 3.413 0 0 0 24 20.591V16a1.5 1.5 0 0 0-1.5-1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
