/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-sign-out-alt',
   styleUrl: './crai-icon-sign-out-alt.css',
   shadow: true,
   })
export class CraiIconSignOutAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M11.5 16a1.5 1.5 0 0 0-1.5 1.5v.8A2.7 2.7 0 0 1 7.3 21H5.7A2.7 2.7 0 0 1 3 18.3V5.7A2.7 2.7 0 0 1 5.7 3h1.6A2.7 2.7 0 0 1 10 5.7v.8a1.5 1.5 0 1 0 3 0v-.8A5.706 5.706 0 0 0 7.3 0H5.7A5.706 5.706 0 0 0 0 5.7v12.6A5.706 5.706 0 0 0 5.7 24h1.6a5.706 5.706 0 0 0 5.7-5.7v-.8a1.5 1.5 0 0 0-1.5-1.5"/><path d="m22.56 9.524-4.585-4.586a1.5 1.5 0 1 0-2.121 2.122l3.41 3.411L7 10.5a1.5 1.5 0 1 0 0 3l12.318-.028-3.467 3.467a1.5 1.5 0 0 0 2.12 2.122l4.587-4.586a3.505 3.505 0 0 0 .003-4.95"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
