/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CraiButton {
    }
}
declare global {
    interface HTMLCraiButtonElement extends Components.CraiButton, HTMLStencilElement {
    }
    var HTMLCraiButtonElement: {
        prototype: HTMLCraiButtonElement;
        new (): HTMLCraiButtonElement;
    };
    interface HTMLElementTagNameMap {
        "crai-button": HTMLCraiButtonElement;
    }
}
declare namespace LocalJSX {
    interface CraiButton {
    }
    interface IntrinsicElements {
        "crai-button": CraiButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "crai-button": LocalJSX.CraiButton & JSXBase.HTMLAttributes<HTMLCraiButtonElement>;
        }
    }
}
