/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-tool-marquee',
   styleUrl: './crai-icon-tool-marquee.css',
   shadow: true,
   })
export class CraiIconToolMarquee {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 24a1.5 1.5 0 1 1 0-3 2.5 2.5 0 0 0 2.5-2.5 1.5 1.5 0 1 1 3 0 5.506 5.506 0 0 1-5.5 5.5M24 5.5A5.506 5.506 0 0 0 18.5 0a1.5 1.5 0 0 0 0 3A2.5 2.5 0 0 1 21 5.5a1.5 1.5 0 1 0 3 0m0 8v-3a1.5 1.5 0 1 0-3 0v3a1.5 1.5 0 1 0 3 0m-17 9A1.5 1.5 0 0 0 5.5 21 2.5 2.5 0 0 1 3 18.5a1.5 1.5 0 0 0-3 0A5.506 5.506 0 0 0 5.5 24 1.5 1.5 0 0 0 7 22.5m-4-17A2.5 2.5 0 0 1 5.5 3a1.5 1.5 0 0 0 0-3A5.506 5.506 0 0 0 0 5.5a1.5 1.5 0 1 0 3 0m0 8v-3a1.5 1.5 0 0 0-3 0v3a1.5 1.5 0 0 0 3 0m12-12A1.5 1.5 0 0 0 13.5 0h-3a1.5 1.5 0 0 0 0 3h3A1.5 1.5 0 0 0 15 1.5m0 21a1.5 1.5 0 0 0-1.5-1.5h-3a1.5 1.5 0 1 0 0 3h3a1.5 1.5 0 0 0 1.5-1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
