/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-book-alt',
   styleUrl: './crai-icon-book-alt.css',
   shadow: true,
   })
export class CraiIconBookAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.024 2.278A5.5 5.5 0 0 0 17.477 1.1l-3.283.688A4.5 4.5 0 0 0 12 2.854a4.4 4.4 0 0 0-2.155-1.062l-3.361-.7A5.5 5.5 0 0 0 0 6.5v9.792A5.49 5.49 0 0 0 4.493 21.7l5.807 1.147a9.4 9.4 0 0 0 1.694.153q.872 0 1.728-.157l5.762-1.143A5.5 5.5 0 0 0 24 16.293V6.5a5.49 5.49 0 0 0-1.976-4.222M10.5 19.829l-5.447-1.076A2.5 2.5 0 0 1 3 16.293V6.5A2.507 2.507 0 0 1 5.494 4q.209 0 .414.037l3.36.7A1.5 1.5 0 0 1 10.5 6.212zM21 16.293a2.506 2.506 0 0 1-2.075 2.464L13.5 19.829V6.212a1.51 1.51 0 0 1 1.27-1.483l3.283-.687A2.5 2.5 0 0 1 21 6.5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
