/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-user-delete',
   styleUrl: './crai-icon-user-delete.css',
   shadow: true,
   })
export class CraiIconUserDelete {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 13h-6a1.5 1.5 0 1 1 0-3h6a1.5 1.5 0 1 1 0 3M14 6A6 6 0 1 0 2 6a6 6 0 0 0 12 0m-3 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0m5 16.5V22a8 8 0 0 0-16 0v.5a1.5 1.5 0 0 0 3 0V22a5 5 0 1 1 10 0v.5a1.5 1.5 0 1 0 3 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
