/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-user-remove',
   styleUrl: './crai-icon-user-remove.css',
   shadow: true,
   })
export class CraiIconUserRemove {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.561 13.439a1.5 1.5 0 0 1-2.122 2.122L20 14.121l-1.439 1.44a1.5 1.5 0 1 1-2.122-2.122L17.879 12l-1.44-1.439a1.5 1.5 0 1 1 2.122-2.122L20 9.879l1.439-1.44a1.5 1.5 0 1 1 2.122 2.122L22.121 12zM2 6a6 6 0 1 1 12 0A6 6 0 0 1 2 6m3 0a3 3 0 1 0 6 0 3 3 0 0 0-6 0m3 8a8.01 8.01 0 0 0-8 8v.5a1.5 1.5 0 0 0 3 0V22a5 5 0 1 1 10 0v.5a1.5 1.5 0 1 0 3 0V22a8.01 8.01 0 0 0-8-8"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
