/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-navigation',
   styleUrl: './crai-icon-navigation.css',
   shadow: true,
   })
export class CraiIconNavigation {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M7.135 14.549c.037.012 1.92.485 1.92.485s.608 1.984.626 2.028a3.075 3.075 0 0 0 2.857 1.915h.05a3.08 3.08 0 0 0 2.846-2.006s2.461-6.554 2.474-6.6A3.5 3.5 0 0 0 13.633 6.1C13.575 6.11 7 8.719 7 8.719a3.1 3.1 0 0 0 .137 5.83zm.96-3.038 6.366-2.528a.5.5 0 0 1 .555.575l-2.391 6.357a.084.084 0 0 1-.084.062c-.045 0-.057-.009-.069-.024l-.795-2.606a1.5 1.5 0 0 0-1.071-1.018l-2.549-.637c-.02-.012-.034-.031-.035-.08-.001-.072.025-.082.078-.101zM12 24A12 12 0 1 0 0 12a12.013 12.013 0 0 0 12 12m0-21a9 9 0 1 1-9 9 9.01 9.01 0 0 1 9-9"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
