/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-croissant',
   styleUrl: './crai-icon-croissant.css',
   shadow: true,
   })
export class CraiIconCroissant {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.258 4.947a11.02 11.02 0 0 0-9.317-3.91A3.3 3.3 0 0 0 13.3.5a3.34 3.34 0 0 0-2.766-.345A15.72 15.72 0 0 0 1.153 8.11C.748 8.91.412 9.743.147 10.6A3.32 3.32 0 0 0 .5 13.337c.154.24.34.46.551.651a11.01 11.01 0 0 0 3.907 9.27 3.2 3.2 0 0 0 2.7.676 3.31 3.31 0 0 0 2.3-1.742l3.21-6.275a4.44 4.44 0 0 0 2.762-2.76l6.257-3.209a3.31 3.31 0 0 0 1.741-2.3 3.2 3.2 0 0 0-.67-2.7M3.015 11.484a12.83 12.83 0 0 1 8.42-8.467.35.35 0 0 1 .282.031.27.27 0 0 1 .132.2l1.316 8.2a1.51 1.51 0 0 1-1.713 1.72l-8.2-1.282a.28.28 0 0 1-.2-.136.3.3 0 0 1-.037-.266m4.278 9.341a.33.33 0 0 1-.224.17.2.2 0 0 1-.182-.039 7.94 7.94 0 0 1-2.846-5.913l5.75.9zM20.824 7.28l-4.888 2.506-.925-5.768a7.93 7.93 0 0 1 5.945 2.853.2.2 0 0 1 .038.183.33.33 0 0 1-.17.226"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
