/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-file-gif',
   styleUrl: './crai-icon-file-gif.css',
   shadow: true,
   })
export class CraiIconFileGif {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.5 0h-15A4.505 4.505 0 0 0 0 4.5v15A4.505 4.505 0 0 0 4.5 24h11.343a5.46 5.46 0 0 0 3.889-1.611l2.657-2.657A5.46 5.46 0 0 0 24 15.843V4.5A4.505 4.505 0 0 0 19.5 0m-6.75 3.125a.625.625 0 0 1 .625-.625h2.013a.625.625 0 1 1 0 1.25H14v1.138h1.239a.625.625 0 1 1 0 1.25H14v1.8a.625.625 0 1 1-1.25 0zm-3 0a.625.625 0 0 1 1.25 0v4.819a.625.625 0 1 1-1.25 0zM4 4.485a1.99 1.99 0 0 1 3.035-1.69c.312.19.567.46.737.784a.626.626 0 0 1-1.11.58A.78.78 0 0 0 6 3.75a.74.74 0 0 0-.749.751v2.067A.74.74 0 0 0 6 7.319a.76.76 0 0 0 .75-.735V6.5H6.5a.5.5 0 1 1 0-1h.75a.75.75 0 0 1 .75.75v.334a2 2 0 0 1-2 1.984 1.99 1.99 0 0 1-2-1.984zM3 19.5V11h18v4h-4a2 2 0 0 0-2 2v4H4.5A1.5 1.5 0 0 1 3 19.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
