/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-thermometer-half',
   styleUrl: './crai-icon-thermometer-half.css',
   shadow: true,
   })
export class CraiIconThermometerHalf {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M15 16.037a2.994 2.994 0 1 1-4.5-2.584V8.037a1.5 1.5 0 0 1 3 0v5.416a2.99 2.99 0 0 1 1.5 2.584M20 16a8.01 8.01 0 0 1-8 8c-6.773.089-10.563-8.262-6-13.271V6.037c.253-7.931 11.75-7.926 12 0v4.692a7.9 7.9 0 0 1 2 5.27m-3 0a4.95 4.95 0 0 0-1.541-3.59A1.5 1.5 0 0 1 15 11.33V6.037a3 3 0 1 0-6 0v5.293a1.5 1.5 0 0 1-.459 1.08A4.994 4.994 0 1 0 17 16"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
