/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-copy',
   styleUrl: './crai-icon-copy.css',
   shadow: true,
   })
export class CraiIconCopy {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M13.5 19h-8A5.506 5.506 0 0 1 0 13.5v-8A5.506 5.506 0 0 1 5.5 0h8A5.506 5.506 0 0 1 19 5.5v8a5.506 5.506 0 0 1-5.5 5.5m-8-16A2.5 2.5 0 0 0 3 5.5v8A2.5 2.5 0 0 0 5.5 16h8a2.5 2.5 0 0 0 2.5-2.5v-8A2.5 2.5 0 0 0 13.5 3zM24 18.5V7a1.5 1.5 0 1 0-3 0v11.5a2.5 2.5 0 0 1-2.5 2.5H7a1.5 1.5 0 1 0 0 3h11.5a5.506 5.506 0 0 0 5.5-5.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
