/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-arrow-from-bottom',
   styleUrl: './crai-icon-arrow-from-bottom.css',
   shadow: true,
   })
export class CraiIconArrowFromBottom {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M17.735 21.016H13.5V4.543l3.185 3.185a1.5 1.5 0 1 0 2.12-2.122l-4.73-4.73a3 3 0 0 0-4.15 0l-4.731 4.73a1.5 1.5 0 1 0 2.12 2.122L10.5 4.479v16.537H6.265a1.5 1.5 0 0 0 0 3h11.47a1.5 1.5 0 1 0 0-3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
