/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-time-forward-ten',
   styleUrl: './crai-icon-time-forward-ten.css',
   shadow: true,
   })
export class CraiIconTimeForwardTen {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20 11a4 4 0 0 0-4 4v5a4 4 0 1 0 8 0v-5a4 4 0 0 0-4-4m1 9a1 1 0 0 1-2 0v-5a1 1 0 1 1 2 0z"/><path d="M22.293 2.707 20.97 4.03A12 12 0 0 0 1.5 17.811a1.5 1.5 0 1 0 2.624-1.455 8.992 8.992 0 0 1 14.71-10.19l-1.127 1.127A1 1 0 0 0 18.414 9H23a1 1 0 0 0 1-1V3.414a1.001 1.001 0 0 0-1.707-.707"/><path d="M12.574 11.114a1.5 1.5 0 0 0-1.635.325l-3.75 3.75a1.5 1.5 0 1 0 2.122 2.122l1.189-1.19V22.5a1.5 1.5 0 1 0 3 0v-10a1.5 1.5 0 0 0-.926-1.386"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
