/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-man-head',
   styleUrl: './crai-icon-man-head.css',
   shadow: true,
   })
export class CraiIconManHead {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M14.5 13a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m7.387-4.933A10.064 10.064 0 0 0 12 0C5.053 0 3 4.582 1.78 7.32A7 7 0 0 1 .745 9.2a1.5 1.5 0 0 0 .64 2.8A17.7 17.7 0 0 0 8.1 10.963a1.5 1.5 0 1 0 1.95-.855 14.2 14.2 0 0 0 3.508-2.547 1.5 1.5 0 1 0-2.122-2.122 12.73 12.73 0 0 1-7.041 3.383l.125-.278C5.68 5.945 7 3 12 3a7.07 7.07 0 0 1 7.049 6.337 1.5 1.5 0 0 0 1.224 1.318.884.884 0 0 1 .727.867.98.98 0 0 1-.292.7 1 1 0 0 1-.7.287h-.173a1.51 1.51 0 0 0-1.538 1A7.18 7.18 0 0 1 12 18a7.63 7.63 0 0 1-6.107-4.057 1.5 1.5 0 0 0-2.786 1.114A9.7 9.7 0 0 0 7 19.417V22.5a1.5 1.5 0 0 0 3 0v-1.768A8 8 0 0 0 12 21a8.4 8.4 0 0 0 2-.274V22.5a1.5 1.5 0 0 0 3 0v-3.045a10.3 10.3 0 0 0 3.719-4.01 3.99 3.99 0 0 0 3.28-3.923 3.88 3.88 0 0 0-2.112-3.455"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
