/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-chat-arrow-grow',
   styleUrl: './crai-icon-chat-arrow-grow.css',
   shadow: true,
   })
export class CraiIconChatArrowGrow {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 21h-17A2.5 2.5 0 0 1 3 18.5v-17a1.5 1.5 0 0 0-3 0v17A5.506 5.506 0 0 0 5.5 24h17a1.5 1.5 0 1 0 0-3"/><path d="M22.5 3.976h-3.086a1 1 0 0 0-.707 1.707l.733.732L15.853 10a.5.5 0 0 1-.708 0l-.17-.17a3.583 3.583 0 0 0-4.95 0l-4.1 4.1a1.5 1.5 0 1 0 2.12 2.121l4.1-4.1a.5.5 0 0 1 .709 0l.17.17a3.585 3.585 0 0 0 4.95 0l3.586-3.585.732.733A1 1 0 0 0 24 8.562V5.476a1.5 1.5 0 0 0-1.5-1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
