/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-angle-small-up',
   styleUrl: './crai-icon-angle-small-up.css',
   shadow: true,
   })
export class CraiIconAngleSmallUp {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="m19.061 13.439-4.586-4.585a3.583 3.583 0 0 0-4.95 0l-4.586 4.585a1.5 1.5 0 0 0 2.122 2.122l4.586-4.586a.5.5 0 0 1 .707 0l4.585 4.586a1.5 1.5 0 1 0 2.122-2.122"/></svg>
        </Host>
    );
  }
}
