/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-volleyball',
   styleUrl: './crai-icon-volleyball.css',
   shadow: true,
   })
export class CraiIconVolleyball {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0a12 12 0 1 0 12 12A12.013 12.013 0 0 0 12 0m8.036 16.029a15.8 15.8 0 0 1-9.464-.562 9.4 9.4 0 0 1 1.674-1.757c1.396.525 2.875.796 4.367.8a12.6 12.6 0 0 0 4.209-.734 9 9 0 0 1-.786 2.253m-7.6-13.007a15.76 15.76 0 0 1 3.492 8.451 9.5 9.5 0 0 1-2.494-.527 12.54 12.54 0 0 0-3.516-7.693A9 9 0 0 1 12 3c.146 0 .288.015.432.022zm8.434 7.485a9.5 9.5 0 0 1-1.952.714A18.8 18.8 0 0 0 16.962 4.5a9 9 0 0 1 3.904 6.007zM6.917 4.58q.7.567 1.283 1.256a18.7 18.7 0 0 0-5.18 5.8A9 9 0 0 1 6.917 4.58M4.211 16.488a15.7 15.7 0 0 1 5.57-8.1c.378.932.605 1.918.673 2.921a12.54 12.54 0 0 0-4.5 7.336 9 9 0 0 1-1.743-2.157m4.531 3.892a9.5 9.5 0 0 1 .441-2.252 18.8 18.8 0 0 0 7.022 1.39c.258 0 .516-.017.774-.027a8.93 8.93 0 0 1-8.237.889"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
