/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-map',
   styleUrl: './crai-icon-map.css',
   shadow: true,
   })
export class CraiIconMap {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m20.469 1.146-.031-.01-2.591-.864a5.34 5.34 0 0 0-3.1-.08L9.44 1.733A2.3 2.3 0 0 1 7.859 1.6l-.5-.23A5.318 5.318 0 0 0 0 6.277V17.8a5.33 5.33 0 0 0 3.822 5.1l2.74.857A5.3 5.3 0 0 0 8.148 24c.478-.01.953-.074 1.416-.192L15.1 22.28a2.3 2.3 0 0 1 1.249.01l2.259.651A4.363 4.363 0 0 0 24 18.701V6.153a5.33 5.33 0 0 0-3.531-5.008M14 3.534V19.47l-4 1.105V4.668zM4.682 20.027A2.33 2.33 0 0 1 3 17.8V6.277a2.29 2.29 0 0 1 1.032-1.929 2.34 2.34 0 0 1 1.3-.4c.282 0 .562.055.823.162L7 4.464v16.288zM21 18.7a1.367 1.367 0 0 1-1.625 1.341L17 19.371V3.152l2.475.823A2.32 2.32 0 0 1 21 6.154z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
