/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CraiButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Button type
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button variant
          * @default 'primary'
         */
        "variant": 'primary' | 'glass';
    }
    interface CraiTextBubble {
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'glass';
    }
}
export interface CraiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCraiButtonElement;
}
declare global {
    interface HTMLCraiButtonElementEventMap {
        "craiClicked": MouseEvent;
    }
    interface HTMLCraiButtonElement extends Components.CraiButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCraiButtonElementEventMap>(type: K, listener: (this: HTMLCraiButtonElement, ev: CraiButtonCustomEvent<HTMLCraiButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCraiButtonElementEventMap>(type: K, listener: (this: HTMLCraiButtonElement, ev: CraiButtonCustomEvent<HTMLCraiButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCraiButtonElement: {
        prototype: HTMLCraiButtonElement;
        new (): HTMLCraiButtonElement;
    };
    interface HTMLCraiTextBubbleElement extends Components.CraiTextBubble, HTMLStencilElement {
    }
    var HTMLCraiTextBubbleElement: {
        prototype: HTMLCraiTextBubbleElement;
        new (): HTMLCraiTextBubbleElement;
    };
    interface HTMLElementTagNameMap {
        "crai-button": HTMLCraiButtonElement;
        "crai-text-bubble": HTMLCraiTextBubbleElement;
    }
}
declare namespace LocalJSX {
    interface CraiButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onCraiClicked"?: (event: CraiButtonCustomEvent<MouseEvent>) => void;
        /**
          * Button type
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button variant
          * @default 'primary'
         */
        "variant"?: 'primary' | 'glass';
    }
    interface CraiTextBubble {
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'glass';
    }
    interface IntrinsicElements {
        "crai-button": CraiButton;
        "crai-text-bubble": CraiTextBubble;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "crai-button": LocalJSX.CraiButton & JSXBase.HTMLAttributes<HTMLCraiButtonElement>;
            "crai-text-bubble": LocalJSX.CraiTextBubble & JSXBase.HTMLAttributes<HTMLCraiTextBubbleElement>;
        }
    }
}
