/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Event } from "@stencil/core";
export { Event } from "@stencil/core";
export namespace Components {
    interface CraiButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Button type
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button variant
          * @default 'primary'
         */
        "variant": 'primary' | 'glass';
    }
    interface CraiTextBubble {
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'glass';
    }
    interface CraiTextInput {
        /**
          * @default 'off'
         */
        "autoCapitalize": 'off' | 'on' | 'sentences' | 'words' | 'characters';
        /**
          * @default 'off'
         */
        "autoComplete": string;
        /**
          * @default 'on'
         */
        "autoCorrect": 'on' | 'off';
        /**
          * @default false
         */
        "autoFocus": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default ''
         */
        "value": string;
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'glass' | 'transparent';
    }
}
export interface CraiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCraiButtonElement;
}
export interface CraiTextInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCraiTextInputElement;
}
declare global {
    interface HTMLCraiButtonElementEventMap {
        "craiClicked": MouseEvent;
    }
    interface HTMLCraiButtonElement extends Components.CraiButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCraiButtonElementEventMap>(type: K, listener: (this: HTMLCraiButtonElement, ev: CraiButtonCustomEvent<HTMLCraiButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCraiButtonElementEventMap>(type: K, listener: (this: HTMLCraiButtonElement, ev: CraiButtonCustomEvent<HTMLCraiButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCraiButtonElement: {
        prototype: HTMLCraiButtonElement;
        new (): HTMLCraiButtonElement;
    };
    interface HTMLCraiTextBubbleElement extends Components.CraiTextBubble, HTMLStencilElement {
    }
    var HTMLCraiTextBubbleElement: {
        prototype: HTMLCraiTextBubbleElement;
        new (): HTMLCraiTextBubbleElement;
    };
    interface HTMLCraiTextInputElementEventMap {
        "craiTextChange": Event;
    }
    interface HTMLCraiTextInputElement extends Components.CraiTextInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCraiTextInputElementEventMap>(type: K, listener: (this: HTMLCraiTextInputElement, ev: CraiTextInputCustomEvent<HTMLCraiTextInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCraiTextInputElementEventMap>(type: K, listener: (this: HTMLCraiTextInputElement, ev: CraiTextInputCustomEvent<HTMLCraiTextInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCraiTextInputElement: {
        prototype: HTMLCraiTextInputElement;
        new (): HTMLCraiTextInputElement;
    };
    interface HTMLElementTagNameMap {
        "crai-button": HTMLCraiButtonElement;
        "crai-text-bubble": HTMLCraiTextBubbleElement;
        "crai-text-input": HTMLCraiTextInputElement;
    }
}
declare namespace LocalJSX {
    interface CraiButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onCraiClicked"?: (event: CraiButtonCustomEvent<MouseEvent>) => void;
        /**
          * Button type
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button variant
          * @default 'primary'
         */
        "variant"?: 'primary' | 'glass';
    }
    interface CraiTextBubble {
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'glass';
    }
    interface CraiTextInput {
        /**
          * @default 'off'
         */
        "autoCapitalize"?: 'off' | 'on' | 'sentences' | 'words' | 'characters';
        /**
          * @default 'off'
         */
        "autoComplete"?: string;
        /**
          * @default 'on'
         */
        "autoCorrect"?: 'on' | 'off';
        /**
          * @default false
         */
        "autoFocus"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onCraiTextChange"?: (event: CraiTextInputCustomEvent<Event>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'glass' | 'transparent';
    }
    interface IntrinsicElements {
        "crai-button": CraiButton;
        "crai-text-bubble": CraiTextBubble;
        "crai-text-input": CraiTextInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "crai-button": LocalJSX.CraiButton & JSXBase.HTMLAttributes<HTMLCraiButtonElement>;
            "crai-text-bubble": LocalJSX.CraiTextBubble & JSXBase.HTMLAttributes<HTMLCraiTextBubbleElement>;
            "crai-text-input": LocalJSX.CraiTextInput & JSXBase.HTMLAttributes<HTMLCraiTextInputElement>;
        }
    }
}
