/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-laptop',
   styleUrl: './crai-icon-laptop.css',
   shadow: true,
   })
export class CraiIconLaptop {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M22 15V8.5A5.506 5.506 0 0 0 16.5 3h-9A5.506 5.506 0 0 0 2 8.5V15a2 2 0 0 0-2 2v1.154A1.847 1.847 0 0 0 1.846 20h20.308A1.847 1.847 0 0 0 24 18.154V17a2 2 0 0 0-2-2m-7.231 1H9.231l-.923-1H5V8.5A2.5 2.5 0 0 1 7.5 6h9A2.5 2.5 0 0 1 19 8.5V15h-3.308z"/></svg>
        </Host>
    );
  }
}
