/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-flower-tulip',
   styleUrl: './crai-icon-flower-tulip.css',
   shadow: true,
   })
export class CraiIconFlowerTulip {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.263 14.76a2.43 2.43 0 0 0-2-.749 12.5 12.5 0 0 0-7.763 3.326v-2.519a6.506 6.506 0 0 0 5-6.318c0-2.973-2.016-5.43-3.987-7.44a3.59 3.59 0 0 0-5.026 0C7.517 3.07 5.5 5.526 5.5 8.5a6.506 6.506 0 0 0 5 6.318v2.52a12.5 12.5 0 0 0-7.763-3.327 2.43 2.43 0 0 0-2 .748 2.67 2.67 0 0 0-.687 2.2c.811 5.673 6.6 7.108 10.56 7.108 5.011.143 12.1-.157 13.34-7.108a2.67 2.67 0 0 0-.687-2.2M8.5 8.5a7.04 7.04 0 0 1 2-4.118V7.5a1.5 1.5 0 1 0 3 0V4.382a7.04 7.04 0 0 1 2 4.118 3.5 3.5 0 0 1-7 0m-5.373 8.577a8.95 8.95 0 0 1 6.561 3.956c-2.319-.133-5.77-.87-6.56-3.956m11.185 3.956a8.96 8.96 0 0 1 6.561-3.956c-.789 3.085-4.242 3.823-6.56 3.956"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
