/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-playing-cards',
   styleUrl: './crai-icon-playing-cards.css',
   shadow: true,
   })
export class CraiIconPlayingCards {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.17 2 14.9.243a5.523 5.523 0 0 0-6.864 3.62L8 4H5.5A5.506 5.506 0 0 0 0 9.5v9A5.506 5.506 0 0 0 5.5 24h5a5.5 5.5 0 0 0 4.268-2.037 5.455 5.455 0 0 0 5.945-3.857L23.8 8.8A5.513 5.513 0 0 0 20.17 2M13 18.5a2.5 2.5 0 0 1-2.5 2.5h-5A2.5 2.5 0 0 1 3 18.5v-9A2.5 2.5 0 0 1 5.5 7h5A2.5 2.5 0 0 1 13 9.5zm7.936-10.6-3.086 9.31a2.49 2.49 0 0 1-1.872 1.734c.011-.147.022-.294.022-.444v-9a5.5 5.5 0 0 0-4.74-5.441 2.48 2.48 0 0 1 2.727-.96l5.268 1.758A2.5 2.5 0 0 1 20.936 7.9M12 13c0 1.45-1.544 3.39-2.714 4.378a1.99 1.99 0 0 1-2.572 0C5.544 16.39 4 14.45 4 13a2 2 0 1 1 4 0 2 2 0 1 1 4 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
