/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-train-side',
   styleUrl: './crai-icon-train-side.css',
   shadow: true,
   })
export class CraiIconTrainSide {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M10 1H1.5a1.5 1.5 0 1 0 0 3h1.48v3H1.5a1.5 1.5 0 1 0 0 3h18.051c.6.954 1.079 1.98 1.425 3.054a1.48 1.48 0 0 1-.224 1.328 1.5 1.5 0 0 1-1.216.617H1.5a1.5 1.5 0 1 0 0 3h18.036a4.502 4.502 0 0 0 4.3-5.842C22.1 6.612 16.788 1 10 1m2 3.226A11.2 11.2 0 0 1 17.077 7H12zM5.98 4H9v3H5.98zM24 21.5a1.5 1.5 0 0 1-1.5 1.5h-21a1.5 1.5 0 1 1 0-3h21a1.5 1.5 0 0 1 1.5 1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
