/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-refresh',
   styleUrl: './crai-icon-refresh.css',
   shadow: true,
   })
export class CraiIconRefresh {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M3.086 10.684a9.006 9.006 0 0 1 14.765-5.532l-1.16 1.16a.996.996 0 0 0 .704 1.702h4.57c.55 0 .996-.447.996-.997v-4.57a.996.996 0 0 0-1.7-.704l-1.296 1.295C15.025-1.366 7.45-.931 3.046 4.009a12 12 0 0 0-2.911 6.24 1.51 1.51 0 0 0 1.47 1.75 1.51 1.51 0 0 0 1.481-1.315M22.394 12a1.51 1.51 0 0 0-1.48 1.315 9.006 9.006 0 0 1-14.766 5.532l1.161-1.16a.997.997 0 0 0-.704-1.702h-4.57a.996.996 0 0 0-.997.997v4.57a.997.997 0 0 0 1.701.704l1.296-1.295c4.939 4.404 12.513 3.97 16.917-.969a12 12 0 0 0 2.913-6.24 1.51 1.51 0 0 0-1.471-1.753"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
