/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-money',
   styleUrl: './crai-icon-money.css',
   shadow: true,
   })
export class CraiIconMoney {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M18.5 21h-13A5.506 5.506 0 0 1 0 15.5v-7A5.506 5.506 0 0 1 5.5 3h13A5.506 5.506 0 0 1 24 8.5v7a5.506 5.506 0 0 1-5.5 5.5M5.5 6A2.5 2.5 0 0 0 3 8.5v7A2.5 2.5 0 0 0 5.5 18h13a2.5 2.5 0 0 0 2.5-2.5v-7A2.5 2.5 0 0 0 18.5 6zm0 1a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M17 8.5a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0M6.561 14.439a1.5 1.5 0 1 0-2.12 2.122 1.5 1.5 0 0 0 2.12-2.122M17 15.5a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0M8.5 12a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/></svg>
        </Host>
    );
  }
}
