/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-mouse',
   styleUrl: './crai-icon-mouse.css',
   shadow: true,
   })
export class CraiIconMouse {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M13.5 3V1.5A1.5 1.5 0 0 0 12 0a1.5 1.5 0 0 0-1.5 1.5V3A7.51 7.51 0 0 0 3 10.5v4.182a9.21 9.21 0 0 0 8.384 9.3A9.01 9.01 0 0 0 21 15v-4.5A7.51 7.51 0 0 0 13.5 3M18 15a6 6 0 0 1-12 0v-4.5A4.505 4.505 0 0 1 10.5 6h3a4.505 4.505 0 0 1 4.5 4.5z"/><path d="M12 8a1.5 1.5 0 0 0-1.5 1.5v2a1.5 1.5 0 1 0 3 0v-2A1.5 1.5 0 0 0 12 8"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
