/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-spa',
   styleUrl: './crai-icon-spa.css',
   shadow: true,
   })
export class CraiIconSpa {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.544 14.01A3.78 3.78 0 0 0 22 11c0-2.379-1.942-4-5.452-4.662A3.8 3.8 0 0 0 17 4.5C17 1.767 14.448 0 10.5 0S4 1.767 4 4.5a3.8 3.8 0 0 0 1.264 2.865A4.01 4.01 0 0 0 3 11a3.84 3.84 0 0 0 1.132 2.783C1.8 14.5 0 15.863 0 18.5 0 24 7.806 24 12 24s12 0 12-5.5c0-2.377-1.461-3.724-3.456-4.49M19 11c0 .97-2.278 2-6.5 2-3.949 0-6.5-.785-6.5-2s2.551-2 6.5-2c4.222 0 6.5 1.03 6.5 2m-8.5-8c1.686 0 3.5.469 3.5 1.5S12.186 6 10.5 6 7 5.531 7 4.5 8.814 3 10.5 3M12 21c-6.224 0-9-.771-9-2.5S5.776 16 12 16s9 .771 9 2.5-2.775 2.5-9 2.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
