/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-incognito',
   styleUrl: './crai-icon-incognito.css',
   shadow: true,
   })
export class CraiIconIncognito {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.847 7.1C19.033.6 15.009.016 14.963.011q-.09-.01-.179-.011a5.2 5.2 0 0 0-2.828.988A4.8 4.8 0 0 0 9.212 0a2 2 0 0 0-.177.011C8.99.016 4.967.6 4.153 7.1 2.724 7.563 0 8.708 0 10.714 0 14.669 6.194 15 12 15s12-.331 12-4.286c0-2.006-2.724-3.151-4.153-3.614M7 10.336V9.5c0-5.061 1.843-6.245 2.358-6.477.279.055.542.172.769.343a3.076 3.076 0 0 0 3.746 0 1.9 1.9 0 0 1 .767-.344C15.152 3.252 17 4.434 17 9.5v.836c-1.626.463-3.31.686-5 .664a17.4 17.4 0 0 1-5-.664M21 20a3.99 3.99 0 0 1-7.8 1.193A5.8 5.8 0 0 0 12 21a5.8 5.8 0 0 0-1.2.193 4 4 0 1 1-.259-3.018Q11.262 18.016 12 18q.739.016 1.461.175A3.987 3.987 0 0 1 21 20"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
