/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-spinner',
   styleUrl: './crai-icon-spinner.css',
   shadow: true,
   })
export class CraiIconSpinner {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12.566 24C5.94 23.998.568 18.624.57 11.997.571 5.369 5.945-.002 12.572 0A12 12 0 0 1 23.28 6.589a1.5 1.5 0 0 1-2.676 1.355 9 9 0 1 0-.01 8.133 1.5 1.5 0 1 1 2.673 1.361A11.96 11.96 0 0 1 12.567 24"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
