/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-sign-in',
   styleUrl: './crai-icon-sign-in.css',
   shadow: true,
   })
export class CraiIconSignIn {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M8.001 21h-4.59a.41.41 0 0 1-.41-.409V3.409A.41.41 0 0 1 3.411 3H8a1.5 1.5 0 0 0 0-3H3.41A3.413 3.413 0 0 0 0 3.409v17.182A3.413 3.413 0 0 0 3.411 24H8a1.5 1.5 0 0 0 0-3"/><path d="m22.501 10.5-13.64.028 3.466-3.466a1.5 1.5 0 1 0-2.12-2.122l-3.88 3.879a4.5 4.5 0 0 0 0 6.364l3.88 3.879a1.5 1.5 0 1 0 2.12-2.122l-3.413-3.412 13.587-.027a1.5 1.5 0 1 0-.006-3z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
