/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-video-camera',
   styleUrl: './crai-icon-video-camera.css',
   shadow: true,
   })
export class CraiIconVideoCamera {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.412 8.7a2.64 2.64 0 0 0-2.516.408l-1.085.808A5.34 5.34 0 0 0 14.725 6.1l-4.579-4.575A3.5 3.5 0 0 0 7.672.5H1.5A1.5 1.5 0 0 0 0 2a1.5 1.5 0 0 0 1.5 1.5h6.172a.5.5 0 0 1 .354.146L10.38 6H5.318A5.32 5.32 0 0 0 0 11.319v7.364A5.32 5.32 0 0 0 5.318 24h8.364a5.33 5.33 0 0 0 5.129-3.913l1.2.89a2.5 2.5 0 0 0 1.492.5A2.53 2.53 0 0 0 22.969 21 2.62 2.62 0 0 0 24 18.85v-7.823A2.49 2.49 0 0 0 22.412 8.7M16 18.684A2.32 2.32 0 0 1 13.682 21H5.318A2.32 2.32 0 0 1 3 18.683v-7.364A2.32 2.32 0 0 1 5.318 9h8.364A2.32 2.32 0 0 1 16 11.319z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
