/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-tree',
   styleUrl: './crai-icon-tree.css',
   shadow: true,
   })
export class CraiIconTree {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m20.4 16.67-.015-.02-1.115-1.56q.28-.287.468-.642a2.87 2.87 0 0 0-.271-3.018L17.94 9.36a2.8 2.8 0 0 0 1.054-2.388 2.75 2.75 0 0 0-.523-1.416C18.432 5.5 14.2.99 14.2.99A2.97 2.97 0 0 0 9.827.956s-4.26 4.544-4.3 4.6a2.75 2.75 0 0 0-.218 2.894c.184.356.443.669.758.916l-1.53 2.1a2.8 2.8 0 0 0-.225 2.934q.199.377.5.678L3.6 16.67A3.4 3.4 0 0 0 6.4 22h4.1v.5a1.5 1.5 0 0 0 3 0V22h4.1a3.4 3.4 0 0 0 2.8-5.33m-2.445 2.116A.38.38 0 0 1 17.6 19H6.4a.38.38 0 0 1-.354-.214.36.36 0 0 1-.014-.359L7.872 16H11.5a1.5 1.5 0 1 0 0-3H7.133l2.183-3H10.5a1.5 1.5 0 1 0 0-3H8.266l3.719-3.99L15.73 7h-.284a1.5 1.5 0 0 0-1.21 2.388L16.89 13a1.5 1.5 0 0 0-1.11 2.37l2.152 3.006a.38.38 0 0 1 .02.41z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
