/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-stethoscope',
   styleUrl: './crai-icon-stethoscope.css',
   shadow: true,
   })
export class CraiIconStethoscope {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 9.5a3.5 3.5 0 1 0-5 3.149V16a5 5 0 1 1-10 0v-.151A7.51 7.51 0 0 0 15 8.5v-3A5.506 5.506 0 0 0 9.5 0a1.5 1.5 0 1 0 0 3A2.5 2.5 0 0 1 12 5.5v3a4.5 4.5 0 1 1-9 0v-3A2.5 2.5 0 0 1 5.5 3a1.5 1.5 0 0 0 0-3A5.506 5.506 0 0 0 0 5.5v3a7.51 7.51 0 0 0 6 7.349V16a8 8 0 0 0 16 0v-3.351A3.5 3.5 0 0 0 24 9.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
