/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-user-add',
   styleUrl: './crai-icon-user-add.css',
   shadow: true,
   })
export class CraiIconUserAdd {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M7.453 14.017A8.19 8.19 0 0 0 0 22.282v.217a1.5 1.5 0 1 0 3 0v-.277a5.153 5.153 0 0 1 4.5-5.2A5.006 5.006 0 0 1 13 22v.5a1.5 1.5 0 0 0 3 0V22a8.01 8.01 0 0 0-8.548-7.982M8 12a6 6 0 1 0-6-6 6.006 6.006 0 0 0 6 6m0-9a3 3 0 1 1 0 6 3 3 0 0 1 0-6m14.5 7H21V8.5a1.5 1.5 0 0 0-3 0V10h-1.5a1.5 1.5 0 0 0 0 3H18v1.5a1.5 1.5 0 0 0 3 0V13h1.5a1.5 1.5 0 0 0 0-3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
