/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-heart-arrow',
   styleUrl: './crai-icon-heart-arrow.css',
   shadow: true,
   })
export class CraiIconHeartArrow {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m22.293 17.715-1.229 1.229-2.315-2.315C20.853 14.2 22 11.885 22 9.9A5.717 5.717 0 0 0 16.5 4a5.32 5.32 0 0 0-4 1.854A5.32 5.32 0 0 0 8.5 4a5.2 5.2 0 0 0-1.978.4L2.561.44A1.5 1.5 0 1 0 .439 2.56l3.724 3.723A6.14 6.14 0 0 0 3 9.9c0 2.886 2.371 6.463 6.676 10.073a4.39 4.39 0 0 0 5.648 0c.473-.4.913-.793 1.339-1.187l2.28 2.28-1.229 1.229A1 1 0 0 0 18.423 24L23 23.99a1 1 0 0 0 1-1v-4.568a1 1 0 0 0-1.707-.707m-8.9-.043a1.414 1.414 0 0 1-1.792 0C7.472 14.21 6 11.387 6 9.9A2.726 2.726 0 0 1 8.5 7 2.726 2.726 0 0 1 11 9.9a1.5 1.5 0 1 0 3 0A2.725 2.725 0 0 1 16.5 7 2.725 2.725 0 0 1 19 9.9c0 1.486-1.472 4.309-5.6 7.772z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
