/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-file-delete',
   styleUrl: './crai-icon-file-delete.css',
   shadow: true,
   })
export class CraiIconFileDelete {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M15.56 13.561 14.12 15l1.44 1.439a1.5 1.5 0 0 1-2.121 2.122l-1.44-1.44-1.438 1.44a1.5 1.5 0 0 1-2.122-2.122L9.879 15l-1.44-1.439a1.5 1.5 0 1 1 2.122-2.122L12 12.879l1.439-1.44a1.5 1.5 0 0 1 2.122 2.122M22 8.157V18.5a5.506 5.506 0 0 1-5.5 5.5h-9A5.506 5.506 0 0 1 2 18.5v-13A5.506 5.506 0 0 1 7.5 0h6.343a5.46 5.46 0 0 1 3.889 1.611l2.657 2.657a5.46 5.46 0 0 1 1.61 3.889M19 18.5V9h-4a2 2 0 0 1-2-2V3H7.5A2.5 2.5 0 0 0 5 5.5v13A2.5 2.5 0 0 0 7.5 21h9a2.5 2.5 0 0 0 2.5-2.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
