/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cupcake',
   styleUrl: './crai-icon-cupcake.css',
   shadow: true,
   })
export class CraiIconCupcake {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23.585 11.075a12.8 12.8 0 0 0-9.939-7.919 1.991 1.991 0 1 0-3.303 0 12.8 12.8 0 0 0-9.936 7.92 4.34 4.34 0 0 0 .256 4.136 3.83 3.83 0 0 0 2.096 1.567l.606 3.132a4.985 4.985 0 0 0 4.887 4.037h7.485a4.99 4.99 0 0 0 4.888-4.034l.605-3.13a3.82 3.82 0 0 0 2.098-1.573 4.34 4.34 0 0 0 .257-4.136m-5.893 8.272a1.99 1.99 0 0 1-1.955 1.614H8.252a1.99 1.99 0 0 1-1.955-1.614l-.266-1.373a3.45 3.45 0 0 0 1.98-.639 3.5 3.5 0 0 0 3.983 0 3.5 3.5 0 0 0 3.983 0c.578.412 1.27.635 1.98.64zm3.133-5.766a.96.96 0 0 1-.866.41 2.09 2.09 0 0 0-1.601.809.513.513 0 0 1-.78 0 1.996 1.996 0 0 0-3.203 0 .513.513 0 0 1-.779 0 2 2 0 0 0-3.205 0 .51.51 0 0 1-.776 0 2.002 2.002 0 0 0-3.206 0 .51.51 0 0 1-.777 0 2.12 2.12 0 0 0-1.603-.808.96.96 0 0 1-.863-.41 1.4 1.4 0 0 1-.028-1.294c3.529-8.348 14.205-8.326 17.714 0 .205.41.195.893-.027 1.293"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
