/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-envelope-ban',
   styleUrl: './crai-icon-envelope-ban.css',
   shadow: true,
   })
export class CraiIconEnvelopeBan {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 15.5v3a5.506 5.506 0 0 1-5.5 5.5h-13A5.506 5.506 0 0 1 0 18.5v-10A5.506 5.506 0 0 1 5.5 3h2a1.5 1.5 0 0 1 0 3h-2a2.49 2.49 0 0 0-2.2 1.336l6.931 6.932a2.55 2.55 0 0 0 2.979.42 1.5 1.5 0 1 1 1.455 2.624 5.52 5.52 0 0 1-6.555-.922L3 11.278V18.5A2.5 2.5 0 0 0 5.5 21h13a2.5 2.5 0 0 0 2.5-2.5v-3a1.5 1.5 0 1 1 3 0m-13-9A6.51 6.51 0 0 1 17.5 0c8.6.305 8.6 12.7 0 13A6.51 6.51 0 0 1 11 6.5m10 0a3.5 3.5 0 0 0-.214-1.164l-4.45 4.45A3.5 3.5 0 0 0 21 6.5m-7 0c.004.397.076.791.214 1.164l4.45-4.45A3.5 3.5 0 0 0 14 6.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
