/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-compress-alt',
   styleUrl: './crai-icon-compress-alt.css',
   shadow: true,
   })
export class CraiIconCompressAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m7.293 2.091-1.54 1.541L2.56.44A1.5 1.5 0 0 0 .439 2.56l3.193 3.193-1.541 1.54A1 1 0 0 0 2.8 9h4.764A1.436 1.436 0 0 0 9 7.564V2.8a1 1 0 0 0-1.707-.709m9.414 19.818 1.54-1.541 3.193 3.193a1.5 1.5 0 1 0 2.121-2.121l-3.193-3.193 1.541-1.54A1 1 0 0 0 21.2 15h-4.764A1.436 1.436 0 0 0 15 16.436V21.2a1 1 0 0 0 1.707.709M2.091 16.707l1.541 1.54L.439 21.44a1.5 1.5 0 1 0 2.121 2.121l3.193-3.193 1.54 1.541A1 1 0 0 0 9 21.2v-4.764A1.436 1.436 0 0 0 7.564 15H2.8a1 1 0 0 0-.709 1.707m19.818-9.414-1.541-1.54 3.193-3.193A1.5 1.5 0 1 0 21.44.439l-3.193 3.193-1.54-1.541A1 1 0 0 0 15 2.8v4.764A1.436 1.436 0 0 0 16.436 9H21.2a1 1 0 0 0 .709-1.707"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
