/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-search',
   styleUrl: './crai-icon-search.css',
   shadow: true,
   })
export class CraiIconSearch {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="m23.561 21.445-4.645-4.647c3.476-4.644 2.528-11.227-2.117-14.703S5.572-.433 2.096 4.212-.432 15.439 4.213 18.915a10.5 10.5 0 0 0 12.586 0l4.647 4.647a1.495 1.495 0 1 0 2.115-2.115zm-13.016-3.427a7.474 7.474 0 1 1 7.474-7.474 7.48 7.48 0 0 1-7.474 7.474"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
