/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-shopping-cart-check',
   styleUrl: './crai-icon-shopping-cart-check.css',
   shadow: true,
   })
export class CraiIconShoppingCartCheck {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M7 24a2 2 0 1 0 0-4 2 2 0 0 0 0 4m10 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4m2.75-10.837A2.5 2.5 0 0 1 17.34 15H7.217a.33.33 0 0 1-.325-.3L6.036 8H9.5a1.5 1.5 0 0 0 0-3H5.653l-.262-2.061A3.327 3.327 0 0 0 2.087 0H1.5a1.5 1.5 0 0 0 0 3h.587a.33.33 0 0 1 .325.3l1.5 11.76A3.327 3.327 0 0 0 7.217 18h10.122a5.5 5.5 0 0 0 5.3-4.042l.016-.06a1.5 1.5 0 0 0-2.888-.798z"/><path d="M21.413 2.486 17.119 6.78l-.851-.88a1.5 1.5 0 0 0-2.163 2.078l1.263 1.314a2.4 2.4 0 0 0 1.7.754h.04a2.4 2.4 0 0 0 1.69-.7l4.735-4.735a1.5 1.5 0 1 0-2.121-2.12z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
