/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-music',
   styleUrl: './crai-icon-music.css',
   shadow: true,
   })
export class CraiIconMusic {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 1h-5A5.506 5.506 0 0 0 8 6.5v6.107A5.5 5.5 0 1 0 10.975 18H11V6.5A2.5 2.5 0 0 1 13.5 4h5A2.5 2.5 0 0 1 21 6.5v6.107A5.5 5.5 0 1 0 23.975 18H24V6.5A5.506 5.506 0 0 0 18.5 1m-13 19a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5m13 0a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
