/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-caret-right',
   styleUrl: './crai-icon-caret-right.css',
   shadow: true,
   })
export class CraiIconCaretRight {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M9 17.879V6.707A1 1 0 0 1 10.707 6l5.586 5.586a1 1 0 0 1 0 1.414l-5.586 5.586A1 1 0 0 1 9 17.879"/></svg>
        </Host>
    );
  }
}
