/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-apps-sort',
   styleUrl: './crai-icon-apps-sort.css',
   shadow: true,
   })
export class CraiIconAppsSort {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M5.707 0a5.5 5.5 0 1 0 0 11 5.5 5.5 0 0 0 0-11m0 8a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5m0 5a5.5 5.5 0 1 0 0 11 5.5 5.5 0 0 0 0-11m0 8a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5m17.086-2.586h-2.086V5.586h2.086a1 1 0 0 0 .707-1.707L19.914.293a1 1 0 0 0-1.414 0l-3.586 3.586a1 1 0 0 0 .707 1.707h2.086v12.828h-2.086a1 1 0 0 0-.707 1.707l3.586 3.586a1 1 0 0 0 1.414 0l3.586-3.586a1 1 0 0 0-.707-1.707"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
