/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-balloons',
   styleUrl: './crai-icon-balloons.css',
   shadow: true,
   })
export class CraiIconBalloons {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M5.154 16.83A2 2 0 0 0 5 17.6c0 1.866 1.738 2.641 2.889 3.154q.53.224 1.027.512a6 6 0 0 1-.247.394 1.5 1.5 0 1 0 2.49 1.674 3.96 3.96 0 0 0 .84-2.161c0-1.866-1.737-2.642-2.888-3.155q-.498-.211-.971-.476a9 9 0 0 1 .249-.387 7.85 7.85 0 0 0 4.6-4.186 6.9 6.9 0 0 0 3.156 3.058c-.612 2.546 1.12 3.724 2.043 4.348.98.664.98.664.6 1.506a1.499 1.499 0 0 0 2.179 1.88 1.5 1.5 0 0 0 .554-.642c1.423-3.147-.654-4.553-1.652-5.229-.928-.628-1.13-.775-.564-1.857C22.07 14.89 24 10.881 24 7.227A6.067 6.067 0 0 0 17.728.955a6.2 6.2 0 0 0-4.694 1.988A7.218 7.218 0 0 0 0 7.227c0 3.835 2.135 8.173 5.154 9.603M17.728 3.955A3.1 3.1 0 0 1 21 7.227c0 3.161-1.844 6.137-3.272 6.137s-3.274-2.976-3.274-6.137a3.1 3.1 0 0 1 3.274-3.272M7.228 3a4.23 4.23 0 0 1 4.226 4.227c0 3.314-2.252 7.091-4.226 7.091S3 10.541 3 7.227A4.23 4.23 0 0 1 7.228 3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
