/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-time-check',
   styleUrl: './crai-icon-time-check.css',
   shadow: true,
   })
export class CraiIconTimeCheck {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M9.856 20.743A9 9 0 1 1 21 12a1.5 1.5 0 0 0 3 0A12 12 0 1 0 9.144 23.657q.175.043.356.043a1.5 1.5 0 0 0 .355-2.957z"/><path d="M23.621 15.94a1.5 1.5 0 0 0-2.12 0l-4.786 4.782-2.133-2.26a1.5 1.5 0 1 0-2.163 2.078L15 23.26a2.36 2.36 0 0 0 1.674.74h.037a2.37 2.37 0 0 0 1.661-.687l5.254-5.252a1.5 1.5 0 0 0-.005-2.121M10.5 7.5v3.555l-2.4 1.5a1.5 1.5 0 1 0 1.593 2.543l2.869-1.8a2 2 0 0 0 .938-1.7V7.5a1.5 1.5 0 1 0-3 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
