/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-rhombus',
   styleUrl: './crai-icon-rhombus.css',
   shadow: true,
   })
export class CraiIconRhombus {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 24a5.32 5.32 0 0 1-3.777-1.562l-6.658-6.662a5.34 5.34 0 0 1 0-7.554l6.658-6.659a5.35 5.35 0 0 1 7.554 0l6.658 6.66a5.34 5.34 0 0 1 0 7.553l-6.658 6.66A5.32 5.32 0 0 1 12 23.998m-1.656-3.684a2.345 2.345 0 0 0 3.312 0l6.658-6.658a2.34 2.34 0 0 0 0-3.312l-6.658-6.66a2.345 2.345 0 0 0-3.312 0l-6.658 6.657a2.34 2.34 0 0 0 0 3.312z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
