/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-globe-alt',
   styleUrl: './crai-icon-globe-alt.css',
   shadow: true,
   })
export class CraiIconGlobeAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M13.418 15a7.5 7.5 0 1 0-7.5-7.5 7.51 7.51 0 0 0 7.5 7.5m0-12a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9m10.32 11.556a12.49 12.49 0 0 1-9.32 5.383V21H17.5a1.5 1.5 0 0 1 0 3h-9a1.5 1.5 0 1 1 0-3h2.918v-1.175A12.488 12.488 0 0 1 2.941.681 1.5 1.5 0 1 1 5.454 2.32a9.5 9.5 0 0 0 15.81 10.541 1.5 1.5 0 1 1 2.473 1.7z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
