/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from 'designsystem-core/client';

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type ReactWebComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
import { type CraiButtonCustomEvent } from "designsystem-core";
import { CraiButton as CraiButtonElement } from "designsystem-core/../designsystem-core/components/crai-button.js";
import { MyComponent as MyComponentElement } from "designsystem-core/../designsystem-core/components/my-component.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type CraiButtonEvents = { onCraiClicked: EventName<CraiButtonCustomEvent<MouseEvent>> };

export const CraiButton: StencilReactComponent<CraiButtonElement, CraiButtonEvents> = /*@__PURE__*/ createComponent<CraiButtonElement, CraiButtonEvents>({
    tagName: 'crai-button',
    properties: {},
    hydrateModule: import('designsystem-core/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.CraiButton as ReactWebComponent<CraiButtonElement, CraiButtonEvents>,
    serializeShadowRoot,
});

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    properties: {
        first: 'first',
        middle: 'middle',
        last: 'last'
    },
    hydrateModule: import('designsystem-core/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyComponent as ReactWebComponent<MyComponentElement, MyComponentEvents>,
    serializeShadowRoot,
});
