'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type CraiButtonCustomEvent } from "@crai/designsystem-core";
import { CraiButton as CraiButtonElement, defineCustomElement as defineCraiButton } from "@crai/designsystem-core/../designsystem-core/components/crai-button.js";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "@crai/designsystem-core/../designsystem-core/components/my-component.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type CraiButtonEvents = { onCraiClicked: EventName<CraiButtonCustomEvent<MouseEvent>> };

export const CraiButton: StencilReactComponent<CraiButtonElement, CraiButtonEvents> = /*@__PURE__*/ createComponent<CraiButtonElement, CraiButtonEvents>({
    tagName: 'crai-button',
    elementClass: CraiButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCraiClicked: 'craiClicked' } as CraiButtonEvents,
    defineCustomElement: defineCraiButton
});

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});
