/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-plane',
   styleUrl: './crai-icon-plane.css',
   shadow: true,
   })
export class CraiIconPlane {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20 9h-1.626l-4.06-7.164A3.47 3.47 0 0 0 10.965 0 3.1 3.1 0 0 0 8.55 1.25a3.13 3.13 0 0 0-.487 2.805L9.704 9h-1.58a2.5 2.5 0 0 1-1.77-.732L4.938 6.851a2.91 2.91 0 0 0-3.4-.525A2.8 2.8 0 0 0 .124 8.048a3.03 3.03 0 0 0 .223 2.264s1.635 3.865 1.665 3.917A5.51 5.51 0 0 0 6.787 17h2.668L8.2 19.771a3.13 3.13 0 0 0 2.93 4.23 3.5 3.5 0 0 0 3.019-1.728L17.989 17H20a4 4 0 0 0 0-8m-9.071-5.835c-.005-.017-.03-.165.124-.165h.192a.46.46 0 0 1 .442.281l3.239 5.72h-2.061zM19.999 14h-2.772a1.5 1.5 0 0 0-1.212.617S11.6 20.683 11.57 20.74a.5.5 0 0 1-.44.261c-.16 0-.132-.12-.138-.12l2.154-4.76A1.5 1.5 0 0 0 11.78 14H6.787a2.51 2.51 0 0 1-2.13-1.19L3.2 9.353l1.034 1.035A5.47 5.47 0 0 0 8.123 12H20a1 1 0 1 1 0 2"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
