/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-test',
   styleUrl: './crai-icon-test.css',
   shadow: true,
   })
export class CraiIconTest {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18 17.5a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1 0-3h1a1.5 1.5 0 0 1 1.5 1.5M13.092 14h-2.184A1.5 1.5 0 0 1 8 13.5V10a4 4 0 0 1 8 0v3.5a1.5 1.5 0 0 1-2.908.5M11 10v1h2v-1a1 1 0 1 0-2 0m-.57 5.947-.924.94a1.5 1.5 0 0 0-2.14 2.096s.164.187.19.21a2.756 2.756 0 0 0 3.9-.006l1.116-1.134a1.5 1.5 0 0 0-1.654-2.435 1.5 1.5 0 0 0-.484.329zM22 7.157V18.5a5.506 5.506 0 0 1-5.5 5.5h-9A5.507 5.507 0 0 1 2 18.5v-13A5.507 5.507 0 0 1 7.5 0h7.343a5.46 5.46 0 0 1 3.889 1.61l1.657 1.658a5.47 5.47 0 0 1 1.61 3.889M18.985 7H17a2 2 0 0 1-2-2V3.015C14.947 3.012 7.5 3 7.5 3A2.5 2.5 0 0 0 5 5.5v13A2.5 2.5 0 0 0 7.5 21h9a2.5 2.5 0 0 0 2.5-2.5S18.988 7.053 18.985 7"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
