/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-text',
   styleUrl: './crai-icon-text.css',
   shadow: true,
   })
export class CraiIconText {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 0h-13A5.506 5.506 0 0 0 0 5.5v13A5.506 5.506 0 0 0 5.5 24h13a5.506 5.506 0 0 0 5.5-5.5v-13A5.506 5.506 0 0 0 18.5 0M21 18.5a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 18.5v-13A2.5 2.5 0 0 1 5.5 3h13A2.5 2.5 0 0 1 21 5.5zm-2-10a1.5 1.5 0 1 1-3 0 .5.5 0 0 0-.5-.5h-2v8a1.5 1.5 0 1 1 0 3h-3a1.5 1.5 0 1 1 0-3V8h-2a.5.5 0 0 0-.5.5 1.5 1.5 0 0 1-3 0A3.5 3.5 0 0 1 8.5 5h7A3.5 3.5 0 0 1 19 8.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
