/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-child-head',
   styleUrl: './crai-icon-child-head.css',
   shadow: true,
   })
export class CraiIconChildHead {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.817 14.354A3.96 3.96 0 0 0 24 11.522a3.88 3.88 0 0 0-2.113-3.455 10.093 10.093 0 0 0-19.775 0A3.88 3.88 0 0 0 0 11.522a3.99 3.99 0 0 0 3.281 3.924 9.5 9.5 0 0 0 1.291 1.9 9.9 9.9 0 0 0-2.411 4.892 1.5 1.5 0 0 0 1.213 1.741q.132.021.266.021a1.5 1.5 0 0 0 1.474-1.236 6.95 6.95 0 0 1 1.7-3.435A9.6 9.6 0 0 0 12 21a9.6 9.6 0 0 0 5.19-1.671 6.95 6.95 0 0 1 1.7 3.435 1.5 1.5 0 0 0 2.281 1 1.5 1.5 0 0 0 .668-1.528 9.9 9.9 0 0 0-2.411-4.892 9.5 9.5 0 0 0 1.291-1.9 3.96 3.96 0 0 0 2.098-1.09M20 12.508h-.173a1.514 1.514 0 0 0-1.538 1A7.18 7.18 0 0 1 12 18a7.18 7.18 0 0 1-6.293-4.5 1.5 1.5 0 0 0-1.413-1q-.062-.001-.125.005H3.99a.99.99 0 0 1-.99-.983.884.884 0 0 1 .727-.867 1.5 1.5 0 0 0 1.222-1.318A7.06 7.06 0 0 1 7.51 4.6a4.494 4.494 0 0 0 7.673 3.079 1.499 1.499 0 1 0-2.123-2.118 1.535 1.535 0 0 1-2.121 0A1.5 1.5 0 0 1 12 3a7.07 7.07 0 0 1 7.049 6.337 1.5 1.5 0 0 0 1.224 1.318.885.885 0 0 1 .727.867.98.98 0 0 1-.617.914 1 1 0 0 1-.383.072"/><path d="M9.5 13a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m5 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
