/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-link',
   styleUrl: './crai-icon-link.css',
   shadow: true,
   })
export class CraiIconLink {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M10.41 19.587a4.39 4.39 0 0 1-5.945.35 4.24 4.24 0 0 1-1.44-3.672 4.5 4.5 0 0 1 1.353-2.68l2.877-2.879a1.5 1.5 0 0 0-2.122-2.12l-2.815 2.816A7.63 7.63 0 0 0 .03 16.06a7.257 7.257 0 0 0 12.356 5.794l3.008-3.008a1.5 1.5 0 0 0-2.121-2.121zm10.752-18.12a7.425 7.425 0 0 0-9.72.806l-2.83 2.833a1.5 1.5 0 0 0 2.12 2.121l2.877-2.873a4.384 4.384 0 0 1 5.834-.42 4.26 4.26 0 0 1 .316 6.301l-3.008 3.008a1.5 1.5 0 0 0 2.121 2.122l3.009-3.009a7.264 7.264 0 0 0-.72-10.889"/><path d="m8.611 13.246 4.662-4.662a1.5 1.5 0 1 1 2.121 2.122l-4.661 4.662a1.5 1.5 0 0 1-2.122-2.122"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
