/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-baseball',
   styleUrl: './crai-icon-baseball.css',
   shadow: true,
   })
export class CraiIconBaseball {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0a12 12 0 1 0 12 12A12.013 12.013 0 0 0 12 0m7.231 17.336a7.5 7.5 0 0 1-1.148-1.462 1.494 1.494 0 0 0-1-2.81A8 8 0 0 1 17 12q.004-.536.084-1.068.204.064.416.068a1.5 1.5 0 0 0 .583-2.874 7.5 7.5 0 0 1 1.148-1.462 8.93 8.93 0 0 1 0 10.672M4.769 6.664c.442.438.828.929 1.148 1.462A1.5 1.5 0 0 0 6.5 11q.212-.004.416-.068.08.531.084 1.068a8 8 0 0 1-.083 1.064 1.494 1.494 0 0 0-1 2.81 7.5 7.5 0 0 1-1.148 1.462 8.93 8.93 0 0 1 0-10.672M6.92 19.423a10.4 10.4 0 0 0 1.888-2.573l.217.073a1.501 1.501 0 0 0 .95-2.846l-.182-.06c.133-.664.202-1.34.207-2.017a10.6 10.6 0 0 0-.207-2.017l.182-.06a1.5 1.5 0 0 0-.95-2.846l-.217.073A10.4 10.4 0 0 0 6.92 4.577a8.97 8.97 0 0 1 10.16 0 10.4 10.4 0 0 0-1.888 2.573l-.217-.073a1.5 1.5 0 1 0-.95 2.846l.182.06c-.133.664-.203 1.34-.207 2.017.005.677.074 1.353.207 2.017l-.182.06a1.5 1.5 0 0 0 .95 2.846l.217-.073c.493.95 1.13 1.817 1.888 2.573a8.97 8.97 0 0 1-10.16 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
