/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-zoom-out',
   styleUrl: './crai-icon-zoom-out.css',
   shadow: true,
   })
export class CraiIconZoomOut {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M13.5 9h-6a1.5 1.5 0 0 0 0 3h6a1.5 1.5 0 0 0 0-3"/><path d="m23.562 21.448-4.642-4.644c3.477-4.643 2.53-11.226-2.112-14.704S5.58-.43 2.104 4.212-.428 15.44 4.216 18.916a10.5 10.5 0 0 0 12.588.003l4.645 4.644a1.494 1.494 0 1 0 2.113-2.113zm-13.01-3.426a7.47 7.47 0 1 1 7.471-7.47 7.48 7.48 0 0 1-7.47 7.47"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
