/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cursor',
   styleUrl: './crai-icon-cursor.css',
   shadow: true,
   })
export class CraiIconCursor {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.52 10.9 9.665.848A3.407 3.407 0 0 0 4 3.4v15.1a1.5 1.5 0 0 0 2.52 1.1l3.672-3.4 2.922 6.41a2.554 2.554 0 0 0 4.55-2.32l-2.81-6.12 4.854-.682a1.5 1.5 0 0 0 .811-2.586zm-9.459.77a1.5 1.5 0 0 0-.81.385L7 15.065V3.4a.38.38 0 0 1 .24-.37.45.45 0 0 1 .184-.044c.084 0 .165.03.227.087l8.51 7.881z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
