/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-target',
   styleUrl: './crai-icon-target.css',
   shadow: true,
   })
export class CraiIconTarget {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0a12 12 0 1 0 12 12A12.013 12.013 0 0 0 12 0m1.5 20.865V19.5a1.5 1.5 0 1 0-3 0v1.365A9.01 9.01 0 0 1 3.135 13.5H4.5a1.5 1.5 0 1 0 0-3H3.135A9.01 9.01 0 0 1 10.5 3.135V4.5a1.5 1.5 0 1 0 3 0V3.135a9.01 9.01 0 0 1 7.365 7.365H19.5a1.5 1.5 0 0 0 0 3h1.365a9.01 9.01 0 0 1-7.365 7.365M16 12a1.5 1.5 0 0 1-1.5 1.5h-1v1a1.5 1.5 0 1 1-3 0v-1h-1a1.5 1.5 0 1 1 0-3h1v-1a1.5 1.5 0 1 1 3 0v1h1A1.5 1.5 0 0 1 16 12"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
