/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-woman-head',
   styleUrl: './crai-icon-woman-head.css',
   shadow: true,
   })
export class CraiIconWomanHead {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M14.5 13a1.5 1.5 0 1 1 0-3.001 1.5 1.5 0 0 1 0 3m9.42 4.77A5.318 5.318 0 0 1 18.683 24H15.5a1.5 1.5 0 0 1-1.5-1.5v-1.775A8.4 8.4 0 0 1 12 21a7.4 7.4 0 0 1-2-.282V22.5A1.5 1.5 0 0 1 8.5 24H5.317a5.318 5.318 0 0 1-5.238-6.23l.4-2.024a3.351 3.351 0 0 1 6.077-1.266C7.658 16.1 9.745 18 12 18a7.18 7.18 0 0 0 6.292-4.5 1.5 1.5 0 0 1 1.415-1h.319a.98.98 0 0 0 .974-.976.88.88 0 0 0-.727-.87 1.5 1.5 0 0 1-1.223-1.318A7.07 7.07 0 0 0 12 3C7 3 5.68 5.944 4.52 8.543l-.125.28a12.84 12.84 0 0 0 7.075-3.387 1.5 1.5 0 1 1 2.115 2.126 14.3 14.3 0 0 1-3.524 2.548 1.506 1.506 0 1 1-1.959.855A17.8 17.8 0 0 1 1.385 12a1.5 1.5 0 0 1-.64-2.8 7 7 0 0 0 1.036-1.88C3 4.58 5.053-.002 12-.002a10.06 10.06 0 0 1 9.887 8.068A3.88 3.88 0 0 1 24 11.52a3.93 3.93 0 0 1-.762 2.321zM7 19.213a12.7 12.7 0 0 1-2.926-3.048.34.34 0 0 0-.3-.166.356.356 0 0 0-.342.3l-.4 2.023A2.32 2.32 0 0 0 5.318 21H7zm13.965-.93-.438-2.518A10.4 10.4 0 0 1 17 19.455v1.544h1.68a2.32 2.32 0 0 0 2.285-2.715"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
