/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-comment-user',
   styleUrl: './crai-icon-comment-user.css',
   shadow: true,
   })
export class CraiIconCommentUser {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M9.5 7.5a2.5 2.5 0 1 1 5 0 2.5 2.5 0 0 1-5 0m4.12 15.565L17.328 20H18.5a5.507 5.507 0 0 0 5.5-5.5v-9A5.507 5.507 0 0 0 18.5 0h-13A5.506 5.506 0 0 0 0 5.5v9A5.506 5.506 0 0 0 5.5 20h1.241l3.6 3.03c.461.41 1.058.637 1.675.636a2.4 2.4 0 0 0 1.604-.601M18.5 3A2.5 2.5 0 0 1 21 5.5v9a2.5 2.5 0 0 1-2.5 2.5h-1.712a1.5 1.5 0 0 0-.956.344L12 20.511l-3.745-3.158A1.5 1.5 0 0 0 7.289 17H5.5A2.5 2.5 0 0 1 3 14.5v-9A2.5 2.5 0 0 1 5.5 3zM7.981 14.232a.665.665 0 0 0 .673.768h6.661a.663.663 0 0 0 .673-.768c-.86-4.266-7.147-4.264-8.007 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
