/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-lock',
   styleUrl: './crai-icon-lock.css',
   shadow: true,
   })
export class CraiIconLock {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M19.044 8.51V7.044a7.044 7.044 0 1 0-14.088 0V8.51a5.54 5.54 0 0 0-3.02 4.925v5.031A5.54 5.54 0 0 0 7.473 24h9.057a5.54 5.54 0 0 0 5.534-5.535v-5.031a5.54 5.54 0 0 0-3.019-4.924M12 3.019a4.025 4.025 0 0 1 4.025 4.025V7.9h-8.05v-.855A4.025 4.025 0 0 1 12 3.02m7.044 15.446a2.516 2.516 0 0 1-2.515 2.516H7.472a2.516 2.516 0 0 1-2.516-2.516v-5.031a2.516 2.516 0 0 1 2.516-2.516h9.057a2.516 2.516 0 0 1 2.515 2.516z"/><path d="M11.497 13.937h1.006a1.51 1.51 0 0 1 0 3.019h-1.006a1.51 1.51 0 0 1 0-3.02"/></svg>
        </Host>
    );
  }
}
