/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-chess-piece',
   styleUrl: './crai-icon-chess-piece.css',
   shadow: true,
   })
export class CraiIconChessPiece {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.5 21H19v-.655a4.52 4.52 0 0 0-1.376-3.23A8.36 8.36 0 0 1 15.067 11H16a1.5 1.5 0 1 0 0-3h-.722a3.97 3.97 0 0 0 .747-2.312 10.54 10.54 0 0 0-1.681-4.416A2.73 2.73 0 0 0 12.026 0a2.73 2.73 0 0 0-2.318 1.272 10.5 10.5 0 0 0-1.682 4.416c.001.83.263 1.639.748 2.312H8.5a1.5 1.5 0 1 0 0 3h.457a8.38 8.38 0 0 1-2.582 6.116A4.52 4.52 0 0 0 5 20.345V21h-.5a1.5 1.5 0 1 0 0 3h15a1.5 1.5 0 1 0 0-3m-7.442-10a11.6 11.6 0 0 0 3.216 8H8.726a11.58 11.58 0 0 0 3.24-8z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
