/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-scissors',
   styleUrl: './crai-icon-scissors.css',
   shadow: true,
   })
export class CraiIconScissors {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19 14c-.65 0-1.294.128-1.895.377l-3.158-3.815 6.708-8.106a1.5 1.5 0 1 0-2.31-1.914L12 8.21 5.656.542a1.5 1.5 0 1 0-2.312 1.914l6.709 8.105L6.9 14.377A5.039 5.039 0 1 0 9.2 16.3l2.8-3.385 2.8 3.385A4.992 4.992 0 1 0 19 14M5 21a2 2 0 1 1 0-4.002A2 2 0 0 1 5 21m14 0a2 2 0 1 1 0-4.001 2 2 0 0 1 0 4"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
