/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-time-quarter-past',
   styleUrl: './crai-icon-time-quarter-past.css',
   shadow: true,
   })
export class CraiIconTimeQuarterPast {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M15.5 13.5h-2.19a1.99 1.99 0 0 1-2.81-2.81V7a1.5 1.5 0 1 1 3 0v3.5h2a1.5 1.5 0 1 1 0 3M12 0a1.5 1.5 0 0 0 0 3 9.01 9.01 0 0 1 9 9 1.5 1.5 0 1 0 3 0A12.013 12.013 0 0 0 12 0M3 12.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0M6.74 1.894a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M2.913 5.75a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M6.74 20.106a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M2.913 16.25a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M12 21a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m9.106-5.24a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m-3.856 3.827a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
