/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-home-location-alt',
   styleUrl: './crai-icon-home-location-alt.css',
   shadow: true,
   })
export class CraiIconHomeLocationAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 9.924V18.5a5.506 5.506 0 0 1-5.5 5.5 1.5 1.5 0 0 1 0-3 2.5 2.5 0 0 0 2.5-2.5V9.924a2.5 2.5 0 0 0-1.1-2.073L13.3 3.4a2.31 2.31 0 0 0-2.593 0L4.1 7.851A2.5 2.5 0 0 0 3 9.924V18.5A2.5 2.5 0 0 0 5.5 21a1.5 1.5 0 1 1 0 3A5.506 5.506 0 0 1 0 18.5V9.924a5.5 5.5 0 0 1 2.423-4.56L9.025.91a5.29 5.29 0 0 1 5.95 0l6.6 4.454A5.5 5.5 0 0 1 24 9.924M19 15a6.95 6.95 0 0 1-2.05 4.949l-3.593 3.515a1.93 1.93 0 0 1-2.712 0l-3.583-3.503A7 7 0 1 1 19 15m-3 0a4 4 0 1 0-6.829 2.828L12 20.6l2.84-2.779A3.96 3.96 0 0 0 16 15m-4-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
