/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-rotate-right',
   styleUrl: './crai-icon-rotate-right.css',
   shadow: true,
   })
export class CraiIconRotateRight {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.442 11.988a1.516 1.516 0 0 0-1.49 1.321 9.017 9.017 0 1 1-3.07-8.165l-1.13 1.131a1 1 0 0 0 .71 1.709h4.59a1 1 0 0 0 1.002-1V2.392a1.001 1.001 0 0 0-1.709-.708l-1.333 1.333C15.052-1.377 7.467-.918 3.072 4.042s-3.936 12.545 1.025 16.94c4.96 4.395 12.544 3.936 16.939-1.024a12 12 0 0 0 2.89-6.214 1.516 1.516 0 0 0-1.484-1.756"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
