/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-music-alt',
   styleUrl: './crai-icon-music-alt.css',
   shadow: true,
   })
export class CraiIconMusicAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.374 1.038a4.5 4.5 0 0 0-3.7-.96L9.486 1.8A5.5 5.5 0 0 0 5 7.206v8.935a4 4 0 0 0-1-.14 4 4 0 1 0 4 4v-8a1.5 1.5 0 0 1 1.224-1.475l11.183-2.1a.48.48 0 0 1 .412.106.5.5 0 0 1 .18.388v4.221a3.992 3.992 0 1 0 3 3.86V4.5a4.49 4.49 0 0 0-1.625-3.463m-2.52 4.441L8.672 7.577a4.5 4.5 0 0 0-.671.19v-.56a2.5 2.5 0 0 1 2.039-2.458l9.185-1.722A1.5 1.5 0 0 1 21 4.5v.976a3.5 3.5 0 0 0-1.145.003"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
