/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-paper-plane',
   styleUrl: './crai-icon-paper-plane.css',
   shadow: true,
   })
export class CraiIconPaperPlane {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M23 1.002a3.36 3.36 0 0 0-3.178-.905L4.536 3.309a5.313 5.313 0 0 0-2.979 9.014l1.64 1.64a.4.4 0 0 1 .118.287v3.023a3.41 3.41 0 0 0 3.408 3.408h3.023c.108 0 .212.042.288.119l1.639 1.638a5.28 5.28 0 0 0 5.451 1.28 5.28 5.28 0 0 0 3.563-4.258l3.212-15.238a3.38 3.38 0 0 0-.9-3.22M3.12 7.827a2.27 2.27 0 0 1 1.881-1.554l.105-.018 13.32-2.8L6.315 15.56v-1.31a3.38 3.38 0 0 0-1-2.41l-1.637-1.638a2.27 2.27 0 0 1-.557-2.375m14.62 11.067q-.011.052-.018.105a2.315 2.315 0 0 1-3.93 1.323l-1.637-1.638a3.38 3.38 0 0 0-2.41-1h-1.31L20.545 5.572z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
