/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-basketball',
   styleUrl: './crai-icon-basketball.css',
   shadow: true,
   })
export class CraiIconBasketball {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0a12 12 0 1 0 12 12A12.013 12.013 0 0 0 12 0m-1.332 15.453L12 14.121l5.207 5.207a8.95 8.95 0 0 1-4.169 1.607 11.9 11.9 0 0 0-2.37-5.482m2.664-6.906L12 9.879 6.794 4.672a8.94 8.94 0 0 1 4.167-1.607 11.9 11.9 0 0 0 2.371 5.482M9.879 12l-1.332 1.332a11.9 11.9 0 0 0-5.482-2.371 8.9 8.9 0 0 1 1.607-4.167zm4.242 0 1.332-1.332a11.9 11.9 0 0 0 5.482 2.371 8.94 8.94 0 0 1-1.607 4.168zm6.636-2.042a8.99 8.99 0 0 1-6.715-6.716 9.02 9.02 0 0 1 6.715 6.716M3.243 14.042a8.99 8.99 0 0 1 6.715 6.715 9.02 9.02 0 0 1-6.715-6.715"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
