/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-chart-pie-alt',
   styleUrl: './crai-icon-chart-pie-alt.css',
   shadow: true,
   })
export class CraiIconChartPieAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.556 11.385h-4.545a1.386 1.386 0 0 1-1.393-1.389V5.433a3.43 3.43 0 0 0-1.33-2.722A3.3 3.3 0 0 0 8.435 2.1 11.112 11.112 0 1 0 21.9 15.579a3.31 3.31 0 0 0-.61-2.858 3.5 3.5 0 0 0-2.734-1.336m.433 3.459a8.116 8.116 0 1 1-9.822-9.835.3.3 0 0 1 .072-.01c.074.004.144.03.2.078a.46.46 0 0 1 .176.356v4.561a4.39 4.39 0 0 0 4.393 4.39h4.545a.47.47 0 0 1 .435.311.3.3 0 0 1 .001.149"/><path d="M23.651 7.446A10.07 10.07 0 0 0 16.582.372 2.014 2.014 0 0 0 14.02 2.3V7a3 3 0 0 0 3 3h4.72a2.008 2.008 0 0 0 1.912-2.554"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
