/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-drink-alt',
   styleUrl: './crai-icon-drink-alt.css',
   shadow: true,
   })
export class CraiIconDrinkAlt {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M21.255 6.27A3.37 3.37 0 0 0 18.61 5h-3.489l.173-1.556A.5.5 0 0 1 15.79 3h3.71a1.5 1.5 0 0 0 0-3h-3.71a3.5 3.5 0 0 0-3.478 3.113L12.1 5H5.39a3.39 3.39 0 0 0-3.324 4.053l1.42 10.326A5.284 5.284 0 0 0 8.723 24h6.554a5.28 5.28 0 0 0 5.235-4.6l1.421-10.342a3.37 3.37 0 0 0-.678-2.788M18.61 8a.378.378 0 0 1 .38.474c-.009.041-.215 1.526-.215 1.526h-4.21l.222-2zm-13.524.146A.38.38 0 0 1 5.39 8h6.378l-.222 2h-6.32s-.207-1.487-.216-1.526a.38.38 0 0 1 .076-.328M15.277 21H8.723a2.284 2.284 0 0 1-2.262-2.012L5.637 13h12.726l-.826 6.006A2.28 2.28 0 0 1 15.277 21m-1.453-4.336-.11 1a1.5 1.5 0 1 1-2.983-.328l.111-1a1.499 1.499 0 0 1 2.933-.256 1.5 1.5 0 0 1 .05.584"/></svg>
        </Host>
    );
  }
}
