/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-italic',
   styleUrl: './crai-icon-italic.css',
   shadow: true,
   })
export class CraiIconItalic {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M21 0H6a1.5 1.5 0 1 0 0 3h5.713L9.259 21H3a1.5 1.5 0 1 0 0 3h15a1.5 1.5 0 1 0 0-3h-5.713l2.454-18H21a1.5 1.5 0 0 0 0-3"/></svg>
        </Host>
    );
  }
}
