/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-following',
   styleUrl: './crai-icon-following.css',
   shadow: true,
   })
export class CraiIconFollowing {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M7.452 14.018A8.19 8.19 0 0 0 0 22.282v.217a1.5 1.5 0 0 0 3 0v-.277a5.15 5.15 0 0 1 4.499-5.2A5.005 5.005 0 0 1 13 22v.5a1.5 1.5 0 1 0 2.999 0V22a8.01 8.01 0 0 0-8.547-7.981M8 12A6 6 0 1 0 8 0a6 6 0 0 0 0 12m0-9a3 3 0 1 1 0 6 3 3 0 0 1 0-6m13.998 4.875a2.107 2.107 0 0 0-2 2.2 2.107 2.107 0 0 0-2-2.2 2.107 2.107 0 0 0-2 2.2c0 1.73 2.257 3.756 3.38 4.658.363.29.878.29 1.24 0 1.124-.9 3.38-2.928 3.38-4.658a2.107 2.107 0 0 0-2-2.2"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
