/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-print',
   styleUrl: './crai-icon-print.css',
   shadow: true,
   })
export class CraiIconPrint {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M19.5 6H19V4.5A4.505 4.505 0 0 0 14.5 0h-5A4.505 4.505 0 0 0 5 4.5V6h-.5A4.505 4.505 0 0 0 0 10.5v6A4.505 4.505 0 0 0 4.5 21h.776A4.495 4.495 0 0 0 9.5 24h5a4.49 4.49 0 0 0 4.224-3h.776a4.505 4.505 0 0 0 4.5-4.5v-6A4.505 4.505 0 0 0 19.5 6M8 4.5A1.5 1.5 0 0 1 9.5 3h5A1.5 1.5 0 0 1 16 4.5V6H8zm8 15a1.5 1.5 0 0 1-1.5 1.5h-5A1.5 1.5 0 0 1 8 19.5v-2A1.5 1.5 0 0 1 9.5 16h5a1.5 1.5 0 0 1 1.5 1.5zm5-3a1.5 1.5 0 0 1-1.5 1.5H19v-.5a4.505 4.505 0 0 0-4.5-4.5h-5A4.505 4.505 0 0 0 5 17.5v.5h-.5A1.5 1.5 0 0 1 3 16.5v-6A1.5 1.5 0 0 1 4.5 9h15a1.5 1.5 0 0 1 1.5 1.5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
