/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-cloud-disabled',
   styleUrl: './crai-icon-cloud-disabled.css',
   shadow: true,
   })
export class CraiIconCloudDisabled {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.082 19.961a7.6 7.6 0 0 0 1.893-4.461 8.11 8.11 0 0 0-5.749-8.434.49.49 0 0 1-.328-.335A8.19 8.19 0 0 0 4.939 2.818L2.561.439A1.5 1.5 0 1 0 .439 2.561l21 21a1.5 1.5 0 1 0 2.122-2.122zM9.31 4.057a5.17 5.17 0 0 1 5.724 3.565 3.5 3.5 0 0 0 2.313 2.313 5.126 5.126 0 0 1 3.637 5.33 4.56 4.56 0 0 1-1.037 2.561L7.091 4.97a5.1 5.1 0 0 1 2.219-.913M16 21.5a1.5 1.5 0 0 1-1.5 1.5H5.97a6.06 6.06 0 0 1-5.91-4.937A5.76 5.76 0 0 1 2.346 12.6a.45.45 0 0 0 .109-.532 8 8 0 0 1-.374-1.259 1.5 1.5 0 1 1 2.935-.618q.085.405.235.791a3.41 3.41 0 0 1-1.126 4.033 2.73 2.73 0 0 0-1.1 2.623A3.1 3.1 0 0 0 5.97 20h8.53a1.5 1.5 0 0 1 1.5 1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
