/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-shopping-bag',
   styleUrl: './crai-icon-shopping-bag.css',
   shadow: true,
   })
export class CraiIconShoppingBag {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.5 6.2H18V6A6 6 0 1 0 6 6v.2H3.5A3.543 3.543 0 0 0 0 9.7v8.8A5.55 5.55 0 0 0 5.5 24h13a5.55 5.55 0 0 0 5.5-5.5V9.7a3.543 3.543 0 0 0-3.5-3.5M9 6a3 3 0 1 1 6 0v.2H9zm12 12.5a2.476 2.476 0 0 1-2.5 2.5h-13A2.476 2.476 0 0 1 3 18.5V9.7a.472.472 0 0 1 .5-.5H6v1.3a1.5 1.5 0 0 0 3 0V9.2h6v1.3a1.5 1.5 0 1 0 3 0V9.2h2.5a.472.472 0 0 1 .5.5z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
