/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-pulse',
   styleUrl: './crai-icon-pulse.css',
   shadow: true,
   })
export class CraiIconPulse {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M18.5 0h-13A5.506 5.506 0 0 0 0 5.5v8A5.506 5.506 0 0 0 5.5 19h5v2h-3a1.5 1.5 0 1 0 0 3h9a1.5 1.5 0 1 0 0-3h-3v-2h5a5.506 5.506 0 0 0 5.5-5.5v-8A5.506 5.506 0 0 0 18.5 0M21 13.5a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 13.5v-8A2.5 2.5 0 0 1 5.5 3h13A2.5 2.5 0 0 1 21 5.5zm-2-4a1.5 1.5 0 0 1-1.5 1.5h-1.2l-1.555 2.332A1.5 1.5 0 0 1 13.5 14h-.093a1.5 1.5 0 0 1-1.249-.826l-1.844-3.691-.566.849A1.5 1.5 0 0 1 8.5 11h-2a1.5 1.5 0 1 1 0-3h1.2l1.552-2.332a1.5 1.5 0 0 1 2.59.161l1.844 3.688.566-.849A1.5 1.5 0 0 1 15.5 8h2A1.5 1.5 0 0 1 19 9.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
