/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-line-width',
   styleUrl: './crai-icon-line-width.css',
   shadow: true,
   })
export class CraiIconLineWidth {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21 24H3a3 3 0 0 1 0-6h18a3 3 0 0 1 0 6m3-10.5a2.5 2.5 0 0 0-2.5-2.5h-19a2.5 2.5 0 0 0 0 5h19a2.5 2.5 0 0 0 2.5-2.5M24 7a2 2 0 0 0-2-2H2a2 2 0 1 0 0 4h20a2 2 0 0 0 2-2m0-5.5A1.5 1.5 0 0 0 22.5 0h-21a1.5 1.5 0 0 0 0 3h21A1.5 1.5 0 0 0 24 1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
