/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-sphere',
   styleUrl: './crai-icon-sphere.css',
   shadow: true,
   })
export class CraiIconSphere {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 0a12 12 0 1 0 12 12A12.013 12.013 0 0 0 12 0m0 15.272c-5.41 0-9-1.972-9-3.272s3.59-3.272 9-3.272S21 10.7 21 12s-3.59 3.272-9 3.272M12 3a9 9 0 0 1 7.5 4.039A20.2 20.2 0 0 0 12 5.728a20.2 20.2 0 0 0-7.5 1.311A9 9 0 0 1 12 3m0 18a9 9 0 0 1-7.5-4.039 20.2 20.2 0 0 0 7.5 1.311c2.56.043 5.106-.402 7.5-1.311A9 9 0 0 1 12 21"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
