/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-data-transfer',
   styleUrl: './crai-icon-data-transfer.css',
   shadow: true,
   })
export class CraiIconDataTransfer {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M8.5 0h-4A4.505 4.505 0 0 0 0 4.5v1A4.505 4.505 0 0 0 4.5 10H5v1h-.5a1.5 1.5 0 1 0 0 3h4a1.5 1.5 0 1 0 0-3H8v-1h.5A4.505 4.505 0 0 0 13 5.5v-1A4.505 4.505 0 0 0 8.5 0M10 5.5A1.5 1.5 0 0 1 8.5 7h-4A1.5 1.5 0 0 1 3 5.5v-1A1.5 1.5 0 0 1 4.5 3h4A1.5 1.5 0 0 1 10 4.5zm5-1A1.5 1.5 0 0 1 16.5 3h1A3.5 3.5 0 0 1 21 6.5v1a1.5 1.5 0 1 1-3 0v-1a.5.5 0 0 0-.5-.5h-1A1.5 1.5 0 0 1 15 4.5m-2 16a1.5 1.5 0 0 1-1.5 1.5h-3A3.5 3.5 0 0 1 5 18.5v-1a1.5 1.5 0 0 1 3 0v1a.5.5 0 0 0 .5.5h3a1.5 1.5 0 0 1 1.5 1.5m8-9.5h-3a3 3 0 0 0-3 3v7a3 3 0 0 0 3 3h3a3 3 0 0 0 3-3v-7a3 3 0 0 0-3-3m-1.5 11a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
