/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-diploma',
   styleUrl: './crai-icon-diploma.css',
   shadow: true,
   })
export class CraiIconDiploma {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M7 11.5A1.5 1.5 0 0 1 8.5 10h3a1.5 1.5 0 1 1 0 3h-3A1.5 1.5 0 0 1 7 11.5M8.5 8h7a1.5 1.5 0 0 0 0-3h-7a1.5 1.5 0 0 0 0 3M21 19.974v2.942a1.083 1.083 0 0 1-1.847.765L18 22.528l-1.153 1.153A1.082 1.082 0 0 1 15 22.916v-2.942a4.989 4.989 0 0 1 4-8.874V5.5A2.5 2.5 0 0 0 16.5 3l-8.993.038A2.5 2.5 0 0 0 5 5.538V17.5A2.5 2.5 0 0 0 7.5 20h4a1.5 1.5 0 1 1 0 3h-4A5.507 5.507 0 0 1 2 17.5V5.538a5.507 5.507 0 0 1 5.5-5.5L16.493 0A5.51 5.51 0 0 1 22 5.5v7.531a4.93 4.93 0 0 1-1 6.943M16 16a2 2 0 1 0 4 0 2 2 0 0 0-4 0"/></svg>
        </Host>
    );
  }
}
