/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-mountains',
   styleUrl: './crai-icon-mountains.css',
   shadow: true,
   })
export class CraiIconMountains {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.5 7a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7m.562 17h-8.126a2.92 2.92 0 0 1-2.544-1.446 2.82 2.82 0 0 1-.025-2.83l4.066-7.235a2.98 2.98 0 0 1 5.136 0l4.063 7.232a2.82 2.82 0 0 1-.025 2.832A2.92 2.92 0 0 1 21.062 24m-4.07-9.977L13.106 21h7.812zM8 22.5A1.5 1.5 0 0 0 6.5 21H3.712a.69.69 0 0 1-.608-.347.7.7 0 0 1-.015-.7L9.35 8.372a.707.707 0 0 1 1.245 0l.622 1.15A1.5 1.5 0 1 0 13.855 8.1l-.622-1.151a3.733 3.733 0 0 0-6.522 0L.451 18.521A3.713 3.713 0 0 0 3.711 24H6.5A1.5 1.5 0 0 0 8 22.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
