/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-microphone',
   styleUrl: './crai-icon-microphone.css',
   shadow: true,
   })
export class CraiIconMicrophone {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M12 19a7.01 7.01 0 0 0 7-7V7A7 7 0 0 0 5 7v5a7.01 7.01 0 0 0 7 7m0-16a4 4 0 0 1 4 4v1h-1.5a1.5 1.5 0 0 0 0 3H16v1a4 4 0 1 1-8 0v-1h1.5a1.5 1.5 0 1 0 0-3H8V7a4 4 0 0 1 4-4"/><path d="M22.5 11.5A1.5 1.5 0 0 0 21 13v.39A7.62 7.62 0 0 1 13.389 21h-2.778A7.62 7.62 0 0 1 3 13.39V13a1.5 1.5 0 0 0-3 0v.39A10.623 10.623 0 0 0 10.611 24h2.778A10.623 10.623 0 0 0 24 13.39V13a1.5 1.5 0 0 0-1.5-1.5"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
