/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-test-tube',
   styleUrl: './crai-icon-test-tube.css',
   shadow: true,
   })
export class CraiIconTestTube {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><path d="M17.5 0h-11a1.5 1.5 0 1 0 0 3H7v16a5 5 0 1 0 10 0V3h.5a1.5 1.5 0 0 0 0-3M12 21a2 2 0 0 1-2-2v-9h4v9a2 2 0 0 1-2 2m2-14h-4V3h4z"/></svg>
        </Host>
    );
  }
}
