/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-undo',
   styleUrl: './crai-icon-undo.css',
   shadow: true,
   })
export class CraiIconUndo {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M21 21.95a4.5 4.5 0 0 0-4.5-4.5h-5.668v1.68A2.214 2.214 0 0 1 7 20.635L.778 13.941a2.94 2.94 0 0 1 0-3.985L7 3.261a2.214 2.214 0 0 1 3.837 1.507V6.45H14.5a9.51 9.51 0 0 1 9.5 9.5v6a1.5 1.5 0 1 1-3 0m0-6a6.51 6.51 0 0 0-6.5-6.5H9.332a1.5 1.5 0 0 1-1.5-1.5v-1.2L2.977 11.9l4.855 5.228V15.95a1.5 1.5 0 0 1 1.5-1.5H16.5a7.46 7.46 0 0 1 4.5 1.503z"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
