/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-ship',
   styleUrl: './crai-icon-ship.css',
   shadow: true,
   })
export class CraiIconShip {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M22.5 18.972a1.473 1.473 0 0 0-1.5 1.471 1.28 1.28 0 0 1-1.125.557 1.66 1.66 0 0 1-.766-.183 12.15 12.15 0 0 0 2.84-5.9 3.41 3.41 0 0 0-1.95-3.7V8.5A4.505 4.505 0 0 0 15.5 4H15V3a3 3 0 1 0-6 0v1h-.5A4.505 4.505 0 0 0 4 8.5v2.583a3.41 3.41 0 0 0-1.928 3.691 13 13 0 0 0 2.822 6.046 1.7 1.7 0 0 1-.768.18A1.32 1.32 0 0 1 3 20.452a1.5 1.5 0 0 0-3 .048C0 22.364 1.928 24 4.125 24a4.64 4.64 0 0 0 2.628-.81A4.67 4.67 0 0 0 12 23.2a4.68 4.68 0 0 0 5.258-.011 4.63 4.63 0 0 0 2.617.811C22.072 24 24 22.364 24 20.5a1.52 1.52 0 0 0-1.5-1.528M8.5 7h7A1.5 1.5 0 0 1 17 8.5v1.8l-3.924-1.126a3.35 3.35 0 0 0-2.066-.026L7 10.221V8.5A1.5 1.5 0 0 1 8.5 7m.875 14a1.37 1.37 0 0 1-1.136-.488 5.3 5.3 0 0 0-.9-1.453 10 10 0 0 1-2.311-4.789.45.45 0 0 1 .185-.468l5.287-1.414v8.149A1.4 1.4 0 0 1 9.375 21m5.25 0a1.67 1.67 0 0 1-1.125-.409v-8.173l5.239 1.512a.434.434 0 0 1 .254.487 9.26 9.26 0 0 1-2.326 4.638c-.38.435-.686.93-.906 1.463a1.37 1.37 0 0 1-1.136.482"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
