/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-gem',
   styleUrl: './crai-icon-gem.css',
   shadow: true,
   })
export class CraiIconGem {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M1.762 8.375.98 9.382a4.653 4.653 0 0 0 .581 6.332L9.2 22.955a4.2 4.2 0 0 0 2.779 1.038c1.053 0 2.07-.385 2.859-1.081l7.56-7.143a4.63 4.63 0 0 0 .671-6.3l-.752-1.007A6.19 6.19 0 0 0 17.376 6H6.639a6.2 6.2 0 0 0-4.877 2.375m1.59 2.846.779-1.006A3.19 3.19 0 0 1 6.639 9h2.425l-.573 1.406a5.2 5.2 0 0 0-.367 2.094h7.717a5.15 5.15 0 0 0-.357-2.214L14.961 9h2.415a3.18 3.18 0 0 1 2.541 1.261l.752 1.007a1.62 1.62 0 0 1 .3 1.232h-5.128a5.2 5.2 0 0 1-.319 1.6l-2.969 6.75a1.23 1.23 0 0 1-1.117 0l-2.982-6.626a5.2 5.2 0 0 1-.33-1.724h-5.1a1.64 1.64 0 0 1 .328-1.279M16.439.44l-1 1a1.5 1.5 0 1 0 2.122 2.121l1-1A1.5 1.5 0 1 0 16.439.44M7.5 4a1.5 1.5 0 0 0 1.06-2.56l-1-1a1.5 1.5 0 0 0-2.12 2.12l1 1A1.5 1.5 0 0 0 7.5 4m3-2.5v1a1.5 1.5 0 1 0 3 0v-1a1.5 1.5 0 1 0-3 0"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
