/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-envelope-plus',
   styleUrl: './crai-icon-envelope-plus.css',
   shadow: true,
   })
export class CraiIconEnvelopePlus {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M24 12.5v6a5.506 5.506 0 0 1-5.5 5.5h-13A5.506 5.506 0 0 1 0 18.5v-10A5.506 5.506 0 0 1 5.5 3h4a1.5 1.5 0 0 1 0 3h-4a2.49 2.49 0 0 0-2.2 1.336l6.931 6.932a2.56 2.56 0 0 0 3.536 0l1.224-1.3a1.5 1.5 0 1 1 2.182 2.06l-1.255 1.328a5.52 5.52 0 0 1-7.808.032L3 11.278V18.5A2.5 2.5 0 0 0 5.5 21h13a2.5 2.5 0 0 0 2.5-2.5v-6a1.5 1.5 0 1 1 3 0M14.5 7H17v2.5a1.5 1.5 0 1 0 3 0V7h2.5a1.5 1.5 0 0 0 0-3H20V1.5a1.5 1.5 0 1 0-3 0V4h-2.5a1.5 1.5 0 0 0 0 3"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
