/* This file is auto-generated by generate-icon-components.js. Do not edit it manually. */
import { Component, Host, Prop, h } from '@stencil/core';

   @Component({
   tag: 'crai-icon-mars',
   styleUrl: './crai-icon-mars.css',
   shadow: true,
   })
export class CraiIconMars {
  @Prop() color = 'var(--crai-icon-color, currentColor)';
  @Prop() size: number | string = '1.2rem';

  private get _size() {
    return typeof this.size === 'number' ? `${this.size}px` : this.size;
  }

  render() {
    return (
        <Host>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width={this._size} height={this._size} fill={this.color}><g clip-path="url(#a)"><path d="M20.506 0h-3.993a1.498 1.498 0 0 0 0 2.995h2.375l-5.52 5.52a8.506 8.506 0 1 0 2.118 2.117l5.52-5.52v2.375a1.497 1.497 0 1 0 2.994 0V3.494A3.494 3.494 0 0 0 20.506 0M8.526 20.964a5.49 5.49 0 1 1 0-10.98 5.49 5.49 0 0 1 0 10.98"/></g><defs><clipPath id="a"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>
        </Host>
    );
  }
}
